export interface RawQuestionData {
  subjectCode: string;
  topicKeyword: string;
  year: number;
  shift?: string;
  paper?: string;
  questionType: 'MCQ' | 'MSQ' | 'NAT';
  difficulty: 'EASY' | 'MEDIUM' | 'HARD';
  questionText: string;
  options: { id: string; text: string }[];
  correctAnswers: string[] | { min: number; max: number };
  marks: number;
  negativeMarks: number;
  avgExpectedSeconds: number;
  explanation: string;
  formulaConcept: string;
  shortcutTrick: string;
  commonMistake: string;
  sourceRef: string;
}

export const gateQuestions: RawQuestionData[] = [
  // --- 2024 ---
  {
    subjectCode: 'GATE_CS_OS',
    topicKeyword: 'Deadlock',
    year: 2024,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Consider a system with 5 processes, $P_0$ through $P_4$ and 3 resource types $A, B, C$. Resource type $A$ has 10 instances, $B$ has 5, and $C$ has 7. Which of the following conditions is both necessary and sufficient for a system state to be safe under the Banker\'s Algorithm?',
    options: [
      { id: 'A', text: 'There exists at least one safe sequence in which all processes can execute to completion.' },
      { id: 'B', text: 'All resource requests are satisfied immediately without blocking.' },
      { id: 'C', text: 'No process requests more resources than the total available resources in the system.' },
      { id: 'D', text: 'Deadlock detection algorithm detects zero cycles in the resource allocation graph.' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: 'By definition in Dijkstra\'s Banker\'s Algorithm, a state is considered safe if and only if there exists at least one safe sequence <P_1, P_2, ..., P_n> such that for each P_i, the resources that P_i can still request can be satisfied by currently available resources plus resources held by all prior processes P_j (j < i).',
    formulaConcept: '$\\text{Need}[i][j] = \\text{Max}[i][j] - \\text{Allocation}[i][j]$',
    shortcutTrick: 'Safe state definition requires the existence of a safe sequence. Absence of cycles is only sufficient for single-instance graphs.',
    commonMistake: 'Confusing single-instance resource cycle detection with multi-instance Banker safe sequence.',
    sourceRef: 'GATE CS 2024 Set 1 Question 18',
  },
  {
    subjectCode: 'GATE_CS_OS',
    topicKeyword: 'Memory',
    year: 2024,
    shift: 'Shift 2',
    questionType: 'NAT',
    difficulty: 'MEDIUM',
    questionText: 'In a paging system with Translation Lookaside Buffer (TLB), TLB access time is $10\\,\\text{ns}$ and main memory access time is $80\\,\\text{ns}$. If the TLB hit ratio is $90\\%$, and page table lookup requires a single memory access on TLB miss, what is the Effective Memory Access Time (EMAT) in nanoseconds?',
    options: [],
    correctAnswers: { min: 97.9, max: 98.1 },
    marks: 2.0,
    negativeMarks: 0.0,
    avgExpectedSeconds: 60,
    explanation: '$\\text{EMAT} = h \\times (t_{\\text{TLB}} + t_{\\text{mem}}) + (1 - h) \\times (t_{\\text{TLB}} + 2 \\times t_{\\text{mem}})$\n$= 0.90 \\times (10 + 80) + 0.10 \\times (10 + 2 \\times 80)$\n$= 0.90 \\times 90 + 0.10 \\times 170 = 81 + 17 = 98\\,\\text{ns}$.',
    formulaConcept: '$\\text{EMAT} = h(t_{\\text{TLB}} + m) + (1-h)(t_{\\text{TLB}} + 2m)$',
    shortcutTrick: '$\\text{Base} = t_{\\text{TLB}} + m = 90\\,\\text{ns}$. Add miss penalty $(1-h) \\times m = 0.1 \\times 80 = 8\\,\\text{ns} \\implies 98\\,\\text{ns}$.',
    commonMistake: 'Forgetting to include TLB access time in the miss case.',
    sourceRef: 'GATE CS 2024 Set 2 NAT 39',
  },
  {
    subjectCode: 'GATE_CS_ALGO',
    topicKeyword: 'Asymptotic',
    year: 2024,
    shift: 'Shift 1',
    questionType: 'MSQ',
    difficulty: 'MEDIUM',
    questionText: 'Which of the following statements is/are TRUE regarding asymptotic notations for non-negative functions $f(n)$ and $g(n)$?',
    options: [
      { id: 'A', text: '$f(n) = O(g(n))$ implies $g(n) = \\Omega(f(n))$' },
      { id: 'B', text: '$f(n) = \\Theta(g(n))$ if and only if $f(n) = O(g(n))$ and $f(n) = \\Omega(g(n))$' },
      { id: 'C', text: '$2^{n+1} = O(2^n)$' },
      { id: 'D', text: '$2^{2n} = O(2^n)$' },
    ],
    correctAnswers: ['A', 'B', 'C'],
    marks: 2.0,
    negativeMarks: 0.0,
    avgExpectedSeconds: 60,
    explanation: 'Analysis of options:\n- A is TRUE: By definition of Big-O and Big-Omega transpose symmetry.\n- B is TRUE: By definition of tight bound Theta notation.\n- C is TRUE: $2^{n+1} = 2 \\times 2^n \\le c \\cdot 2^n$ with $c = 2$ for all $n \\ge 1$.\n- D is FALSE: $2^{2n} = 4^n$. As $n \\to \\infty$, $4^n / 2^n = 2^n \\to \\infty$, so $4^n \\ne O(2^n)$.',
    formulaConcept: '$f(n) = O(g(n)) \\iff \\exists c > 0, n_0 : 0 \\le f(n) \\le c \\cdot g(n)$',
    shortcutTrick: 'Constant factor in exponents changes asymptotic order ($2^{2n} = 4^n$), but constant addition in exponents does not ($2^{n+1} = 2 \\cdot 2^n$).',
    commonMistake: 'Selecting Option D thinking that both are powers of 2.',
    sourceRef: 'GATE CS 2024 Set 1 MSQ 27',
  },
  {
    subjectCode: 'GATE_CS_CN',
    topicKeyword: 'TCP',
    year: 2024,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In TCP Tahoe congestion control, when a timeout occurs with current congestion window $\\text{cwnd} = 32\\text{ KB}$, what will be the values of slow start threshold ($\\text{ssthresh}$) and $\\text{cwnd}$ immediately after the timeout?',
    options: [
      { id: 'A', text: 'ssthresh = 16 KB, cwnd = 1 MSS (1 KB)' },
      { id: 'B', text: 'ssthresh = 16 KB, cwnd = 16 KB' },
      { id: 'C', text: 'ssthresh = 32 KB, cwnd = 1 MSS (1 KB)' },
      { id: 'D', text: 'ssthresh = 8 KB, cwnd = 16 KB' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'In TCP Tahoe upon timeout:\n1. $\\text{ssthresh} = \\max(\\text{cwnd}/2, 2 \\text{ MSS}) = 32/2 = 16\\text{ KB}$.\n2. $\\text{cwnd}$ is reset to 1 MSS (1 KB) and Slow Start phase begins again.',
    formulaConcept: '$\\text{ssthresh} = \\frac{\\text{cwnd}}{2}, \\quad \\text{cwnd} = 1\\text{ MSS}$',
    shortcutTrick: 'Any TIMEOUT in TCP always drops cwnd down to 1 MSS.',
    commonMistake: 'Confusing 3 duplicate ACKs (Fast Recovery) with timeout.',
    sourceRef: 'GATE CS 2024 Set 2 Question 14',
  },
  {
    subjectCode: 'GATE_CS_COA',
    topicKeyword: 'Pipelining',
    year: 2024,
    shift: 'Shift 1',
    questionType: 'NAT',
    difficulty: 'MEDIUM',
    questionText: 'A 5-stage pipeline has stage delays of $150\\,\\text{ps}, 120\\,\\text{ps}, 160\\,\\text{ps}, 140\\,\\text{ps}, 110\\,\\text{ps}$. The pipeline register delay is $10\\,\\text{ps}$. What is the clock cycle time of this pipeline in picoseconds?',
    options: [],
    correctAnswers: { min: 169.9, max: 170.1 },
    marks: 1.0,
    negativeMarks: 0.0,
    avgExpectedSeconds: 30,
    explanation: 'The pipeline cycle time is determined by the slowest stage plus the register delay:\n$\\text{Clock Cycle} = \\max(150, 120, 160, 140, 110) + 10 = 160 + 10 = 170\\,\\text{ps}$.',
    formulaConcept: '$t_{\\text{cycle}} = \\max(t_i) + t_{\\text{reg}}$',
    shortcutTrick: 'Find the maximum stage delay (160) and add register overhead (10) = 170 ps.',
    commonMistake: 'Averaging the stage delays instead of taking the maximum bottleneck stage.',
    sourceRef: 'GATE CS 2024 Set 1 NAT 42',
  },

  // --- 2023 ---
  {
    subjectCode: 'GATE_CS_OS',
    topicKeyword: 'CPU Scheduling',
    year: 2023,
    shift: 'Shift 2',
    questionType: 'NAT',
    difficulty: 'HARD',
    questionText: 'Consider three processes $P_1, P_2, P_3$ arriving at times 0, 1, 3 respectively with CPU burst times 6, 4, 2. The scheduling policy is Shortest Remaining Time First (SRTF). What is the average waiting time (in ms)?',
    options: [],
    correctAnswers: { min: 2.66, max: 3.01 },
    marks: 2.0,
    negativeMarks: 0.0,
    avgExpectedSeconds: 90,
    explanation: 'Gantt Chart execution:\n- t=0 to 1: P1 runs (remaining 5).\n- t=1 to 3: P2 arrives (burst 4 < 5), P2 runs (remaining 2).\n- t=3: P3 arrives (burst 2 = P2 remaining 2). P2 finishes at t=5.\n- t=5 to 7: P3 runs and finishes at t=7.\n- t=7 to 12: P1 runs and finishes at t=12.\nWaiting times: P1: 12-0-6=6; P2: 5-1-4=0; P3: 7-3-2=2.\nAvg = (6 + 0 + 2)/3 = 2.67 ms.',
    formulaConcept: '$W_i = C_i - A_i - B_i$',
    shortcutTrick: 'Draw the timeline horizontally and immediately mark completion times from right to left.',
    commonMistake: 'Forgetting to subtract arrival time when calculating waiting time.',
    sourceRef: 'GATE CS 2023 Set 2 NAT 44',
  },
  {
    subjectCode: 'GATE_CS_DBMS',
    topicKeyword: 'Normalization',
    year: 2023,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Given a relation $R(A, B, C, D)$ with functional dependencies: $F = \\{ AB \\to C, C \\to D, D \\to A \\}$. What is the highest normal form satisfied by relation $R$?',
    options: [
      { id: 'A', text: '1NF' },
      { id: 'B', text: '2NF' },
      { id: 'C', text: '3NF' },
      { id: 'D', text: 'BCNF' },
    ],
    correctAnswers: ['C'],
    marks: 2.0,
    negativeMarks: 0.66,
    avgExpectedSeconds: 75,
    explanation: 'Candidate keys are AB, BC, and BD. All attributes {A, B, C, D} are prime attributes! In 3NF: for every X -> Y, either X is superkey or Y is prime. Since all attributes are prime, every FD satisfies 3NF. But C -> D violates BCNF because C is not a superkey. Hence highest normal form is 3NF.',
    formulaConcept: '3NF Rule: For every non-trivial $X \\to Y$, either $X$ is superkey or $Y$ is prime attribute.',
    shortcutTrick: 'If ALL attributes in the relation belong to at least one candidate key, the relation is ALWAYS in 3NF automatically!',
    commonMistake: 'Missing the candidate key (BC) or (BD) and mistakenly concluding 2NF.',
    sourceRef: 'GATE CS 2023 Set 1 Question 32',
  },
  {
    subjectCode: 'GATE_CS_ALGO',
    topicKeyword: 'Graph',
    year: 2023,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'What is the time complexity of Dijkstra\'s Single Source Shortest Path algorithm on a directed graph with $|V|$ vertices and $|E|$ edges when implemented with a Min-Heap (Binary Heap)?',
    options: [
      { id: 'A', text: '$O(|E| \\log |V|)$' },
      { id: 'B', text: '$O(|V|^2)$' },
      { id: 'C', text: '$O(|V| + |E|)$' },
      { id: 'D', text: '$O(|E| + |V| \\log |V|)$' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'With a Binary Heap: Extract-Min takes $O(\\log |V|)$ done $|V|$ times $\\implies O(|V| \\log |V|)$. Decrease-Key takes $O(\\log |V|)$ done at most $|E|$ times $\\implies O(|E| \\log |V|)$. Total time is $O((|V| + |E|) \\log |V|) = O(|E| \\log |V|)$ for connected graphs.',
    formulaConcept: '$T = |V| \\cdot T_{\\text{extract-min}} + |E| \\cdot T_{\\text{decrease-key}}$',
    shortcutTrick: 'Binary heap = $O(E \\log V)$, Fibonacci heap = $O(E + V \\log V)$, Adjacency Matrix = $O(V^2)$.',
    commonMistake: 'Confusing binary heap complexity with Fibonacci heap complexity.',
    sourceRef: 'GATE CS 2023 Set 1 Question 22',
  },
  {
    subjectCode: 'GATE_CS_TOC',
    topicKeyword: 'Automata',
    year: 2023,
    shift: 'Shift 2',
    questionType: 'NAT',
    difficulty: 'MEDIUM',
    questionText: 'What is the MINIMUM number of states in a Minimal Deterministic Finite Automaton (DFA) that accepts all binary strings containing "101" as a substring?',
    options: [],
    correctAnswers: { min: 4, max: 4 },
    marks: 1.0,
    negativeMarks: 0.0,
    avgExpectedSeconds: 40,
    explanation: 'To recognize substring "101" of length 3:\n- State 0: Initial state (seen nothing matching 101).\n- State 1: Seen prefix "1".\n- State 2: Seen prefix "10".\n- State 3: Seen "101" (Dead/Accepting trap state).\nTotal states = $3 + 1 = 4$ states.',
    formulaConcept: 'For any string pattern of length $m$, minimal DFA for substring acceptance requires exactly $(m + 1)$ states.',
    shortcutTrick: 'Substring of length $k$ over alphabet $\\Sigma$ requires $k + 1$ states.',
    commonMistake: 'Thinking 3 states are enough, forgetting the initial state $q_0$.',
    sourceRef: 'GATE CS 2023 Set 2 NAT 36',
  },

  // --- 2022 ---
  {
    subjectCode: 'GATE_CS_OS',
    topicKeyword: 'Paging',
    year: 2022,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Bélády\'s Anomaly in page replacement algorithms refers to the phenomenon where:',
    options: [
      { id: 'A', text: 'Increasing the number of page frames results in an increase in the number of page faults.' },
      { id: 'B', text: 'The page fault rate drops exponentially with small frame increments.' },
      { id: 'C', text: 'LRU replacement causes thrashing faster than FIFO.' },
      { id: 'D', text: 'Optimal page replacement cannot be implemented in hardware.' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Bélády\'s Anomaly is the counter-intuitive phenomenon where increasing page frame allocation leads to more page faults. It can occur in FIFO and Second Chance page replacement, but NEVER in Stack algorithms (like LRU and Optimal).',
    formulaConcept: 'Stack Algorithms (LRU, LFU, OPT) are mathematically immune to Bélády\'s Anomaly.',
    shortcutTrick: 'FIFO suffers from Bélády\'s Anomaly; LRU is immune.',
    commonMistake: 'Thinking LRU can exhibit Bélády\'s Anomaly.',
    sourceRef: 'GATE CS 2022 Set 1 Question 15',
  },
  {
    subjectCode: 'GATE_CS_ALGO',
    topicKeyword: 'Asymptotic',
    year: 2022,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'According to Master Theorem, what is the asymptotic solution of the recurrence relation $T(n) = 4T(n/2) + n^2$ with $T(1) = 1$?',
    options: [
      { id: 'A', text: '$\\Theta(n^2 \\log n)$' },
      { id: 'B', text: '$\\Theta(n^2)$' },
      { id: 'C', text: '$\\Theta(n^3)$' },
      { id: 'D', text: '$\\Theta(n^{\\log_2 3})$' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: 'Here $a = 4, b = 2, f(n) = n^2$.\n$n^{\\log_b a} = n^{\\log_2 4} = n^2$.\nSince $f(n) = \\Theta(n^{\\log_b a}) = \\Theta(n^2)$, this falls under Case 2 of Master Theorem:\n$T(n) = \\Theta(n^{\\log_b a} \\log n) = \\Theta(n^2 \\log n)$.',
    formulaConcept: 'Master Theorem Case 2: $f(n) = \\Theta(n^{\\log_b a}) \\implies T(n) = \\Theta(n^{\\log_b a} \\log n)$',
    shortcutTrick: 'When polynomial work matches the recursive tree leaves ($n^2 = n^{\\log_2 4}$), multiply by $\\log n$.',
    commonMistake: 'Applying Case 1 and dropping the $\\log n$ factor.',
    sourceRef: 'GATE CS 2022 Set 2 Question 26',
  },
  {
    subjectCode: 'GATE_CS_DBMS',
    topicKeyword: 'Transaction',
    year: 2022,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A schedule $S$ of concurrent transactions is conflict serializable if and only if its precedence graph (serialization graph) is:',
    options: [
      { id: 'A', text: 'Acyclic (contains no directed cycles)' },
      { id: 'B', text: 'A complete bipartite graph' },
      { id: 'C', text: 'Strongly connected' },
      { id: 'D', text: 'Eulerian' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Theorem: A concurrent schedule $S$ is conflict serializable if and only if the precedence graph $G(S)$ constructed from all conflicting pairs of operations (Read-Write, Write-Read, Write-Write on the same item) contains NO directed cycles (acyclic). The equivalent serial order is given by the Topological Sort of $G(S)$.',
    formulaConcept: 'Conflict Serializable $\\iff$ Precedence Graph is Directed Acyclic Graph (DAG).',
    shortcutTrick: 'Cycle in graph = NOT conflict serializable. No cycle = Conflict serializable via topological sort.',
    commonMistake: 'Confusing conflict serializability with view serializability (which is NP-complete).',
    sourceRef: 'GATE CS 2022 Set 1 Question 31',
  },

  // --- 2021 ---
  {
    subjectCode: 'GATE_CS_CN',
    topicKeyword: 'Subnetting',
    year: 2021,
    shift: 'Shift 1',
    questionType: 'NAT',
    difficulty: 'MEDIUM',
    questionText: 'An organization is allocated an IP prefix $200.10.0.0/20$. The organization wants to create 8 equal-sized subnets. What is the number of usable host IP addresses in each subnet?',
    options: [],
    correctAnswers: { min: 510, max: 510 },
    marks: 2.0,
    negativeMarks: 0.0,
    avgExpectedSeconds: 60,
    explanation: '1. Original prefix length = 20 bits. Total host bits = $32 - 20 = 12$ bits.\n2. To create 8 ($2^3$) subnets, we borrow 3 bits from the host portion.\n3. New subnet prefix = $20 + 3 = /23$.\n4. Remaining host bits per subnet = $32 - 23 = 9$ bits.\n5. Total IP addresses per subnet = $2^9 = 512$.\n6. Usable host addresses = $2^9 - 2$ = 510.',
    formulaConcept: '$\\text{Usable Hosts} = 2^{(32 - \\text{CIDR})} - 2$',
    shortcutTrick: 'Borrow 3 bits for 8 subnets $\\implies$ 9 host bits remaining $\\implies 2^9 - 2 = 510$.',
    commonMistake: 'Forgetting to subtract 2 for network and broadcast addresses.',
    sourceRef: 'GATE CS 2021 Set 1 NAT 48',
  },
  {
    subjectCode: 'GATE_CS_OS',
    topicKeyword: 'Synchronization',
    year: 2021,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A counting semaphore $S$ is initialized to 7. Then, $20\\,P$ (wait) operations and $15\\,V$ (signal) operations are performed in some order. What is the final value of the semaphore $S$?',
    options: [
      { id: 'A', text: '2' },
      { id: 'B', text: '12' },
      { id: 'C', text: '-2' },
      { id: 'D', text: '0' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Counting semaphore value calculation:\n$\\text{Final Value} = \\text{Initial Value} - \\text{Number of } P\\text{ (wait) ops} + \\text{Number of } V\\text{ (signal) ops}$\n$= 7 - 20 + 15 = 2$.',
    formulaConcept: '$S_{\\text{final}} = S_0 - \\#P + \\#V$',
    shortcutTrick: '$P$ decrements by 1, $V$ increments by 1. $7 - 20 + 15 = 2$.',
    commonMistake: 'Assuming semaphore cannot go negative during execution; the net algebraic value is simply $7 - 20 + 15 = 2$.',
    sourceRef: 'GATE CS 2021 Set 2 Question 19',
  },
  {
    subjectCode: 'GATE_CS_COA',
    topicKeyword: 'Cache',
    year: 2021,
    shift: 'Shift 1',
    questionType: 'NAT',
    difficulty: 'HARD',
    questionText: 'Consider a 4-way set associative cache memory with 64 KB total data capacity and 64-byte line (block) size. The processor generates 32-bit byte physical addresses. What is the size of the TAG field in bits?',
    options: [],
    correctAnswers: { min: 18, max: 18 },
    marks: 2.0,
    negativeMarks: 0.0,
    avgExpectedSeconds: 60,
    explanation: '1. Cache size = $64\\text{ KB} = 2^{16}$ bytes.\n2. Block size = $64\\text{ bytes} = 2^6$ bytes $\\implies \\text{Block Offset} = 6$ bits.\n3. Total number of lines = $\\frac{2^{16}}{2^6} = 2^{10} = 1024$ lines.\n4. 4-way set associative $\\implies$ Number of sets = $\\frac{1024}{4} = 256 = 2^8$ sets $\\implies \\text{Set Index} = 8$ bits.\n5. $\\text{Tag bits} = 32 - (\\text{Set Index} + \\text{Block Offset}) = 32 - (8 + 6) = 32 - 14 = 18$ bits.',
    formulaConcept: '$\\text{Tag} = \\text{Address bits} - \\log_2(\\text{Sets}) - \\log_2(\\text{Block Size})$',
    shortcutTrick: '$32 - 8 - 6 = 18$ bits.',
    commonMistake: 'Dividing total cache size by 4 before finding line count.',
    sourceRef: 'GATE CS 2021 Set 1 NAT 53',
  },

  // --- 2020 ---
  {
    subjectCode: 'GATE_CS_ALGO',
    topicKeyword: 'Dynamic',
    year: 2020,
    shift: 'Shift 1',
    questionType: 'NAT',
    difficulty: 'MEDIUM',
    questionText: 'What is the length of the Longest Common Subsequence (LCS) of the two strings $X = \\text{"ABCBDAB"}$ and $Y = \\text{"BDCABA"}$?',
    options: [],
    correctAnswers: { min: 4, max: 4 },
    marks: 2.0,
    negativeMarks: 0.0,
    avgExpectedSeconds: 60,
    explanation: 'Subsequences analysis:\nValid common subsequences include "BCBA", "BDAB", "BCAB".\nAll have length 4.\nNo common subsequence of length 5 exists.\nTherefore, LCS length = 4.',
    formulaConcept: '$L[i,j] = 1 + L[i-1,j-1]$ if $X[i] == Y[j]$, else $\\max(L[i-1,j], L[i,j-1])$',
    shortcutTrick: 'Trace matching characters in order: B-C-B-A or B-D-A-B $\\implies 4$.',
    commonMistake: 'Confusing substring (contiguous) with subsequence (order preserved, not necessarily contiguous).',
    sourceRef: 'GATE CS 2020 Set 1 NAT 41',
  },
  {
    subjectCode: 'GATE_CS_TOC',
    topicKeyword: 'Logic',
    year: 2020,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Which of the following first-order logic formulas is logically equivalent to $\\neg (\\forall x (P(x) \\implies Q(x)))$?',
    options: [
      { id: 'A', text: '$\\exists x (P(x) \\land \\neg Q(x))$' },
      { id: 'B', text: '$\\forall x (P(x) \\land \\neg Q(x))$' },
      { id: 'C', text: '$\\exists x (\\neg P(x) \\lor Q(x))$' },
      { id: 'D', text: '$\\exists x (P(x) \\implies \\neg Q(x))$' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Step-by-step simplification:\n1. $P(x) \\implies Q(x) \\equiv \\neg P(x) \\lor Q(x)$.\n2. $\\neg (\\forall x (\\neg P(x) \\lor Q(x))) \\equiv \\exists x \\neg(\\neg P(x) \\lor Q(x))$.\n3. Applying De Morgan\'s law: $\\exists x (P(x) \\land \\neg Q(x))$.',
    formulaConcept: '$\\neg \\forall x \\,\\phi(x) \\equiv \\exists x \\,\\neg \\phi(x), \\quad \\neg (P \\implies Q) \\equiv P \\land \\neg Q$',
    shortcutTrick: 'Negation of "All P are Q" is "There exists a P which is NOT Q".',
    commonMistake: 'Distributing negation as $\\exists x (\\neg P(x) \\implies \\neg Q(x))$.',
    sourceRef: 'GATE CS 2020 Set 1 Question 14',
  },

  // --- 2019 ---
  {
    subjectCode: 'GATE_CS_DBMS',
    topicKeyword: 'B and B+',
    year: 2019,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In a $B^+$-tree of order $p$ (maximum $p$ child pointers in an internal node), what is the MINIMUM number of keys in any non-root internal node?',
    options: [
      { id: 'A', text: '$\\lceil p/2 \\rceil - 1$' },
      { id: 'B', text: '$\\lfloor p/2 \\rfloor$' },
      { id: 'C', text: '$p - 1$' },
      { id: 'D', text: '$\\lceil p/2 \\rceil$' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'In a $B^+$-tree of order $p$:\n- Maximum child pointers = $p$, max keys = $p - 1$.\n- Minimum child pointers for non-root internal node = $\\lceil p/2 \\rceil$.\n- Since an internal node with $k$ child pointers contains $k - 1$ keys, minimum number of keys = $\\lceil p/2 \\rceil - 1$.',
    formulaConcept: '$\\text{Min keys in internal node} = \\lceil p/2 \\rceil - 1$',
    shortcutTrick: 'Nodes are at least half full: pointers $\\ge \\lceil p/2 \\rceil \\implies$ keys $\\ge \\lceil p/2 \\rceil - 1$.',
    commonMistake: 'Choosing $\\lceil p/2 \\rceil$ (which is the pointer count, not key count).',
    sourceRef: 'GATE CS 2019 Set 1 Question 29',
  },
  {
    subjectCode: 'GATE_CS_ALGO',
    topicKeyword: 'Binary Search',
    year: 2019,
    shift: 'Shift 1',
    questionType: 'NAT',
    difficulty: 'MEDIUM',
    questionText: 'What is the maximum number of nodes in a complete binary tree of depth $h = 5$, where the root is at depth $0$?',
    options: [],
    correctAnswers: { min: 63, max: 63 },
    marks: 1.0,
    negativeMarks: 0.0,
    avgExpectedSeconds: 20,
    explanation: 'A fully saturated complete binary tree of depth $h$ (with root at $h=0$) has $N = 2^{h+1} - 1$ nodes.\nFor $h = 5$: $N = 2^{5+1} - 1 = 2^6 - 1 = 64 - 1 = 63$ nodes.',
    formulaConcept: '$N_{\\max} = \\sum_{i=0}^h 2^i = 2^{h+1} - 1$',
    shortcutTrick: '$2^6 - 1 = 63$.',
    commonMistake: 'Calculating $2^5 - 1 = 31$ when depth starts from 0.',
    sourceRef: 'GATE CS 2019 Set 1 NAT 34',
  },

  // --- 2018 ---
  {
    subjectCode: 'GATE_CS_CN',
    topicKeyword: 'Application',
    year: 2018,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following transport layer protocols and default port numbers are used by DNS (Domain Name System) for standard client name resolution queries?',
    options: [
      { id: 'A', text: 'UDP port 53' },
      { id: 'B', text: 'TCP port 53' },
      { id: 'C', text: 'UDP port 67' },
      { id: 'D', text: 'TCP port 80' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'DNS uses UDP port 53 for standard client lookup queries because UDP has zero connection overhead and fast single request-response. (DNS uses TCP port 53 only for Zone Transfers between primary and secondary DNS servers or responses > 512 bytes).',
    formulaConcept: 'DNS: Port 53 (UDP for queries, TCP for zone transfer). DHCP: Ports 67/68.',
    shortcutTrick: 'Standard DNS lookup = UDP 53.',
    commonMistake: 'Assuming DNS exclusively uses TCP.',
    sourceRef: 'GATE CS 2018 Set 1 Question 12',
  },
  {
    subjectCode: 'GATE_CS_OS',
    topicKeyword: 'Memory Management',
    year: 2018,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In an inverted page table system with 32-bit virtual addresses, 4 KB page size, and 512 MB physical memory, the size of the inverted page table is determined by the number of:',
    options: [
      { id: 'A', text: 'Physical page frames in main memory' },
      { id: 'B', text: 'Virtual pages across all processes' },
      { id: 'C', text: 'Concurrent active processes' },
      { id: 'D', text: 'Entries in the translation lookaside buffer' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'In a traditional page table, there is one entry per virtual page. In an Inverted Page Table, there is exactly one entry per PHYSICAL frame in main memory, indexed by physical frame number. Total entries = $\\text{Physical Memory Size} / \\text{Page Size} = 512\\text{ MB} / 4\\text{ KB} = 128\\text{K}$ entries.',
    formulaConcept: '$\\text{Entries in Inverted Page Table} = \\frac{\\text{Physical Memory Size}}{\\text{Page Frame Size}}$',
    shortcutTrick: 'Inverted page table size depends on PHYSICAL memory, not virtual address space.',
    commonMistake: 'Assuming inverted page tables still scale with virtual address space.',
    sourceRef: 'GATE CS 2018 Set 1 Question 23',
  },
];
