import { RawQuestionData } from './gateQuestions.js';

export const rrbAlp2026Feb17Shift2Questions: RawQuestionData[] = [
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Speed',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A car travels 120 km at 60 km/h, then 200 km at 80 km/h, but experiences a total stoppage time of 20 minutes due to traffic. After that, it covers the final 150 km at 100 km/h. What is the average speed (in km/h, rounded off to one decimal place) of the car for the entire journey including stoppage times?',
    options: [
      { id: 'A', text: '74.2' },
      { id: 'B', text: '75.3' },
      { id: 'C', text: '73.5' },
      { id: 'D', text: '72.4' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '1. Total Distance $= 120 + 200 + 150 = 470\\text{ km}$.\n2. Time for segment 1 $= \\frac{120}{60} = 2\\text{ hrs}$.\n3. Time for segment 2 $= \\frac{200}{80} + \\frac{20}{60} = 2.5 + 0.3333 = 2.8333\\text{ hrs} = \\frac{17}{6}\\text{ hrs}$.\n4. Time for segment 3 $= \\frac{150}{100} = 1.5\\text{ hrs}$.\nTotal Time $= 2 + 2.5 + \\frac{1}{3} + 1.5 = 6 + \\frac{1}{3} = \\frac{19}{3}\\text{ hrs} \\approx 6.333\\text{ hrs}$.\nAverage Speed $= \\frac{470}{19/3} = \\frac{1410}{19} \\approx 74.21\\text{ km/h} \\approx 74.2\\text{ km/h}$.',
    formulaConcept: 'Average Speed with Delays: $v_{\\text{avg}} = \\frac{D_{\\text{total}}}{T_{\\text{running}} + T_{\\text{stoppage}}}$.',
    shortcutTrick: '$1410 / 19 = 74.21\\text{ km/h}$.',
    commonMistake: 'Excluding the 20-minute traffic delay.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q1',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Sound',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Megaphones, loudhailers, horns and musical instruments like trumpets and shehnais are designed to:',
    options: [
      { id: 'A', text: 'Absorb sound waves' },
      { id: 'B', text: 'Send sound in a specific direction' },
      { id: 'C', text: 'Spread sound equally in all directions' },
      { id: 'D', text: 'Reduce the loudness of sound' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Megaphones, horns, and trumpets have conical/flared tubes that guide successive reflections of sound waves forward, directing acoustic energy into a concentrated beam in a specific forward direction without spreading in all directions.',
    formulaConcept: 'Acoustics: Multiple reflection and directional sound channeling.',
    shortcutTrick: 'Horns/Megaphones direct sound in a specific direction.',
    commonMistake: 'Thinking they spread sound equally in all directions.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q2',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Data Sufficiency',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Four bags – Atlas, Bolt, Cargo, and Drift – have different weights. Which bag is heavier: Bolt or Cargo?\n(I) Atlas is heavier than Bolt but lighter than Drift.\n(II) Cargo is lighter than Drift but heavier than Atlas.',
    options: [
      { id: 'A', text: 'Data in Statement II alone is sufficient while Statement I is not' },
      { id: 'B', text: 'Data in both statements I and II together are NOT sufficient' },
      { id: 'C', text: 'Data in both statements I and II together are sufficient to answer the question' },
      { id: 'D', text: 'Data in Statement I alone is sufficient while Statement II is not' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'From (I): Drift > Atlas > Bolt.\nFrom (II): Drift > Cargo > Atlas.\nCombining both: Drift > Cargo > Atlas > Bolt.\nThis definitively proves Cargo > Bolt (Cargo is heavier than Bolt).\nBoth statements I and II together are necessary and sufficient.',
    formulaConcept: 'Inequality chaining in Data Sufficiency.',
    shortcutTrick: 'Cargo > Atlas > Bolt $\\implies$ Cargo is heavier than Bolt.',
    commonMistake: 'Evaluating either statement in isolation.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q3',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Direction',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Paritosh starts from Point A and drives 22 km South. He turns right and drives 12 km, turns right and drives 26 km. He turns right and drives 23 km. He takes a final right turn, drives 4 km and stops at Point P. How far and towards which direction should he drive to reach Point A again?',
    options: [
      { id: 'A', text: '11 km to the east' },
      { id: 'B', text: '10 km to the west' },
      { id: 'C', text: '11 km to the west' },
      { id: 'D', text: '10 km to the east' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: 'Coordinates from $A(0,0)$:\n1. 22 km South $\\to (0, -22)$\n2. Right (West) 12 km $\\to (-12, -22)$\n3. Right (North) 26 km $\\to (-12, 4)$\n4. Right (East) 23 km $\\to (11, 4)$\n5. Right (South) 4 km $\\to (11, 0) = P$.\nTo return to $A(0,0)$ from $P(11, 0)$, Paritosh must drive 11 km West.',
    formulaConcept: 'Coordinate tracking: $x = -12 + 23 = 11$, $y = -22 + 26 - 4 = 0$.',
    shortcutTrick: '$P = (11, 0) \\implies$ Move 11 km West.',
    commonMistake: 'Selecting 11 km to the east.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q4',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of ? in the given series?\n\n91 97 106 118 133 ?',
    options: [
      { id: 'A', text: '150' },
      { id: 'B', text: '152' },
      { id: 'C', text: '151' },
      { id: 'D', text: '153' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Differences increase by $+3$:\n$97 - 91 = +6$\n$106 - 97 = +9$\n$118 - 106 = +12$\n$133 - 118 = +15$\nNext difference $= 15 + 3 = +18$.\nNext number $= 133 + 18 = 151$.',
    formulaConcept: 'Multiples of 3 difference progression: $+6, +9, +12, +15, +18$.',
    shortcutTrick: '$133 + 18 = 151$.',
    commonMistake: 'Adding 15 again ($148$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q5',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Select the set in which the numbers are related in the same way as in the given sets: (8, 168, 7) ; (9, 243, 9).',
    options: [
      { id: 'A', text: '(12, 252, 7)' },
      { id: 'B', text: '(16, 324, 8)' },
      { id: 'C', text: '(15, 330, 8)' },
      { id: 'D', text: '(13, 325, 9)' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Pattern: $a \\times c \\times 3 = b$.\n- $8 \\times 7 \\times 3 = 56 \\times 3 = 168$\n- $9 \\times 9 \\times 3 = 81 \\times 3 = 243$\n- For (12, 252, 7): $12 \\times 7 \\times 3 = 84 \\times 3 = 252$. Exactly matches.',
    formulaConcept: 'Outer product tripling: $b = 3ac$.',
    shortcutTrick: '$12 \\times 7 \\times 3 = 252$.',
    commonMistake: 'Checking difference without factoring in multiple.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q6',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the sequence (left to right):\nF U V G Q R T N E S C T E U S R R S Q Q Y\nHow many such vowels are there, each of which is immediately preceded by a consonant and also immediately followed by a consonant?',
    options: [
      { id: 'A', text: 'One' },
      { id: 'B', text: 'More than three' },
      { id: 'C', text: 'Two' },
      { id: 'D', text: 'None' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Condition: [Consonant][Vowel][Consonant]:\n- F U V $\\implies$ U is preceded by F (Consonant) and followed by V (Consonant) -> 1\n- N E S $\\implies$ E is preceded by N (Consonant) and followed by S (Consonant) -> 2\n- T E U $\\implies$ E is followed by vowel U -> No\n- E U S $\\implies$ U is preceded by vowel E -> No\nTotal = 2 vowels (U in FUV, E in NES).',
    formulaConcept: 'String Pattern Matching [C][V][C].',
    shortcutTrick: 'FUV and NES are the only two valid triplets.',
    commonMistake: 'Counting E or U in TEUS where vowels are adjacent.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q7',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Based on the five three-digit numbers: 567, 254, 395, 486, 671. What will be the resultant if the third digit of the highest number is added to the third digit of the lowest number?',
    options: [
      { id: 'A', text: '4' },
      { id: 'B', text: '3' },
      { id: 'C', text: '5' },
      { id: 'D', text: '2' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: '1. Highest number is 671 $\\implies$ third digit is 1.\n2. Lowest number is 254 $\\implies$ third digit is 4.\nSum $= 1 + 4 = 5$.',
    formulaConcept: 'Digit Extraction & Summation.',
    shortcutTrick: '$1 + 4 = 5$.',
    commonMistake: 'Selecting 567 as lowest or taking second digits.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q8',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of the question mark (?) in the given series based on the English alphabetical order?\n\nMCZ RHE WMJ BRO ?',
    options: [
      { id: 'A', text: 'GTW' },
      { id: 'B', text: 'GRD' },
      { id: 'C', text: 'GWT' },
      { id: 'D', text: 'GER' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Each letter advances by $+5$ modulo 26:\n- 1st: $M(13) \\xrightarrow{+5} R(18) \\xrightarrow{+5} W(23) \\xrightarrow{+5} B(28/2) \\xrightarrow{+5} G(7)$\n- 2nd: $C(3) \\xrightarrow{+5} H(8) \\xrightarrow{+5} M(13) \\xrightarrow{+5} R(18) \\xrightarrow{+5} W(23)$\n- 3rd: $Z(26) \\xrightarrow{+5} E(5) \\xrightarrow{+5} J(10) \\xrightarrow{+5} O(15) \\xrightarrow{+5} T(20)$.\nResult is GWT.',
    formulaConcept: 'Uniform $+5$ Positional Shift.',
    shortcutTrick: '$B+5=G, R+5=W, O+5=T \\implies \\text{GWT}$.',
    commonMistake: 'Selecting GTW by swapping last two letters.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q9',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Ratio',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If $m : f = 16 : 3$, then what is the value of $\\frac{3m - 16f}{3m + 16f}$?',
    options: [
      { id: 'A', text: '0' },
      { id: 'B', text: '233 / 249' },
      { id: 'C', text: '253 / 247' },
      { id: 'D', text: '253 / 249' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Substitute $m = 16k$ and $f = 3k$:\nNumerator $= 3(16k) - 16(3k) = 48k - 48k = 0$.\nDenominator $= 3(16k) + 16(3k) = 48k + 48k = 96k$.\nValue $= \\frac{0}{96k} = 0$.',
    formulaConcept: 'Direct ratio evaluation.',
    shortcutTrick: '$3(16) - 16(3) = 0 \\implies 0$.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q10',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Geometry',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The length of a side of a square is equal to the diameter of a circle. If the area of the square is $196\\text{ cm}^2$, then find the area of the circle (in $\\text{cm}^2$). [Use $\\pi = 22/7$]',
    options: [
      { id: 'A', text: '154' },
      { id: 'B', text: '148' },
      { id: 'C', text: '616' },
      { id: 'D', text: '145' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '1. Side of square $s = \\sqrt{196} = 14\\text{ cm}$.\n2. Diameter of circle $d = 14\\text{ cm} \\implies$ radius $r = \\frac{14}{2} = 7\\text{ cm}$.\n3. Area of circle $= \\pi r^2 = \\frac{22}{7} \\times 7^2 = 22 \\times 7 = 154\\text{ cm}^2$.',
    formulaConcept: 'Geometric Area Relations: $A_{\\text{square}} = s^2$, $A_{\\text{circle}} = \\pi r^2$.',
    shortcutTrick: '$r = 7 \\implies \\text{Area} = 154\\text{ cm}^2$.',
    commonMistake: 'Using radius $= 14\\text{ cm}$ (which gives 616).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q11',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'D, E, F, G, I, J and K are sitting around a circular table facing the centre. E sits to the immediate left of I. F sits to the immediate left of D. D sits second to the left of K. G sits third to the left of I. Who sits third to the right of J?',
    options: [
      { id: 'A', text: 'G' },
      { id: 'B', text: 'K' },
      { id: 'C', text: 'D' },
      { id: 'D', text: 'F' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: '7 positions clockwise 1 to 7:\n1. Let I = 1 $\\implies$ E (immediate left, clockwise 1) is at 2.\n2. G is 3rd left of I $\\implies$ G is at 4.\n3. D is 2nd left of K, and F is immediate left of D $\\implies$ slots for (K, D, F) must be (7, 5, 6).\n4. Remaining slot for J is 3.\nOrder (1-7): I, E, J, G, D, F, K.\nThird to the right of J (counter-clockwise 3 from 3) is G at position 4 (or pos 4 from 3 is G).',
    formulaConcept: 'Circular Arrangement for 7 members.',
    shortcutTrick: 'Clockwise sequence: I-E-J-G-D-F-K $\\implies 3$rd right of J is G.',
    commonMistake: 'Reversing left and right.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q12',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the sequence (left to right):\n# P & T £ @ G $ G V M & X M @ # & L L @ K Y\nHow many such letters are there, each of which is immediately preceded by a symbol and also immediately followed by a symbol?',
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '4' },
      { id: 'C', text: '5' },
      { id: 'D', text: '2' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Condition: [Symbol][Letter][Symbol]\n1. # P & $\\implies$ P is preceded by # and followed by & -> 1\n2. £ @ G $ -> Wait, @ G $ $\\implies$ G is preceded by @ and followed by $ -> 2\n3. & X M -> M is followed by @ -> & X M has X followed by M (Letter, not symbol)\n4. @ K Y -> Y has nothing after\n5. & L L @ -> L followed by L (Letter)\n6. @ G $ (2), and # P & (1), and check & X M @ # (M is preceded by X)\nTotal matches = 3 letters (P, T in & T £, G in @ G $).\nTotal = 3.',
    formulaConcept: 'String scanning for [Symbol][Letter][Symbol].',
    shortcutTrick: '#P&, &T£, @G$ = 3.',
    commonMistake: 'Counting G in $ G V where V is a letter.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q13',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A shopkeeper sells an item for ₹430.5 after giving two successive discounts of 70% and 75% on its marked price. Had he not given any discount, he would have earned a profit of 40%. What is the cost price (in ₹) of the item?',
    options: [
      { id: 'A', text: '4,121' },
      { id: 'B', text: '4,145' },
      { id: 'C', text: '4,100' },
      { id: 'D', text: '4,081' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. $SP = MP \\times (1 - 0.70) \\times (1 - 0.75) = MP \\times 0.30 \\times 0.25 = 0.075 MP = 430.5$.\n2. $MP = \\frac{430.5}{0.075} = 5740$.\n3. Zero discount gives 40% profit on CP $\\implies CP = \\frac{MP}{1.40} = \\frac{5740}{1.40} = ₹4,100$.',
    formulaConcept: 'Multi-discount Back-calculation: $CP = \\frac{SP}{(1-d_1)(1-d_2)(1+P)}$.',
    shortcutTrick: '$MP = 430.5 / 0.075 = 5740 \\implies CP = 5740 / 1.4 = 4100$.',
    commonMistake: 'Multiplying 430.5 by 1.40.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q14',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Select the pair which follows the same pattern as:\nNLGT : SPJV\nDQCL : IUFN',
    options: [
      { id: 'A', text: 'JPZS : OTCU' },
      { id: 'B', text: 'WXYZ : BBBC' },
      { id: 'C', text: 'KNMS : PRPV' },
      { id: 'D', text: 'RMEF : WRHH' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check shift pattern: $[+5, +4, +3, +2]$:\n- NLGT $\\to$ SPJV: $N(14)+5=S(19), L(12)+4=P(16), G(7)+3=J(10), T(20)+2=V(22)$\n- DQCL $\\to$ IUFN: $D(4)+5=I(9), Q(17)+4=U(21), C(3)+3=F(6), L(12)+2=N(14)$\nTesting JPZS $\\to$ OTCU:\n- $J(10)+5=O(15)$\n- $P(16)+4=T(20)$\n- $Z(26)+3=C(29/3)$\n- $S(19)+2=U(21)$. Matches.',
    formulaConcept: 'Decreasing Shift Sequence: $[+5, +4, +3, +2]$.',
    shortcutTrick: '$J+5=O, P+4=T, Z+3=C, S+2=U \\implies \\text{OTCU}$.',
    commonMistake: 'Applying constant shift across all letters.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q15',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Each vowel in the word JOURNAL is changed to the letter immediately following it and each consonant is changed to the letter immediately preceding it in the English alphabetical order. How many vowels are there in the new group of letters thus formed?',
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '0' },
      { id: 'C', text: '3' },
      { id: 'D', text: '2' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Transforming JOURNAL:\n- J (consonant) $\\to$ I (VOWEL)\n- O (vowel) $\\to$ P (consonant)\n- U (vowel) $\\to$ V (consonant)\n- R (consonant) $\\to$ Q (consonant)\n- N (consonant) $\\to$ M (consonant)\n- A (vowel) $\\to$ B (consonant)\n- L (consonant) $\\to$ K (consonant)\nNew group: I, P, V, Q, M, B, K.\nNumber of vowels in new group is exactly 1 (\'I\').',
    formulaConcept: 'Consonant/Vowel Transformation & Vowel Counting.',
    shortcutTrick: 'Only J becomes I (vowel). All vowels become consonants $\\implies$ exactly 1 vowel.',
    commonMistake: 'Assuming vowels remain vowels.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q16',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A product\'s price after successive discounts of 20% and 10% is ₹7,200. What was the original price of the product before any discounts were applied?',
    options: [
      { id: 'A', text: '₹9,000' },
      { id: 'B', text: '₹12,000' },
      { id: 'C', text: '₹10,000' },
      { id: 'D', text: '₹11,000' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '$\\text{Original} \\times (1 - 0.20) \\times (1 - 0.10) = \\text{Original} \\times 0.80 \\times 0.90 = 0.72 \\times \\text{Original} = 7200$.\n$\\text{Original Price} = \\frac{7200}{0.72} = ₹10,000$.',
    formulaConcept: 'Successive Discount: $SP = MP(1 - d_1)(1 - d_2)$.',
    shortcutTrick: '$7200 / 0.72 = ₹10,000$.',
    commonMistake: 'Adding 30% to 7200 ($₹9,360$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q17',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Statistics',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the mode of the following data?\n77, 85, 87, 75, 78, 62, 68, 61, 90, 63, 61, 71, 69, 77, 75, 82, 75, 69, 74, 75, 70, 81, 65, 66, 61',
    options: [
      { id: 'A', text: '75' },
      { id: 'B', text: '77' },
      { id: 'C', text: '61' },
      { id: 'D', text: '69' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Frequencies:\n- 75: occurs 4 times\n- 61: occurs 3 times\n- 77: occurs 2 times\n- 69: occurs 2 times\n75 has the highest frequency (4). Hence mode is 75.',
    formulaConcept: 'Mode is the value that appears most frequently.',
    shortcutTrick: '75 appears 4 times.',
    commonMistake: 'Selecting 61 which appears only 3 times.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q18',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Optics',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The distance between the pole and the principal focus of a spherical mirror is called:',
    options: [
      { id: 'A', text: 'Focal length' },
      { id: 'B', text: 'Magnification' },
      { id: 'C', text: 'Radius of curvature' },
      { id: 'D', text: 'Aperture' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 10,
    explanation: 'By optical definition, the distance from the vertex/pole (P) of a spherical mirror to its principal focus (F) is its focal length ($f = R/2$).',
    formulaConcept: 'Optics Terminology: Focal length $f = \\frac{R}{2}$.',
    shortcutTrick: 'Pole to Focus = Focal Length.',
    commonMistake: 'Confusing focal length with radius of curvature (Pole to Center of Curvature).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q19',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Percentage',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: '4% of a number is what percentage of 20% of the same number?',
    options: [
      { id: 'A', text: '500%' },
      { id: 'B', text: '16.67%' },
      { id: 'C', text: '8.33%' },
      { id: 'D', text: '20%' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Let the number be $N$.\n$\\text{Percentage} = \\frac{4\\% \\text{ of } N}{20\\% \\text{ of } N} \\times 100 = \\frac{0.04N}{0.20N} \\times 100 = \\frac{4}{20} \\times 100 = 20\\%$.',
    formulaConcept: 'Relative Percentage Ratio: $\\frac{A}{B} \\times 100$.',
    shortcutTrick: '$\\frac{4}{20} \\times 100 = 20\\%$.',
    commonMistake: 'Calculating $\\frac{20}{4} \\times 100 = 500\\%$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q20',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In the number-pairs: X : 98 :: 196 : Y. Which numbers should replace X and Y so that the pattern is identical on both sides?',
    options: [
      { id: 'A', text: 'X = 116, Y = 178' },
      { id: 'B', text: 'X = 104, Y = 185' },
      { id: 'C', text: 'X = 47, Y = 101' },
      { id: 'D', text: 'X = 98, Y = 96' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Pattern: Constant subtraction of 18 ($\\text{First Number} - 18 = \\text{Second Number}$):\n- For left side: $X - 18 = 98 \\implies X = 98 + 18 = 116$.\n- For right side: $196 - 18 = 178 = Y$.\nHence $X = 116, Y = 178$.',
    formulaConcept: 'Arithmetic Difference Analogy: $y = x - 18$.',
    shortcutTrick: '$116 - 18 = 98$ and $196 - 18 = 178$.',
    commonMistake: 'Applying halving relation without matching integers.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q21',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Direction',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Vinay starts from Point A towards the south for 7 m. He turns left and walks 8 m, turns left and walks 4 m, turns left and walks 2 m. He turns right and walks 3 m. At last, he turns left and walks 2 m and stops at Point B. Towards which direction should he walk in order to reach Point A again?',
    options: [
      { id: 'A', text: 'North' },
      { id: 'B', text: 'South' },
      { id: 'C', text: 'East' },
      { id: 'D', text: 'West' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: 'Coordinates from $A(0,0)$:\n1. 7 m South $\\to (0, -7)$\n2. Left (East) 8 m $\\to (8, -7)$\n3. Left (North) 4 m $\\to (8, -3)$\n4. Left (West) 2 m $\\to (6, -3)$\n5. Right (North) 3 m $\\to (6, 0)$\n6. Left (West) 2 m $\\to (4, 0) = B$.\nSince Point B is at $(4, 0)$, to reach $A(0,0)$ Vinay must walk directly West.',
    formulaConcept: '2D Path Summation: $x = 8 - 2 - 2 = 4$, $y = -7 + 4 + 3 = 0$.',
    shortcutTrick: '$B = (4, 0) \\implies$ Walk West to reach $(0,0)$.',
    commonMistake: 'Selecting East.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q22',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of the question mark (?) in the given series based on English alphabetical order?\n\nZHW UCR PXM KSH ?',
    options: [
      { id: 'A', text: 'FCD' },
      { id: 'B', text: 'FNC' },
      { id: 'C', text: 'FCN' },
      { id: 'D', text: 'FDR' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'All letter positions decrease by $-5$ (or advance by $-5$ mod 26):\n1st: $Z(26) \\xrightarrow{-5} U(21) \\xrightarrow{-5} P(16) \\xrightarrow{-5} K(11) \\xrightarrow{-5} F(6)$\n2nd: $H(8) \\xrightarrow{-5} C(3) \\xrightarrow{-5} X(24) \\xrightarrow{-5} S(19) \\xrightarrow{-5} N(14)$\n3rd: $W(23) \\xrightarrow{-5} R(18) \\xrightarrow{-5} M(13) \\xrightarrow{-5} H(8) \\xrightarrow{-5} C(3)$.\nResult is FNC.',
    formulaConcept: 'Uniform $-5$ Modulo 26 Sequence.',
    shortcutTrick: '$K-5=F, S-5=N, H-5=C \\implies \\text{FNC}$.',
    commonMistake: 'Selecting FCN by swapping the last two letters.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q23',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Classification',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Based on the English alphabetical order, three of the following four letter-clusters are alike in a certain way and form a group. Which pair DOES NOT belong to that group?\n\n1. JI-LK\n2. BA-DC\n3. GH-PQ\n4. XW-ZY',
    options: [
      { id: 'A', text: 'JI-LK' },
      { id: 'B', text: 'BA-DC' },
      { id: 'C', text: 'GH-PQ' },
      { id: 'D', text: 'XW-ZY' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Pattern in clusters:\n- JI-LK: $J(-1)I, L(-1)K$ (both reverse consecutive $-1$)\n- BA-DC: $B(-1)A, D(-1)C$ (both reverse consecutive $-1$)\n- XW-ZY: $X(-1)W, Z(-1)Y$ (both reverse consecutive $-1$)\n- GH-PQ: $G(+1)H, P(+1)Q$ (forward consecutive $+1$).\nGH-PQ has forward direction instead of reverse direction.',
    formulaConcept: 'Intra-pair letter step parity.',
    shortcutTrick: 'All others step backward $-1$; GH-PQ steps forward $+1$.',
    commonMistake: 'Overlooking the reverse order in JI, BA, XW.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q24',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Five students, P, Q, R, S, and T, have different heights. P is taller than Q but shorter than R. S is not the shortest. Only one student is shorter than T. Who among them is the shortest?',
    options: [
      { id: 'A', text: 'P' },
      { id: 'B', text: 'R' },
      { id: 'C', text: 'Q' },
      { id: 'D', text: 'S' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '1. $R > P > Q$.\n2. "Only one student is shorter than T" $\\implies$ T is the 4th tallest (2nd shortest).\n3. Since $R > P > Q$, Q must be the 5th (shortest) person, with T in 4th place and S in top 3.\nOrder: $R > P > S > T > Q$ (or $S > R > P > T > Q$).\nShortest student is Q.',
    formulaConcept: 'Positional Ranking Deduction.',
    shortcutTrick: 'T is 4th, only one below T, and Q < P < R $\\implies$ Q is 5th (shortest).',
    commonMistake: 'Assuming S must be shortest.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q25',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Each of A, B, C, D, E, F and G play a game on a different day (Mon to Sun). B plays on Wednesday. Only three persons play between B and F. Only one person plays between C and F. A plays immediately before D. G does not play immediately after B. On which day does A play the game?',
    options: [
      { id: 'A', text: 'Tuesday' },
      { id: 'B', text: 'Sunday' },
      { id: 'C', text: 'Friday' },
      { id: 'D', text: 'Monday' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. B = Wednesday (Day 3).\n2. Three persons between B and F $\\implies$ F = Sunday (Day 7).\n3. One person between C and F (Sun) $\\implies$ C = Friday (Day 5).\n4. A plays immediately before D (pair A-D) $\\implies$ Pair A-D must occupy Mon-Tue (Days 1 & 2).\n5. Remaining days: Thursday (Day 4) and Saturday (Day 6). Since G $\\ne$ Thursday (not immediately after B) $\\implies$ E = Thursday, G = Saturday.\nSchedule: Mon-A, Tue-D, Wed-B, Thu-E, Fri-C, Sat-G, Sun-F.\nA plays on Monday.',
    formulaConcept: 'Weekly Scheduling Grid.',
    shortcutTrick: 'Pair A-D must be Mon-Tue $\\implies$ A = Monday.',
    commonMistake: 'Placing F on Monday.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q26',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Mathematical',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What will come in place of the question mark (?) in the following equation, if \'+\' and \'÷\' are interchanged and \'-\' and \'x\' are interchanged?\n\n312 + 6 x 8 - 21 ÷ 169 = ?',
    options: [
      { id: 'A', text: '51' },
      { id: 'B', text: '59' },
      { id: 'C', text: '55' },
      { id: 'D', text: '53' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '$312 \\div 6 - 8 \\times 21 + 169$\n1. Division: $312 \\div 6 = 52$\n2. Multiplication: $8 \\times 21 = 168$\n3. Expression: $52 - 168 + 169 = 52 + 1 = 53$.',
    formulaConcept: 'BODMAS Rule with interchanged signs.',
    shortcutTrick: '$52 + (169 - 168) = 52 + 1 = 53$.',
    commonMistake: 'Subtracting 168 from 52 incorrectly.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q27',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Blood',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'In a code language: \'A # B\' = daughter, \'A @ B\' = brother, \'A + B\' = wife, \'A - B\' = father. How is D related to R if ‘D # M - S + P @ R’?',
    options: [
      { id: 'A', text: 'Brother\'s daughter' },
      { id: 'B', text: 'Brother\'s wife\'s mother' },
      { id: 'C', text: 'Brother\'s wife\'s sister' },
      { id: 'D', text: 'Brother\'s wife' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '- $P @ R \\implies P$ is brother of $R$.\n- $S + P \\implies S$ is wife of $P$ (Brother\'s wife).\n- $M - S \\implies M$ is father of $S$.\n- $D \\# M \\implies D$ is daughter of $M$ (sister of $S$).\nSince $S$ is brother\'s wife, and $D$ is sister of $S$, $D$ is brother\'s wife\'s sister of $R$.',
    formulaConcept: 'Coded Family Tree Decoding.',
    shortcutTrick: '$P$ is brother, $S$ is brother\'s wife, $D$ is sister of $S \\implies$ Brother\'s wife\'s sister.',
    commonMistake: 'Confusing with brother\'s daughter.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q28',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Data Sufficiency',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Four people – Amit, Bhavesh, Chandan, and Dhiraj – are of different ages. Who is the oldest?\n(I) Bhavesh is older than Amit but younger than Dhiraj.\n(II) Chandan is younger than Dhiraj but older than Amit.',
    options: [
      { id: 'A', text: 'Data in both statements I and II together are sufficient to answer the question' },
      { id: 'B', text: 'Data in Statement I alone is sufficient while Statement II is not' },
      { id: 'C', text: 'Data in Statement II alone is sufficient while Statement I is not' },
      { id: 'D', text: 'Data in both statements I and II together are NOT sufficient' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'From (I): Dhiraj > Bhavesh > Amit (Dhiraj is older than Bhavesh and Amit, but Chandan is unknown).\nFrom (II): Dhiraj > Chandan > Amit (Dhiraj is older than Chandan and Amit, but Bhavesh is unknown).\nCombining (I) and (II): Dhiraj is older than all three others (Bhavesh, Chandan, Amit).\nHence, Dhiraj is uniquely identified as the oldest using both statements together.',
    formulaConcept: 'Data Sufficiency: Upper bound containment.',
    shortcutTrick: 'Both statements show Dhiraj is older than all other 3 individuals.',
    commonMistake: 'Assuming either statement alone establishes maximum.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q29',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Algebra',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'If $a^2 + b^2 + c^2 + 189 = 6(a + 4b + 2c)$, then $\\sqrt{ab + bc + ca}$ is equal to:',
    options: [
      { id: 'A', text: '2√14' },
      { id: 'B', text: '2√11' },
      { id: 'C', text: '3√11' },
      { id: 'D', text: '3√14' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: 'Rearrange into sum of perfect squares:\n$(a^2 - 6a + 9) + (b^2 - 24b + 144) + (c^2 - 12c + 36) = 0$\nNotice: $9 + 144 + 36 = 189$.\n$(a - 3)^2 + (b - 12)^2 + (c - 6)^2 = 0$.\nSince squares of real numbers cannot be negative:\n$a = 3, b = 12, c = 6$.\nNow: $ab + bc + ca = (3 \\times 12) + (12 \\times 6) + (6 \\times 3) = 36 + 72 + 18 = 126$.\n$\\sqrt{126} = \\sqrt{9 \\times 14} = 3\\sqrt{14}$.',
    formulaConcept: 'Completing the Square Method in Multi-variable quadratics.',
    shortcutTrick: '$a=3, b=12, c=6 \\implies \\sqrt{36 + 72 + 18} = \\sqrt{126} = 3\\sqrt{14}$.',
    commonMistake: 'Calculation error with $\\sqrt{126}$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q30',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Geometry',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'It is given that $\\Delta ABC \\sim \\Delta EDF$ such that $AB = 5\\text{ cm}$, $AC = 7.5\\text{ cm}$, $DF = 15\\text{ cm}$ and $ED = 12.5\\text{ cm}$. The sum of the remaining sides ($BC + EF$) of the triangles is:',
    options: [
      { id: 'A', text: '24.75 cm' },
      { id: 'B', text: '22.25 cm' },
      { id: 'C', text: '20.25 cm' },
      { id: 'D', text: '23.25 cm' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: 'Since $\\Delta ABC \\sim \\Delta EDF$, the ratio of corresponding sides is equal:\n$\\frac{AB}{ED} = \\frac{BC}{DF} = \\frac{AC}{EF}$.\n$\\frac{5}{12.5} = \\frac{1}{2.5} = 0.4$.\n1. $\\frac{BC}{15} = \\frac{1}{2.5} \\implies BC = \\frac{15}{2.5} = 6\\text{ cm}$.\n2. $\\frac{7.5}{EF} = \\frac{1}{2.5} \\implies EF = 7.5 \\times 2.5 = 18.75\\text{ cm}$.\nSum of remaining sides $= BC + EF = 6 + 18.75 = 24.75\\text{ cm}$.',
    formulaConcept: 'Similar Triangles Proportion: $\\frac{AB}{ED} = \\frac{BC}{DF} = \\frac{AC}{EF}$.',
    shortcutTrick: '$BC = 15/2.5 = 6$; $EF = 7.5 \\times 2.5 = 18.75 \\implies 6 + 18.75 = 24.75$.',
    commonMistake: 'Matching side $AC$ with $DF$ instead of $EF$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q31',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Anand purchased an item and spent ₹63 on its repair. He then sold it to Bharath at a profit of 25%. Later, Bharath sold the item for ₹8,415, incurring a loss of 15%. What was Anand’s cost (in ₹) of the item just before selling it to Bharath?',
    options: [
      { id: 'A', text: '7917' },
      { id: 'B', text: '7918' },
      { id: 'C', text: '7920' },
      { id: 'D', text: '7919' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '1. Bharath sold for ₹8,415 at 15% loss:\n$\\text{Bharath\'s CP} = \\frac{8415}{1 - 0.15} = \\frac{8415}{0.85} = ₹9,900$.\n2. Anand sold to Bharath at 25% profit:\n$\\text{Anand\'s Total Cost} = \\frac{9900}{1.25} = ₹7,920$.',
    formulaConcept: 'Multi-step Transaction Profit/Loss Formula.',
    shortcutTrick: '$8415 / 0.85 = 9900 \\implies 9900 / 1.25 = 7920$.',
    commonMistake: 'Subtracting ₹63 when question asks for cost just before selling.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q32',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Blood',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In a code language: \'A # B\' = daughter, \'A % B\' = father, \'A − B\' = son, \'A @ B\' = sister. How is S related to U if ‘S @ M − H # Y % U’?',
    options: [
      { id: 'A', text: 'Sister\'s daughter' },
      { id: 'B', text: 'Brother\'s daughter' },
      { id: 'C', text: 'Daughter' },
      { id: 'D', text: 'Sister' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: '- $Y \\% U \\implies Y$ is father of $U$.\n- $H \\# Y \\implies H$ is daughter of $Y$ (sister of $U$).\n- $M - H \\implies M$ is son of $H$.\n- $S @ M \\implies S$ is sister of $M$ (daughter of $H$).\nSince $H$ is sister of $U$, and $S$ is daughter of $H$, $S$ is U\'s sister\'s daughter (niece).',
    formulaConcept: 'Coded Family Tree Decoding.',
    shortcutTrick: '$S$ is daughter of $H$ (sister of $U$) $\\implies$ Sister\'s daughter.',
    commonMistake: 'Selecting Brother\'s daughter.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q33',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Partnership',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Bharat, Jyoti, and Vishal invest ₹70,000, ₹32,000, and ₹46,000, respectively, to start a business. At the end of the year, the total profit earned is ₹52,540. 60% of the profit is given to charity and the rest is divided among them in the ratio of their investments. What will be the share of Vishal (in ₹)?',
    options: [
      { id: 'A', text: '6,380' },
      { id: 'B', text: '6,532' },
      { id: 'C', text: '6,520' },
      { id: 'D', text: '6,453' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: '1. Divisible profit after 60% charity $= 52540 \\times (1 - 0.60) = 52540 \\times 0.40 = ₹21,016$.\n2. Investment Ratio: $70 : 32 : 46 = 35 : 16 : 23$.\n3. Total Ratio units $= 35 + 16 + 23 = 74$.\n4. Vishal\'s share $= \\frac{23}{74} \\times 21016 = 23 \\times 284 = ₹6,532$.',
    formulaConcept: 'Partnership with Charity Deduction.',
    shortcutTrick: '$21016 / 74 = 284 \\implies 284 \\times 23 = ₹6,532$.',
    commonMistake: 'Dividing total ₹52,540 directly without deducting 60% charity.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q34',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Mathematical',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What will come in the place of ‘?’ in the following equation, if ‘+’ and ‘-’ are interchanged and ‘×’ and ‘÷’ are interchanged?\n\n5 × 39 ÷ 39 + 39 - 5 = ?',
    options: [
      { id: 'A', text: '-29' },
      { id: 'B', text: '-27' },
      { id: 'C', text: '-31' },
      { id: 'D', text: '-30' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '$5 \\div 39 \\times 39 - 39 + 5 = 5 - 39 + 5 = -34 + 5 = -29$.',
    formulaConcept: 'BODMAS Evaluation.',
    shortcutTrick: '$5 - 39 + 5 = -29$.',
    commonMistake: 'Sign confusion in $-39 + 5$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q35',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Simplification',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If the cost price of 12 identical books is ₹960 and the cost price of 8 identical pens is ₹320, find the total cost price (in ₹) of 15 books and 10 pens of the same kind.',
    options: [
      { id: 'A', text: '1800' },
      { id: 'B', text: '1600' },
      { id: 'C', text: '1200' },
      { id: 'D', text: '1500' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '1. Cost per book $= \\frac{960}{12} = ₹80$.\n2. Cost per pen $= \\frac{320}{8} = ₹40$.\n3. Total cost $= (15 \\times 80) + (10 \\times 40) = 1200 + 400 = ₹1,600$.',
    formulaConcept: 'Unitary Method.',
    shortcutTrick: '$15(80) + 10(40) = 1200 + 400 = 1600$.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q36',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Syllogism',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Read the given statement(s) and conclusions carefully:\n\nStatements:\nSome buttons are mangoes.\nSome pigs are mangoes.\n\nConclusions:\n(I) Some buttons are pigs.\n(II) All mangoes are buttons.',
    options: [
      { id: 'A', text: 'Both conclusions (I) and (II) follow.' },
      { id: 'B', text: 'Neither conclusion (I) nor (II) follows.' },
      { id: 'C', text: 'Only conclusion (I) follows.' },
      { id: 'D', text: 'Only conclusion (II) follows.' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Two "Some" statements with an undistributed middle term (mangoes) provide no definite linkage between buttons and pigs. Conclusion (II) is invalid because "Some buttons are mangoes" does not imply "All mangoes are buttons". Neither conclusion follows.',
    formulaConcept: 'Syllogism Rules on Undistributed Middle.',
    shortcutTrick: 'Some + Some $\\implies$ Neither follows.',
    commonMistake: 'Assuming buttons and pigs overlap.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q37',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Statistics',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'The mean of a data is four times its mode. If the median of the data is 63, find its mean.',
    options: [
      { id: 'A', text: '63' },
      { id: 'B', text: '72' },
      { id: 'C', text: '93' },
      { id: 'D', text: '84' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Using the empirical relationship: $\\text{Mode} = 3\\text{ Median} - 2\\text{ Mean}$.\nGiven $\\text{Mean} = 4 \\times \\text{Mode} \\implies \\text{Mode} = \\frac{\\text{Mean}}{4}$.\n$\\frac{\\text{Mean}}{4} = 3(63) - 2\\text{ Mean} = 189 - 2\\text{ Mean}$.\n$\\frac{\\text{Mean}}{4} + 2\\text{ Mean} = 189 \\implies \\frac{9\\text{ Mean}}{4} = 189$.\n$\\text{Mean} = \\frac{189 \\times 4}{9} = 21 \\times 4 = 84$.',
    formulaConcept: 'Empirical Relationship: $\\text{Mode} = 3\\text{Median} - 2\\text{Mean}$.',
    shortcutTrick: '$9M/4 = 189 \\implies M = 21 \\times 4 = 84$.',
    commonMistake: 'Inverting the formula as $\\text{Mean} = 3\\text{Median} - 2\\text{Mode}$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q38',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Statistics',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A student\'s marks were incorrectly entered as 44 instead of 92. Due to this, the average marks of the class got decreased by 4/3. What is the number of students in the class?',
    options: [
      { id: 'A', text: '43' },
      { id: 'B', text: '32' },
      { id: 'C', text: '36' },
      { id: 'D', text: '41' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Total deficit $= 92 - 44 = 48$.\n$\\frac{48}{n} = \\frac{4}{3} \\implies n = \\frac{48 \\times 3}{4} = 12 \\times 3 = 36$.',
    formulaConcept: 'Average Correction Formula: $n = \\frac{\\Delta \\text{Total}}{\\Delta \\bar{x}}$.',
    shortcutTrick: '$n = 48 \\times \\frac{3}{4} = 36$.',
    commonMistake: 'Calculation error with 48/4.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q39',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Biology',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following biological processes is responsible for the transportation of soluble products of photosynthesis (sucrose) to different parts of a plant?',
    options: [
      { id: 'A', text: 'Transpiration' },
      { id: 'B', text: 'Assimilation' },
      { id: 'C', text: 'Termination' },
      { id: 'D', text: 'Translocation' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Translocation is the process of transporting soluble photosynthetic products (sucrose, amino acids) through the phloem sieve tubes from source (leaves) to sink tissues (roots, fruits, buds) using ATP energy.',
    formulaConcept: 'Plant Transport Mechanisms: Xylem (Water/minerals via Transpiration pull) vs Phloem (Nutrients via Translocation).',
    shortcutTrick: 'Transport of food/sugar in plants = Translocation.',
    commonMistake: 'Confusing transpiration (water loss) with translocation (food transport).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q40',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'NQMI is related to TWSO in a certain way based on English alphabetical order. In the same way, DHKF is related to JNQL. To which of the following is LOPS related, following the same logic?',
    options: [
      { id: 'A', text: 'QUUX' },
      { id: 'B', text: 'RUVY' },
      { id: 'C', text: 'RVUY' },
      { id: 'D', text: 'QVVX' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Constant shift of $+6$ across all letters:\n- NQMI $\\to$ TWSO: $N(14)+6=T(20), Q(17)+6=W(23), M(13)+6=S(19), I(9)+6=O(15)$\n- DHKF $\\to$ JNQL: $D(4)+6=J(10), H(8)+6=N(14), K(11)+6=Q(17), F(6)+6=L(12)$\nApplying $+6$ to LOPS:\n- $L(12) + 6 = R(18)$\n- $O(15) + 6 = U(21)$\n- $P(16) + 6 = V(22)$\n- $S(19) + 6 = Y(25)$\nResult is RUVY.',
    formulaConcept: 'Uniform $+6$ Positional Shift.',
    shortcutTrick: '$L+6=R, O+6=U, P+6=V, S+6=Y \\implies \\text{RUVY}$.',
    commonMistake: 'Selecting RVUY by swapping middle letters.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q41',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Pipes',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Three pipes of diameters 2 cm, 3 cm and 4 cm are running together to fill a cistern. The smallest pipe alone can fill the cistern in 232 minutes. The rate of water flow in each pipe is proportional to the square of its diameter. The time (in minutes) taken by all pipes running together to completely fill the cistern is:',
    options: [
      { id: 'A', text: '40' },
      { id: 'B', text: '42' },
      { id: 'C', text: '32' },
      { id: 'D', text: '36' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: '1. Flow rates are proportional to $d^2$:\n- Pipe 1 ($d=2\\text{ cm}$): Flow $r_1 = 2^2 = 4$\n- Pipe 2 ($d=3\\text{ cm}$): Flow $r_2 = 3^2 = 9$\n- Pipe 3 ($d=4\\text{ cm}$): Flow $r_3 = 4^2 = 16$\n2. Total combined flow rate $R = 4 + 9 + 16 = 29$.\n3. Smallest pipe (rate 4) fills the cistern in 232 minutes $\\implies \\text{Total Capacity} = 4 \\times 232 = 928\\text{ units}$.\n4. Time taken by all pipes together $= \\frac{928}{29} = 32\\text{ minutes}$.',
    formulaConcept: 'Flow Rate Proportional to Cross-sectional Area ($Q \\propto d^2$).',
    shortcutTrick: '$T = 232 \\times \\frac{4}{29} = 8 \\times 4 = 32\\text{ minutes}$.',
    commonMistake: 'Taking flow proportional to diameter ($d$) instead of $d^2$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q42',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a certain code language, ‘book is published’ is coded as ‘cw ku qr’ and ‘book was interesting’ is coded as ‘ot qr zx’. How is ‘book’ coded in the given language?',
    options: [
      { id: 'A', text: 'ot' },
      { id: 'B', text: 'qr' },
      { id: 'C', text: 'cw' },
      { id: 'D', text: 'ku' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Common word between both sentences is \'book\'.\nCommon code token between \'cw ku qr\' and \'ot qr zx\' is \'qr\'.\nTherefore, \'book\' is coded as \'qr\'.',
    formulaConcept: 'Sentence-based cipher word mapping.',
    shortcutTrick: 'Common word = book, Common code = qr.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q43',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Ratio',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'The cost of 7 kg of sugar of quality A is ₹245, and the cost of 5 kg of sugar of quality B is ₹300. In what ratio should quality A sugar and quality B sugar be mixed so that the cost of 1 kg of the mixture is ₹50?',
    options: [
      { id: 'A', text: '3 : 4' },
      { id: 'B', text: '2 : 3' },
      { id: 'C', text: '3 : 2' },
      { id: 'D', text: '4 : 3' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '1. Rate of Quality A $= \\frac{245}{7} = ₹35/\\text{kg}$.\n2. Rate of Quality B $= \\frac{300}{5} = ₹60/\\text{kg}$.\n3. Mean price $= ₹50/\\text{kg}$.\nUsing the Rule of Alligation:\n$\\frac{\\text{Quantity of A}}{\\text{Quantity of B}} = \\frac{60 - 50}{50 - 35} = \\frac{10}{15} = \\frac{2}{3} = 2 : 3$.',
    formulaConcept: 'Rule of Alligation: $\\frac{Q_A}{Q_B} = \\frac{C_B - C_M}{C_M - C_A}$.',
    shortcutTrick: '$(60 - 50) : (50 - 35) = 10 : 15 = 2 : 3$.',
    commonMistake: 'Inverting the ratio to $3 : 2$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q44',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the sequence (left to right):\nK Ω T & R $ S @ B * L % N # P £ D Ω G $ M\nHow many such letters are there, each of which is immediately preceded by a symbol and also immediately followed by another symbol?',
    options: [
      { id: 'A', text: 'One' },
      { id: 'B', text: 'Three' },
      { id: 'C', text: 'More than three' },
      { id: 'D', text: 'Two' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check for [Symbol][Letter][Symbol]:\n1. Ω T & -> T is preceded by Ω and followed by & -> 1\n2. & R $ -> R is preceded by & and followed by $ -> 2\n3. $ S @ -> S is preceded by $ and followed by @ -> 3\n4. @ B * -> B is preceded by @ and followed by * -> 4\n5. * L % -> L is preceded by * and followed by % -> 5\n6. % N # -> N is preceded by % and followed by # -> 6\n7. # P £ -> P is preceded by # and followed by £ -> 7\n8. £ D Ω -> D is preceded by £ and followed by Ω -> 8\n9. Ω G $ -> G is preceded by Ω and followed by $ -> 9\nSince there are 9 such instances, the answer is "More than three".',
    formulaConcept: 'Pattern Matching in character strings.',
    shortcutTrick: 'Count exceeds 3 easily $\\implies$ More than three.',
    commonMistake: 'Stopping after counting 3.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q45',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of the question mark (?) in the given series?\n\n25 29 34 40 47 55 ?',
    options: [
      { id: 'A', text: '62' },
      { id: 'B', text: '68' },
      { id: 'C', text: '66' },
      { id: 'D', text: '64' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Sequential increment pattern (+4, +5, +6, +7, +8, +9):\n$25 + 4 = 29$\n$29 + 5 = 34$\n$34 + 6 = 40$\n$40 + 7 = 47$\n$47 + 8 = 55$\n$55 + 9 = 64$.',
    formulaConcept: 'Series with consecutive integer differences.',
    shortcutTrick: '$55 + 9 = 64$.',
    commonMistake: 'Adding 8 again ($63$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q46',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Speed',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A person drove at 59 kmph for 3.5 hours, then increased his speed by 9 kmph, and reached the destination in another hour. Find the average speed (in kmph) of the person during the entire journey.',
    options: [
      { id: 'A', text: '61' },
      { id: 'B', text: '57' },
      { id: 'C', text: '59' },
      { id: 'D', text: '66' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1. Distance for segment 1 $= 59 \\times 3.5 = 206.5\\text{ km}$.\n2. New speed $= 59 + 9 = 68\\text{ km/h}$. Distance for segment 2 $= 68 \\times 1 = 68\\text{ km}$.\n3. Total Distance $= 206.5 + 68 = 274.5\\text{ km}$.\n4. Total Time $= 3.5 + 1 = 4.5\\text{ hours}$.\nAverage Speed $= \\frac{274.5}{4.5} = 61\\text{ kmph}$.',
    formulaConcept: 'Average Speed $= \\frac{\\text{Total Distance}}{\\text{Total Time}}$.',
    shortcutTrick: '$\\frac{274.5}{4.5} = \\frac{549}{9} = 61\\text{ km/h}$.',
    commonMistake: 'Using speed 9 kmph instead of $59 + 9 = 68\\text{ kmph}$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q47',
  },
  {
    subjectCode: 'RRB_ALP_GA',
    topicKeyword: 'Polity',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Oaths and affirmations for various constitutional posts (Ministers, Judges, MPs) are provided in which Schedule of the Indian Constitution?',
    options: [
      { id: 'A', text: 'Eleventh Schedule' },
      { id: 'B', text: 'First Schedule' },
      { id: 'C', text: 'Third Schedule' },
      { id: 'D', text: 'Ninth Schedule' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The Third Schedule of the Indian Constitution contains the forms of oaths or affirmations for Union Ministers, MPs, Supreme Court & High Court Judges, and CAG.',
    formulaConcept: 'Indian Constitution Schedules: 1st (States/UTs), 2nd (Salaries/Emoluments), 3rd (Oaths/Affirmations), 4th (Rajya Sabha seats).',
    shortcutTrick: '3rd Schedule = Oaths & Affirmations.',
    commonMistake: 'Confusing 2nd Schedule (Salaries) with 3rd Schedule (Oaths).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q48',
  },
  {
    subjectCode: 'RRB_ALP_GA',
    topicKeyword: 'Current Affairs',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In 2025, which Indian state unveiled plans to establish the country’s first Quantum Computing Village (at Amaravati)?',
    options: [
      { id: 'A', text: 'Tamil Nadu' },
      { id: 'B', text: 'Kerala' },
      { id: 'C', text: 'Andhra Pradesh' },
      { id: 'D', text: 'Haryana' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The Government of Andhra Pradesh announced the development of India\'s first Quantum Computing Village in Amaravati to foster deep-tech research, quantum algorithms, and commercial quantum applications.',
    formulaConcept: 'Science & Technology Current Affairs: State Quantum Initiatives.',
    shortcutTrick: 'First Quantum Village = Andhra Pradesh (Amaravati).',
    commonMistake: 'Selecting Kerala or Tamil Nadu.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q49',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In a code language, \'SAND\' is coded as WDRG and \'BIRD\' is coded as FLVG. How will \'FOUR\' be coded in the same language?',
    options: [
      { id: 'A', text: 'JSXV' },
      { id: 'B', text: 'JRYU' },
      { id: 'C', text: 'IRYW' },
      { id: 'D', text: 'ISXV' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Check letter shift pattern: $[+4, +3, +4, +3]$:\n- SAND $\\to$ WDRG: $S(19)+4=W(23), A(1)+3=D(4), N(14)+4=R(18), D(4)+3=G(7)$\n- BIRD $\\to$ FLVG: $B(2)+4=F(6), I(9)+3=L(12), R(18)+4=V(22), D(4)+3=G(7)$\nApplying to FOUR:\n- $F(6) + 4 = J(10)$\n- $O(15) + 3 = R(18)$\n- $U(21) + 4 = Y(25)$\n- $R(18) + 3 = U(21)$\nResult is JRYU.',
    formulaConcept: 'Alternating Shift Cipher: $[+4, +3, +4, +3]$.',
    shortcutTrick: '$F+4=J, O+3=R, U+4=Y, R+3=U \\implies \\text{JRYU}$.',
    commonMistake: 'Applying $+4$ uniformly to all letters ($JSXV$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q50',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Seven people, A, B, C, D, E, F and G, are sitting in a row facing north. No one sits to the right of E. Only three people sit between E and D. Only two people sit between D and A. F sits third to the left of B. G sits to the immediate right of B. How many people sit between B and E?',
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '2' },
      { id: 'C', text: '1' },
      { id: 'D', text: '4' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: 'Slots 1 to 7 from West to East (facing North):\n1. No one right of E $\\implies$ E is at Slot 7.\n2. Three people between E and D $\\implies$ D is at Slot 3.\n3. Two people between D (3) and A $\\implies$ A is at Slot 6 or 0 (impossible), so A is at Slot 6.\n4. G is immediate right of B (pair B-G). F is 3rd left of B $\\implies$ F is at Slot 1, B is at Slot 4, G is at Slot 5.\n5. Remaining Slot 2 is occupied by C.\nRow layout: 1-F, 2-C, 3-D, 4-B, 5-G, 6-A, 7-E.\nBetween B (Slot 4) and E (Slot 7), there are 2 people (G and A on slots 5 and 6).',
    formulaConcept: 'Linear Arrangement with Positional Anchors.',
    shortcutTrick: 'B=4, E=7 $\\implies 7 - 4 - 1 = 2$ people.',
    commonMistake: 'Counting B and E.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q51',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Based on the English alphabetical order, three of the following four letter-cluster pairs are alike in a certain way and form a group. Which pair DOES NOT belong to that group?\n\n1. PN - QO\n2. RP - BJ\n3. MK - NL\n4. FD - GE',
    options: [
      { id: 'A', text: 'PN - QO' },
      { id: 'B', text: 'RP - BJ' },
      { id: 'C', text: 'MK - NL' },
      { id: 'D', text: 'FD - GE' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Pattern:\n- PN - QO: $P(16) \\xrightarrow{-2} N(14)$, $Q(17) \\xrightarrow{-2} O(15)$, with $P \\xrightarrow{+1} Q$\n- MK - NL: $M(13) \\xrightarrow{-2} K(11)$, $N(14) \\xrightarrow{-2} L(12)$, with $M \\xrightarrow{+1} N$\n- FD - GE: $F(6) \\xrightarrow{-2} D(4)$, $G(7) \\xrightarrow{-2} E(5)$, with $F \\xrightarrow{+1} G$\nIn all three, each cluster has $-2$ internal step and $+1$ cross shift.\n- RP - BJ: $R(-2)P$, but $B(2) \\xrightarrow{-8} J(10)$ (violates $-2$ rule).\nHence RP - BJ is the odd one out.',
    formulaConcept: 'Alphabetical step pattern parity.',
    shortcutTrick: 'BJ has $+8$ difference, whereas all others have $-2$ internal step.',
    commonMistake: 'Overlooking the jump in BJ.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q52',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Each letter in the word SHOCKED is changed to the letter immediately preceding it in alphabetical order, and then all letters obtained are arranged in alphabetical order (A to Z). Which letter will be second from the right in the new group?',
    options: [
      { id: 'A', text: 'D' },
      { id: 'B', text: 'N' },
      { id: 'C', text: 'G' },
      { id: 'D', text: 'J' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1. Shift $-1$: S$\\to$R, H$\\to$G, O$\\to$N, C$\\to$B, K$\\to$J, E$\\to$D, D$\\to$C.\nLetters: R, G, N, B, J, D, C.\n2. Arrange in alphabetical order (A to Z):\nB, C, D, G, J, N, R.\n3. Second letter from the right is \'N\'.',
    formulaConcept: 'Two-stage String Transformation: shift + alphabetical sort.',
    shortcutTrick: 'Alphabetical order: B, C, D, G, J, N, R $\\implies$ 2nd from right is N.',
    commonMistake: 'Reading second from left instead of second from right.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q53',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Number System',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a division sum, the divisor is 2 times the quotient and 4 times the remainder. If the remainder is 22, what is the dividend?',
    options: [
      { id: 'A', text: '3894' },
      { id: 'B', text: '3892' },
      { id: 'C', text: '3899' },
      { id: 'D', text: '3889' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '1. Remainder $R = 22$.\n2. Divisor $D = 4 \\times R = 4 \\times 22 = 88$.\n3. Quotient $Q = \\frac{D}{2} = \\frac{88}{2} = 44$.\n4. $\\text{Dividend} = (\\text{Divisor} \\times \\text{Quotient}) + \\text{Remainder} = (88 \\times 44) + 22 = 3872 + 22 = 3894$.',
    formulaConcept: 'Division Algorithm: $\\text{Dividend} = \\text{Divisor} \\times \\text{Quotient} + \\text{Remainder}$.',
    shortcutTrick: '$88 \\times 44 + 22 = 3872 + 22 = 3894$.',
    commonMistake: 'Multiplying quotient by remainder.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q54',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Percentage',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The price of an article was ₹1600. It increased by 10% in the first year and by 20% in the second year. What is the price (in ₹) of the article after two years?',
    options: [
      { id: 'A', text: '2000' },
      { id: 'B', text: '2144' },
      { id: 'C', text: '1840' },
      { id: 'D', text: '2112' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '$\\text{Price} = 1600 \\times 1.10 \\times 1.20 = 1600 \\times 1.32 = ₹2,112$.',
    formulaConcept: 'Successive Percentage Compounding.',
    shortcutTrick: '$1600 \\times 1.32 = 2112$.',
    commonMistake: 'Calculating 30% simple addition ($1600 \\times 1.30 = 2080$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q55',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Each of Gauri, Hina, Isha, Jack, Kunti, Lali and Mahima has an exam on a different day (Mon to Sun). Gauri has an exam on Monday. Only three persons have exams between Gauri and Kunti. Hina has exam immediately after Jack and immediately before Isha. Lali does not have an exam on the last day. On which day does Lali have the exam?',
    options: [
      { id: 'A', text: 'Sunday' },
      { id: 'B', text: 'Wednesday' },
      { id: 'C', text: 'Saturday' },
      { id: 'D', text: 'Tuesday' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. Gauri = Monday (Day 1).\n2. Three persons between Gauri and Kunti $\\implies$ Kunti = Friday (Day 5).\n3. Triplet block: Jack, Hina, Isha (in consecutive order Jack $\\to$ Hina $\\to$ Isha).\nAvailable 3 consecutive slots: Tue, Wed, Thu (Days 2, 3, 4).\nSo Jack = Tuesday, Hina = Wednesday, Isha = Thursday.\n4. Remaining slots: Saturday (Day 6) and Sunday (Day 7). Since Lali $\\ne$ Sunday $\\implies$ Lali = Saturday, Mahima = Sunday.\nLali\'s exam is on Saturday.',
    formulaConcept: 'Sequential Block Insertion in Day Schedule.',
    shortcutTrick: 'Mon-Gauri, Tue-Jack, Wed-Hina, Thu-Isha, Fri-Kunti, Sat-Lali, Sun-Mahima $\\implies$ Saturday.',
    commonMistake: 'Placing Jack-Hina-Isha on Fri-Sat-Sun.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q56',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Geometry',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In the geometric figure with parallel lines AB || CD || EF: Angle ABO = 35° and Angle CDO = 64°. Find the measure of angle x.',
    options: [
      { id: 'A', text: '105°' },
      { id: 'B', text: '145°' },
      { id: 'C', text: '209°' },
      { id: 'D', text: '151°' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Draw a parallel line through the vertex O parallel to AB and CD.\n1. Upper angle at O $= 35^\\circ$ (alternate interior angle to $\\angle ABO$).\n2. Lower angle at O $= 180^\\circ - 64^\\circ = 116^\\circ$ (co-interior angle to $\\angle CDO$).\n3. Total angle $x = 35^\\circ + 116^\\circ = 151^\\circ$.',
    formulaConcept: 'Parallel Lines & Alternate/Co-interior Angle Theorems.',
    shortcutTrick: '$x = 35^\\circ + (180^\\circ - 64^\\circ) = 35^\\circ + 116^\\circ = 151^\\circ$.',
    commonMistake: 'Directly adding $35^\\circ + 64^\\circ = 99^\\circ$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q57',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Pipes',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A cistern can be filled by a tap in 5 hours and emptied by an outlet pipe in 9 hours. How long will it take to fill the cistern if both the tap and the pipe are opened together?',
    options: [
      { id: 'A', text: '11 hours 25 minutes' },
      { id: 'B', text: '11 hours 15 minutes' },
      { id: 'C', text: '12 hours 15 minutes' },
      { id: 'D', text: '12 hours 25 minutes' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Net filling rate $= \\frac{1}{5} - \\frac{1}{9} = \\frac{9 - 5}{45} = \\frac{4}{45}\\text{ cistern/hr}$.\nTime required $= \\frac{45}{4} = 11.25\\text{ hours} = 11\\text{ hours } (0.25 \\times 60)\\text{ minutes} = 11\\text{ hours } 15\\text{ minutes}$.',
    formulaConcept: 'Net Pipe Work Rate: $\\frac{1}{T} = \\frac{1}{\\text{Inlet}} - \\frac{1}{\\text{Outlet}}$.',
    shortcutTrick: '$\\frac{45}{4} = 11\\frac{1}{4}\\text{ hrs} = 11\\text{ hr } 15\\text{ min}$.',
    commonMistake: 'Adding the rates instead of subtracting.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q58',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Sound',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'For an echo to be heard clearly, the reflecting surface should be at least how far from the listener? (Take speed of sound $\\approx 340\\text{ m/s}$ and persistence of hearing $= 0.1\\text{ s}$)',
    options: [
      { id: 'A', text: '50 m' },
      { id: 'B', text: '17 m' },
      { id: 'C', text: '100 m' },
      { id: 'D', text: '34 m' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Persistence of human hearing is $0.1\\text{ s}$. Total round-trip distance $= v \\times t = 340 \\times 0.1 = 34\\text{ m}$.\nMinimum obstacle distance $d = \\frac{34}{2} = 17\\text{ m}$ (or 17.2 m at 20°C).',
    formulaConcept: 'Echo Acoustics Formula: $d = \\frac{v \\cdot t}{2}$.',
    shortcutTrick: '$\\frac{340 \\times 0.1}{2} = 17\\text{ m}$.',
    commonMistake: 'Forgetting the round-trip factor of 2 and answering 34 m.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q59',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'During a sale, 50% of the goods are sold at 40% profit, 30% of the remaining goods are sold at 46% profit and the still remaining goods are sold at a loss of 24%. If there is an overall profit of x%, then what is the value of x?',
    options: [
      { id: 'A', text: '18.5' },
      { id: 'B', text: '17.5' },
      { id: 'C', text: '19' },
      { id: 'D', text: '20' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: 'Let total goods $= 100$.\n1. First part: $50$ goods at $+40\\% \\implies 50 \\times 0.40 = +20$.\n2. Remaining $= 50$. Second part: $30\\% \\text{ of } 50 = 15$ goods at $+46\\% \\implies 15 \\times 0.46 = +6.9$.\n3. Third part: $50 - 15 = 35$ goods at $-24\\% \\implies 35 \\times (-0.24) = -8.4$.\nNet overall profit percentage $= 20 + 6.9 - 8.4 = 18.5\\%$.',
    formulaConcept: 'Weighted Average Profit/Loss.',
    shortcutTrick: '$20 + 6.9 - 8.4 = 18.5\\%$.',
    commonMistake: 'Taking 30% of total goods instead of remaining.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q60',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Mensuration',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A solid metal sphere is melted and smaller spheres of equal radii are formed. 5% of the volume of the sphere is lost during the process. The smaller sphere has a radius that is one-tenth of the large sphere. If 14 liters of paint was needed to paint the larger sphere, how many liters is needed to paint all the smaller spheres?',
    options: [
      { id: 'A', text: '154 liters' },
      { id: 'B', text: '102 liters' },
      { id: 'C', text: '133 liters' },
      { id: 'D', text: '44 liters' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. Let original sphere volume $= V$, radius $= R$. Available volume after 5% loss $= 0.95 V$.\n2. Radius of small sphere $r = \\frac{R}{10} \\implies$ volume of each small sphere $v = \\frac{V}{1000}$.\n3. Number of small spheres formed $n = \\frac{0.95 V}{V/1000} = 950$ spheres.\n4. Surface area of large sphere $A = 4\\pi R^2$.\n5. Surface area of one small sphere $a = 4\\pi \\left(\\frac{R}{10}\\right)^2 = \\frac{A}{100}$.\n6. Total surface area of 950 small spheres $= 950 \\times \\frac{A}{100} = 9.5 A$.\n7. Paint required $= 9.5 \\times 14\\text{ liters} = 133\\text{ liters}$.',
    formulaConcept: 'Volume Conservation and Surface Area Scaling: $n = 0.95 \\times 10^3 = 950$; $A_{\\text{total}} = 950 \\times 10^{-2} A_0 = 9.5 A_0$.',
    shortcutTrick: '$9.5 \\times 14 = 133$ liters.',
    commonMistake: 'Assuming surface area remains constant after melting.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q61',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Seven boxes, M, N, O, P, Q, R and S, are kept one over the other (positions 1 to 7 from bottom to top). P is kept third from the bottom (Position 3). Only one box is kept between P and M but M is not in the lowermost position. Only three boxes are kept between M and R. O is kept immediately below Q. Only one box is kept between O and N. Which box is second from the top (Position 6)?',
    options: [
      { id: 'A', text: 'O' },
      { id: 'B', text: 'N' },
      { id: 'C', text: 'Q' },
      { id: 'D', text: 'R' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: 'Stack positions 1 (bottom) to 7 (top):\n1. P is at Pos 3.\n2. One box between P and M and M $\\ne$ 1 $\\implies$ M is at Pos 5.\n3. Three boxes between M (5) and R $\\implies$ R is at Pos 1 (5 - 3 - 1 = 1).\n4. O is immediately below Q (pair Q-O) $\\implies$ Available adjacent positions are (7, 6).\nSo Q is at Pos 7, O is at Pos 6.\n5. One box between O (6) and N $\\implies$ N is at Pos 4.\n6. Remaining box S is at Pos 2.\nStack layout (top to bottom): 7-Q, 6-O, 5-M, 4-N, 3-P, 2-S, 1-R.\nSecond box from the top (Pos 6) is O.',
    formulaConcept: 'Vertical Box Stacking Puzzle.',
    shortcutTrick: 'Pos 7 = Q, Pos 6 = O $\\implies$ Second from top is O.',
    commonMistake: 'Placing M at position 1.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q62',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Mathematical',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If ‘P’ stands for ‘×’, ‘Q’ stands for ‘÷’, ‘R’ stands for ‘−’ and ‘S’ stands for ‘+’, then what will come in place of ? in:\n\n70 Q 2 R 5 P 3 S 18 = ?',
    options: [
      { id: 'A', text: '48' },
      { id: 'B', text: '38' },
      { id: 'C', text: '21' },
      { id: 'D', text: '54' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '$70 \\div 2 - 5 \\times 3 + 18 = 35 - 15 + 18 = 20 + 18 = 38$.',
    formulaConcept: 'BODMAS Evaluation.',
    shortcutTrick: '$35 - 15 + 18 = 38$.',
    commonMistake: 'Subtracting 18 instead of adding.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q63',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Physics',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If the energy of an electron in the second orbit ($n=2$) of hydrogen is −3.4 eV, what is its energy in the fourth orbit ($n=4$)?',
    options: [
      { id: 'A', text: '−1.7 eV' },
      { id: 'B', text: '−6.8 eV' },
      { id: 'C', text: '−13.6 eV' },
      { id: 'D', text: '−0.85 eV' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Bohr\'s formula for hydrogen energy levels: $E_n = \\frac{-13.6}{n^2}\\text{ eV}$.\nFor $n = 4$:\n$E_4 = \\frac{-13.6}{4^2} = \\frac{-13.6}{16} = -0.85\\text{ eV}$.\n(Alternatively: $E_4 = E_2 \\times \\frac{2^2}{4^2} = -3.4 \\times \\frac{4}{16} = \\frac{-3.4}{4} = -0.85\\text{ eV}$).',
    formulaConcept: 'Bohr\'s Hydrogen Atom Energy Levels: $E_n = \\frac{E_1}{n^2}$.',
    shortcutTrick: '$E_4 = \\frac{E_2}{4} = \\frac{-3.4}{4} = -0.85\\text{ eV}$.',
    commonMistake: 'Halving the energy instead of dividing by $2^2 = 4$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q64',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'PL 2 is related to LO 15 and NJ 5 is related to JM 18. To which of the given options is NP 3 related, following the same logic?',
    options: [
      { id: 'A', text: 'IT 14' },
      { id: 'B', text: 'JT 14' },
      { id: 'C', text: 'JS 16' },
      { id: 'D', text: 'IS 16' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Pattern:\n- 1st letter: $-4$ ($P(16)-4=L(12); N(14)-4=J(10); N(14)-4=J(10)$)\n- 2nd letter: $+3$ ($L(12)+3=O(15); J(10)+3=M(13); P(16)+3=S(19)$)\n- Number: $+13$ ($2+13=15; 5+13=18; 3+13=16$).\nResult is JS 16.',
    formulaConcept: 'Positional Shift & Number Addition: $[-4, +3, +13]$.',
    shortcutTrick: '$N-4=J, P+3=S, 3+13=16 \\implies \\text{JS 16}$.',
    commonMistake: 'Selecting IS 16 with $N-5=I$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q65',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Biology',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The microscopic cilia present in the respiratory tract epithelium primarily help in:',
    options: [
      { id: 'A', text: 'Absorbing oxygen' },
      { id: 'B', text: 'Gas exchange' },
      { id: 'C', text: 'Pumping blood to lungs' },
      { id: 'D', text: 'Removing harmful particles from inhaled air' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The coordinated rhythmic wave-like motion of cilia in the respiratory tract forms the mucociliary escalator, sweeping trapped airborne particulates, dust, and pathogens upward out of the lungs toward the pharynx.',
    formulaConcept: 'Mucociliary Clearance Mechanism in Respiratory Defense.',
    shortcutTrick: 'Cilia sweep dust/mucus out of airways.',
    commonMistake: 'Confusing with gas exchange (which occurs in alveoli).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q66',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Heat',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Why do we feel cool after applying water or evaporating sweat on our skin during summer?',
    options: [
      { id: 'A', text: 'Evaporation of water absorbs latent heat from the skin surface' },
      { id: 'B', text: 'Water reduces sweat formation and retains body heat' },
      { id: 'C', text: 'Water increases body temperature by absorbing sunlight' },
      { id: 'D', text: 'Condensation of water releases energy on the skin surface' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Evaporation is a cooling process: as water molecules transition from liquid to vapor, they absorb their latent heat of vaporization directly from the skin surface, lowering the skin temperature.',
    formulaConcept: 'Latent Heat of Vaporization & Evaporative Cooling.',
    shortcutTrick: 'Evaporation absorbs latent heat -> cooling effect.',
    commonMistake: 'Confusing evaporation with condensation.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q67',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Syllogism',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Read the given statements and conclusions carefully:\n\nStatements:\nNo rugs are lamps.\nNo doors are rugs.\n\nConclusions:\n(I) No doors are lamps.\n(II) Some lamps are doors.',
    options: [
      { id: 'A', text: 'Only conclusion (II) follows.' },
      { id: 'B', text: 'Only conclusion (I) follows.' },
      { id: 'C', text: 'Both conclusions (I) and (II) follow.' },
      { id: 'D', text: 'Neither conclusion (I) nor (II) follows.' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'From two negative premises ("No A is B" and "No C is A"), no valid categorical deduction can be drawn between B (lamps) and C (doors). Therefore, neither conclusion (I) nor (II) definitely follows.',
    formulaConcept: 'Syllogism Rule: Two negative premises yield no valid definite conclusion.',
    shortcutTrick: 'No + No $\\implies$ No definite conclusion.',
    commonMistake: 'Assuming negative transitivity between doors and lamps.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q68',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Interest',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Atul distributed ₹24,700 between his two grandsons, 12-year-old Baban and 13-year-old Rakesh, such that both get equal amounts when they reach 23 years of age at 8% compound interest per annum. How much (in ₹) did Atul deposit in the name of Rakesh?',
    options: [
      { id: 'A', text: '12825' },
      { id: 'B', text: '11625' },
      { id: 'C', text: '13175' },
      { id: 'D', text: '11875' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. Baban has $23 - 12 = 11$ years until age 23.\n2. Rakesh has $23 - 13 = 10$ years until age 23.\n3. $B \\times (1.08)^{11} = R \\times (1.08)^{10} \\implies 1.08 B = R \\implies \\frac{R}{B} = \\frac{108}{100} = \\frac{27}{25}$.\n4. Sum of ratio units $= 27 + 25 = 52$.\n5. Rakesh\'s share $= \\frac{27}{52} \\times 24700 = 27 \\times 475 = ₹12,825$.',
    formulaConcept: 'Compound Interest Equal Maturity Division: $\\frac{P_1}{P_2} = (1 + r)^{t_2 - t_1}$.',
    shortcutTrick: 'Ratio $= 27 : 25 \\implies 24700 / 52 = 475 \\implies 27 \\times 475 = ₹12,825$.',
    commonMistake: 'Giving the larger amount to younger boy Baban.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q69',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Interest',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What sum (in ₹) will earn an interest of ₹480 in 2 years at 12% simple interest per year?',
    options: [
      { id: 'A', text: '2200' },
      { id: 'B', text: '1800' },
      { id: 'C', text: '2000' },
      { id: 'D', text: '2150' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: '$P = \\frac{SI \\times 100}{R \\times T} = \\frac{480 \\times 100}{12 \\times 2} = \\frac{48000}{24} = ₹2,000$.',
    formulaConcept: 'Simple Interest Formula: $P = \\frac{SI \\times 100}{RT}$.',
    shortcutTrick: '$480 / 24\\% = 2000$.',
    commonMistake: 'Dividing 480 by 12 without accounting for 2 years.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q70',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In the following number-pairs, the second number is obtained by applying a mathematical operation to the first number: 112 - 100 ; 34 - 22. Select the set following the same rule.',
    options: [
      { id: 'A', text: '55 - 42' },
      { id: 'B', text: '15 - 3' },
      { id: 'C', text: '23 - 12' },
      { id: 'D', text: '43 - 23' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Pattern: Constant difference of 12 ($\\text{First} - 12 = \\text{Second}$):\n- $112 - 12 = 100$\n- $34 - 12 = 22$\n- For 15 - 3: $15 - 12 = 3$.',
    formulaConcept: 'Constant Difference Relation: $x - y = 12$.',
    shortcutTrick: '$15 - 3 = 12$.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q71',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Biology',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'On the basis of function, the plasma membrane (cell membrane) is ________ in nature.',
    options: [
      { id: 'A', text: 'semi-permeable' },
      { id: 'B', text: 'selectively permeable' },
      { id: 'C', text: 'fully permeable' },
      { id: 'D', text: 'fully non-permeable' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 10,
    explanation: 'The plasma membrane is selectively permeable because it strictly regulates the passage of substances, permitting specific molecules (like water and nutrients) while blocking unwanted solutes.',
    formulaConcept: 'Cell Membrane Transport & Selective Permeability.',
    shortcutTrick: 'Plasma membrane = Selectively permeable.',
    commonMistake: 'Selecting fully permeable (which is the cell wall).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q72',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A, B, D, U, P and K live on six different floors (1 to 6). U lives on an odd-numbered floor but not the lowermost floor. Only one person lives between U and P. D does not live on the lowermost floor. K lives immediately above D. B lives immediately above U. A lives immediately below U. Who lives on Floor 2?',
    options: [
      { id: 'A', text: 'A' },
      { id: 'B', text: 'P' },
      { id: 'C', text: 'U' },
      { id: 'D', text: 'B' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. U is on an odd floor not 1 $\\implies$ U is on Floor 3 or 5.\n2. B is immediately above U, and A is immediately below U $\\implies$ Block [B on U+1, U, A on U-1].\nIf U = 3 $\\implies$ B is on Floor 4, A is on Floor 2.\n3. One person between U (3) and P $\\implies$ P is on Floor 5 or 1.\n4. K is immediately above D (pair K-D). Since D $\\ne$ 1, K must be on Floor 6, D on Floor 5, and P on Floor 1.\nFloor layout: 6-K, 5-D, 4-B, 3-U, 2-A, 1-P.\nFloor 2 is occupied by A.',
    formulaConcept: 'Floor Puzzle Block Positioning.',
    shortcutTrick: 'Block B(4)-U(3)-A(2) $\\implies$ Floor 2 is A.',
    commonMistake: 'Placing U on floor 5.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q73',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Classification',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Based on the English alphabetical order, three of the following four letter-clusters are alike in a certain way and form a group. Which letter-cluster DOES NOT belong to that group?\n\n1. CVR\n2. OID\n3. GAV\n4. JDY',
    options: [
      { id: 'A', text: 'CVR' },
      { id: 'B', text: 'OID' },
      { id: 'C', text: 'GAV' },
      { id: 'D', text: 'JDY' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check letter gap differences in each triplet:\n- OID: $O(15) \\xrightarrow{-6} I(9) \\xrightarrow{-5} D(4)$\n- GAV: $G(33/7) \\xrightarrow{-6} A(27/1) \\xrightarrow{-5} V(22)$\n- JDY: $J(36/10) \\xrightarrow{-6} D(30/4) \\xrightarrow{-5} Y(25)$\nAll three follow a $[-6, -5]$ backward sequence.\n- CVR: $C(29) \\xrightarrow{-7} V(22) \\xrightarrow{-4} R(18)$ (violates $[-6, -5]$).\nHence CVR is the odd one out.',
    formulaConcept: 'Intra-cluster letter difference pattern: $[-6, -5]$.',
    shortcutTrick: '$C \\to V$ is $-7$, unlike $-6$ in all others.',
    commonMistake: 'Counting vowels.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q74',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 2',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Each letter in the word BANNER is changed to the letter immediately preceding it in alphabetical order, and then all letters obtained are arranged in reverse alphabetical order (Z to A). Which letter will be third from the right in the new group?',
    options: [
      { id: 'A', text: 'C' },
      { id: 'B', text: 'M' },
      { id: 'C', text: 'B' },
      { id: 'D', text: 'L' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1. Shift $-1$: B$\\to$A, A$\\to$Z, N$\\to$M, N$\\to$M, E$\\to$D, R$\\to$Q.\nLetters: A, Z, M, M, D, Q.\n2. Arrange in reverse alphabetical order (highest to lowest):\nZ, Q, M, M, D, A.\n3. Third letter from the right (1st: A, 2nd: D, 3rd: M) is \'M\'.',
    formulaConcept: 'Shift and Descending Sort string operation.',
    shortcutTrick: 'Reverse sort: Z, Q, M, M, D, A $\\implies$ 3rd from right is M.',
    commonMistake: 'Counting from left instead of right.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 2 Q75',
  },
];
