import { RawQuestionData } from './gateQuestions.js';

export const rrbAlp2026Feb17Shift1Questions: RawQuestionData[] = [
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Percentage',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the overall percentage increase in a number if it is increased successively by 10%, 20%, and 15%?',
    options: [
      { id: 'A', text: '45.8%' },
      { id: 'B', text: '51.8%' },
      { id: 'C', text: '41.8%' },
      { id: 'D', text: '55.8%' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Effective Multiplier $= 1.10 \\times 1.20 \\times 1.15 = 1.32 \\times 1.15 = 1.518$.\nOverall percentage increase $= (1.518 - 1) \\times 100 = 51.8\\%$.',
    formulaConcept: 'Successive Percentage Increase: $(1 + r_1)(1 + r_2)(1 + r_3) - 1$.',
    shortcutTrick: '$10 + 20 + \\frac{10\\times 20}{100} = 32\\%$; $32 + 15 + \\frac{32\\times 15}{100} = 47 + 4.8 = 51.8\\%$.',
    commonMistake: 'Simply adding percentages ($10+20+15=45\\%$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q1',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'What should come in place of the question mark (?) in the given series based on English alphabetical order?\n\nCLW WFQ QZK KTE ?',
    options: [
      { id: 'A', text: 'RDF' },
      { id: 'B', text: 'ENY' },
      { id: 'C', text: 'ENT' },
      { id: 'D', text: 'ECD' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1st letter ($-6$): $C(29) \\to W(23) \\to Q(17) \\to K(11) \\to E(5)$.\n2nd letter ($-6$): $L(38) \\to F(32) \\to Z(26) \\to T(20) \\to N(14)$.\n3rd letter ($-6$): $W(23) \\to Q(17) \\to K(11) \\to E(5) \\to Y(25)$.\nHence the missing cluster is ENY.',
    formulaConcept: 'Uniform $-6$ Alphabetic Shift on all three character positions.',
    shortcutTrick: 'All positions subtract 6: $K(11)-6=E$, $T(20)-6=N$, $E(5)-6=Y \\implies \\text{ENY}$.',
    commonMistake: 'Miscalculating cyclic wrap from E backwards to Y.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q2',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In the following number-pairs, the second number is obtained by applying certain mathematical operations to the first number: 3 - 28 ; 9 - 730. Select the set following the same rule.',
    options: [
      { id: 'A', text: '7 - 342' },
      { id: 'B', text: '1 - 2' },
      { id: 'C', text: '5 - 124' },
      { id: 'D', text: '8 - 645' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Pattern: $n \\to n^3 + 1$.\n- $3^3 + 1 = 27 + 1 = 28$\n- $9^3 + 1 = 729 + 1 = 730$\n- For $n=1$: $1^3 + 1 = 2 \\implies (1 - 2)$.',
    formulaConcept: 'Cubic relation: $f(n) = n^3 + 1$.',
    shortcutTrick: '$1^3 + 1 = 2$.',
    commonMistake: 'Selecting 7 - 342 which is $7^3 - 1 = 342$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q3',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Direction',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Mohit starts from Point A and drives 24 km east. He turns right and drives 23 km, turns right and drives 26 km. He turns right and drives 27 km. He takes a final right turn, drives 2 km and stops at Point P. How far and towards which direction should he drive to reach Point A again?',
    options: [
      { id: 'A', text: '3 km to the South' },
      { id: 'B', text: '4 km to the South' },
      { id: 'C', text: '1 km to the North' },
      { id: 'D', text: '2 km to the North' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: 'Coordinates starting from $A(0,0)$:\n1. 24 km East $\\to (24, 0)$\n2. Right (South) 23 km $\\to (24, -23)$\n3. Right (West) 26 km $\\to (-2, -23)$\n4. Right (North) 27 km $\\to (-2, 4)$\n5. Right (East) 2 km $\\to (0, 4) = P$.\nTo reach $A(0,0)$ from $P(0,4)$, Mohit must travel 4 km South.',
    formulaConcept: '2D Cartesian path summation: $x = 24 - 26 + 2 = 0$, $y = -23 + 27 = 4$.',
    shortcutTrick: '$P = (0, 4) \\implies$ Move 4 km South to reach $(0,0)$.',
    commonMistake: 'Selecting 4 km to the North (direction from A to P instead of P to A).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q4',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Mensuration',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A toy is in the form of a solid cone having a radius of 5 cm and a height of 12 cm. It is mounted on a frustum of a solid cone, with the smaller base having a radius of 5 cm. The larger base of the frustum has a radius of 22 cm. The slant height of the frustum is 32 cm. What is the total surface area (in cm²) of the toy?',
    options: [
      { id: 'A', text: '1341π' },
      { id: 'B', text: '1431π' },
      { id: 'C', text: '1314π' },
      { id: 'D', text: '1413π' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: '1. Slant height of top cone: $l_1 = \\sqrt{5^2 + 12^2} = 13\\text{ cm}$.\n2. Curved surface area of top cone: $CSA_1 = \\pi r_1 l_1 = \\pi \\times 5 \\times 13 = 65\\pi$.\n3. Curved surface area of frustum: $CSA_2 = \\pi (r_1 + r_2) L = \\pi (5 + 22) \\times 32 = \\pi \\times 27 \\times 32 = 864\\pi$.\n4. Area of bottom circular base: $A_{\\text{base}} = \\pi r_2^2 = \\pi \\times 22^2 = 484\\pi$.\nTotal Surface Area $= 65\\pi + 864\\pi + 484\\pi = 1413\\pi\\text{ cm}^2$.',
    formulaConcept: 'Composite Surface Area: $TSA = CSA_{\\text{cone}} + CSA_{\\text{frustum}} + \\text{Base Area}$.',
    shortcutTrick: '$65\\pi + 864\\pi + 484\\pi = 1413\\pi$.',
    commonMistake: 'Including the internal junction circle ($r=5$) twice.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q5',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Work',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A and B can do a piece of work in 10 days, B and C in 15 days, and C and A in 20 days. In how many days can C alone do the work?',
    options: [
      { id: 'A', text: '120 days' },
      { id: 'B', text: '140 days' },
      { id: 'C', text: '150 days' },
      { id: 'D', text: '130 days' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '$2(A + B + C) = \\frac{1}{10} + \\frac{1}{15} + \\frac{1}{20} = \\frac{6 + 4 + 3}{60} = \\frac{13}{60} \\implies A + B + C = \\frac{13}{120}$.\n$C = (A + B + C) - (A + B) = \\frac{13}{120} - \\frac{1}{10} = \\frac{13 - 12}{120} = \\frac{1}{120}$.\nTherefore, C alone takes 120 days.',
    formulaConcept: 'Cyclic Work Rates: $2(A+B+C) = \\sum R_{ij}$.',
    shortcutTrick: '$C = \\frac{13}{120} - \\frac{12}{120} = \\frac{1}{120} \\implies 120$ days.',
    commonMistake: 'Forgetting to divide by 2 when summing pairs.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q6',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Each vowel in the word CRUMBLE is changed to the letter immediately following it in the English alphabetical order and each consonant is changed to the letter immediately preceding it. Which letter will be third from the left in the new group?',
    options: [
      { id: 'A', text: 'L' },
      { id: 'B', text: 'A' },
      { id: 'C', text: 'V' },
      { id: 'D', text: 'Q' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Transforming CRUMBLE:\n- C (consonant) $\\to$ B\n- R (consonant) $\\to$ Q\n- U (vowel) $\\to$ V\n- M (consonant) $\\to$ L\n- B (consonant) $\\to$ A\n- L (consonant) $\\to$ K\n- E (vowel) $\\to$ F\nNew word: B Q V L A K F. Third letter from left is V.',
    formulaConcept: 'Positional Letter Transformation.',
    shortcutTrick: 'Directly check 3rd letter: U is a vowel $\\implies U + 1 = V$.',
    commonMistake: 'Transforming all letters instead of just focusing on the 3rd letter.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q7',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'L, K, H, M, Z and U live on six different floors (1 to 6). L lives immediately below H. Z lives immediately below U. Only three people live between M and Z. K does not live on the topmost floor. H does not live on any floors below U. How many people live between H and K?',
    options: [
      { id: 'A', text: 'Three' },
      { id: 'B', text: 'One' },
      { id: 'C', text: 'Four' },
      { id: 'D', text: 'Two' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 60,
    explanation: '1. Z is immediately below U (pair U-Z).\n2. Exactly 3 people between M and Z $\\implies$ Z must be on Floor 2, M on Floor 6 (with U on Floor 3).\n3. L lives immediately below H $\\implies$ H is on Floor 5 and L on Floor 4.\n4. K is on Floor 1 (satisfying K $\\ne$ 6).\nArrangement: 6-M, 5-H, 4-L, 3-U, 2-Z, 1-K.\nBetween H (Floor 5) and K (Floor 1), there are 3 people (L, U, Z on floors 4, 3, 2).',
    formulaConcept: 'Floor Arrangement Puzzle.',
    shortcutTrick: 'Floors 5 to 1: $5 - 1 - 1 = 3$ people.',
    commonMistake: 'Placing Z on floor 1.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q8',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Sound',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'When a sound is produced, what travels through the medium?',
    options: [
      { id: 'A', text: 'Both the particles and the disturbance' },
      { id: 'B', text: 'Neither particles nor disturbance' },
      { id: 'C', text: 'The particles of the medium' },
      { id: 'D', text: 'The disturbance created by the sound source' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'In a mechanical wave like sound, medium particles only oscillate back and forth about their mean equilibrium positions; it is the energy and disturbance (compressions/rarefactions) that propagates through the medium.',
    formulaConcept: 'Wave Propagation Principle: Energy/Disturbance travels, matter oscillates locally.',
    shortcutTrick: 'Waves transport disturbance and energy, NOT matter.',
    commonMistake: 'Thinking air particles travel from speaker to listener.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q9',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Geometry',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In ΔPQR, points M and N lie on sides PQ and PR respectively such that MN || QR. If PM : QM = 4 : 7 and area of ΔPMN = 36 cm², find the area of trapezium MQRN.',
    options: [
      { id: 'A', text: '236.25 cm2' },
      { id: 'B', text: '222.86 cm2' },
      { id: 'C', text: '216.36 cm2' },
      { id: 'D', text: '248.15 cm2' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: '$PQ = PM + QM = 4 + 7 = 11$.\nSince $\\Delta PMN \\sim \\Delta PQR$, the ratio of their areas is equal to the square of corresponding side ratios:\n$\\frac{\\text{Area}(\\Delta PQR)}{\\text{Area}(\\Delta PMN)} = \\left(\\frac{11}{4}\\right)^2 = \\frac{121}{16}$.\n$\\text{Area}(\\Delta PQR) = 36 \\times \\frac{121}{16} = 9 \\times \\frac{121}{4} = \\frac{1089}{4} = 272.25\\text{ cm}^2$.\n$\\text{Area}(\\text{Trapezium MQRN}) = \\text{Area}(\\Delta PQR) - \\text{Area}(\\Delta PMN) = 272.25 - 36 = 236.25\\text{ cm}^2$.',
    formulaConcept: 'Similar Triangles Area Theorem: $\\frac{A_1}{A_2} = \\left(\\frac{s_1}{s_2}\\right)^2$.',
    shortcutTrick: '$\\text{Trapezium Area} = 36 \\times \\frac{121 - 16}{16} = 36 \\times \\frac{105}{16} = \\frac{945}{4} = 236.25\\text{ cm}^2$.',
    commonMistake: 'Using $7/4$ instead of $(11/4)^2$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q10',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Work',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A machine does 1000 J of work in 5 seconds. Its power is:',
    options: [
      { id: 'A', text: '500 W' },
      { id: 'B', text: '100 W' },
      { id: 'C', text: '50 W' },
      { id: 'D', text: '200 W' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Power $P = \\frac{W}{t} = \\frac{1000\\text{ J}}{5\\text{ s}} = 200\\text{ W}$.',
    formulaConcept: 'Power Definition: $P = \\frac{W}{t}$.',
    shortcutTrick: '$1000 / 5 = 200\\text{ W}$.',
    commonMistake: 'Multiplying work by time.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q11',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Mathematical',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'What will come in place of the question mark (?) in the following equation, if \'+\' and \'÷\' are interchanged and \'-\' and \'×\' are interchanged?\n\n195 + 5 x 44 - 6 ÷ 320 = ?',
    options: [
      { id: 'A', text: '109' },
      { id: 'B', text: '91' },
      { id: 'C', text: '95' },
      { id: 'D', text: '113' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: 'Substitute interchanged operators:\n$195 \\div 5 - 44 \\times 6 + 320$\n1. Division: $195 \\div 5 = 39$\n2. Multiplication: $44 \\times 6 = 264$\n3. Expression: $39 - 264 + 320 = 359 - 264 = 95$.',
    formulaConcept: 'BODMAS evaluation after sign substitution.',
    shortcutTrick: '$39 + 320 - 264 = 359 - 264 = 95$.',
    commonMistake: 'Applying operations from left to right without precedence.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q12',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a certain code language, ‘CASH’ is coded as ‘1937’ and ‘EAHS’ is coded as ‘9163’. What is the code for ‘E’ in the given code language?',
    options: [
      { id: 'A', text: '9' },
      { id: 'B', text: '3' },
      { id: 'C', text: '6' },
      { id: 'D', text: '1' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Common letters between CASH and EAHS: {A, S, H}.\nCommon digits between {1,9,3,7} and {9,1,6,3}: {1, 9, 3}.\nRemaining unique letter in EAHS is \'E\', and remaining unique digit is \'6\'.\nTherefore, code for \'E\' is 6.',
    formulaConcept: 'Set difference in coded character sets.',
    shortcutTrick: 'Common {A,S,H} = {1,3,9} $\\implies E = 6$.',
    commonMistake: 'Assuming 1st position mapping $E=9$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q13',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Chemistry',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The thermal decomposition of sodium hydrogen carbonate ($NaHCO_3$) upon heating produces:',
    options: [
      { id: 'A', text: 'Sodium chloride, water, and hydrogen gas under normal heating' },
      { id: 'B', text: 'Sodium hydroxide, oxygen, and carbon monoxide at high temperature' },
      { id: 'C', text: 'Sodium carbonate, water, and carbon dioxide gas during cooking' },
      { id: 'D', text: 'Sodium sulfate, hydrogen, and carbon dioxide when strongly heated' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Thermal decomposition of baking soda:\n$2NaHCO_3 \\xrightarrow{\\Delta} Na_2CO_3 + H_2O + CO_2\\uparrow$.\nThe released $CO_2$ gas causes dough and batter to rise during baking.',
    formulaConcept: 'Baking Soda Thermal Decomposition: $2NaHCO_3 \\to Na_2CO_3 + H_2O + CO_2$.',
    shortcutTrick: 'Baking soda heating = Sodium carbonate + Water + $CO_2$.',
    commonMistake: 'Selecting sodium hydroxide or chloride.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q14',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Simplification',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Simplify: $2 - [2 - 3\\{2 - (2 - 4)\\} \\div 2]$',
    options: [
      { id: 'A', text: '8' },
      { id: 'B', text: '4' },
      { id: 'C', text: '2' },
      { id: 'D', text: '6' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '1. Inner parenthesis: $(2 - 4) = -2$.\n2. Curly braces: $2 - (-2) = 4$.\n3. Multiplication and division: $3 \\times 4 \\div 2 = 12 \\div 2 = 6$.\n4. Square bracket: $2 - 6 = -4$.\n5. Outer subtraction: $2 - (-4) = 2 + 4 = 6$.',
    formulaConcept: 'BODMAS Rule with nested brackets.',
    shortcutTrick: '$2 - [2 - 6] = 2 - [-4] = 6$.',
    commonMistake: 'Sign errors in nested double negatives.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q15',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Anand purchased an item and spent ₹175 on its repair. He then sold it to Bharath at a profit of 25%. Later, Bharath sold the item for ₹3,402, incurring a loss of 58%. What was Anand’s total cost (in ₹) of the item just before selling it to Bharath?',
    options: [
      { id: 'A', text: '6478' },
      { id: 'B', text: '6483' },
      { id: 'C', text: '6481' },
      { id: 'D', text: '6480' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: '1. Bharath sold for ₹3,402 at 58% loss:\n$\\text{Bharath\'s CP} = \\frac{3402}{1 - 0.58} = \\frac{3402}{0.42} = 8100$.\n2. Anand\'s Selling Price to Bharath $= ₹8,100$.\n3. Anand sold at 25% profit $\\implies \\text{Anand\'s Total Cost} = \\frac{8100}{1.25} = ₹6,480$.',
    formulaConcept: 'Chain Trade CP/SP Relations: $\\text{Cost} = \\frac{\\text{SP}}{1 \\pm r}$.',
    shortcutTrick: '$3402 / 0.42 = 8100 \\implies 8100 / 1.25 = 6480$.',
    commonMistake: 'Subtracting ₹175 when the question asks for cost just before selling.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q16',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of ? in the given series?\n\n36 40 46 50 56 ?',
    options: [
      { id: 'A', text: '59' },
      { id: 'B', text: '61' },
      { id: 'C', text: '62' },
      { id: 'D', text: '60' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Alternating addition pattern (+4, +6):\n$36 + 4 = 40$\n$40 + 6 = 46$\n$46 + 4 = 50$\n$50 + 6 = 56$\n$56 + 4 = 60$.',
    formulaConcept: 'Alternating Arithmetic Progression.',
    shortcutTrick: 'Pattern: $+4, +6, +4, +6, +4 \\implies 56 + 4 = 60$.',
    commonMistake: 'Adding 6 to get 62.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q17',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Direction',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Arman starts from Point A and drives 61 km west. He turns right and drives 58 km, turns right and drives 64 km. He turns right and drives 71 km. He takes a final right turn, drives 3 km and stops at Point P. How far and towards which direction should he drive to reach Point A again?',
    options: [
      { id: 'A', text: '15 km to the south' },
      { id: 'B', text: '14 km to the south' },
      { id: 'C', text: '12 km to the north' },
      { id: 'D', text: '13 km to the north' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: 'Coordinates starting from $A(0,0)$:\n1. 61 km West $\\to (-61, 0)$\n2. Right (North) 58 km $\\to (-61, 58)$\n3. Right (East) 64 km $\\to (3, 58)$\n4. Right (South) 71 km $\\to (3, -13)$\n5. Right (West) 3 km $\\to (0, -13) = P$.\nTo reach $A(0,0)$ from $P(0, -13)$, Arman must drive 13 km North.',
    formulaConcept: 'Coordinate tracking: $x = -61 + 64 - 3 = 0$; $y = 58 - 71 = -13$.',
    shortcutTrick: '$P = (0, -13) \\implies$ 13 km North to reach origin.',
    commonMistake: 'Selecting 13 km south.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q18',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a certain code language, ‘SONG’ is coded as ‘9785’ and ‘GONE’ is coded as ‘5867’. What is the code for ‘E’ in the given code language?',
    options: [
      { id: 'A', text: '6' },
      { id: 'B', text: '8' },
      { id: 'C', text: '5' },
      { id: 'D', text: '7' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Compare SONG and GONE:\nCommon letters: {O, N, G}.\nCommon code digits: {5, 7, 8}.\nRemaining letter in GONE is \'E\', and remaining digit in code is \'6\'.\nTherefore, code for \'E\' is 6.',
    formulaConcept: 'Set elimination in cipher decoding.',
    shortcutTrick: 'Unique letter in GONE is E $\\implies$ Unique digit is 6.',
    commonMistake: 'Confusing 5, 7, 8.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q19',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: '24 is related to 74 following a certain logic. Following the same logic, 36 is related to 110. To which of the given options is 51 related, following the same logic?',
    options: [
      { id: 'A', text: '155' },
      { id: 'B', text: '261' },
      { id: 'C', text: '151' },
      { id: 'D', text: '266' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Pattern: $3n + 2$.\n- $24 \\times 3 + 2 = 72 + 2 = 74$\n- $36 \\times 3 + 2 = 108 + 2 = 110$\n- $51 \\times 3 + 2 = 153 + 2 = 155$.',
    formulaConcept: 'Linear Number Transformation: $f(x) = 3x + 2$.',
    shortcutTrick: '$51 \\times 3 + 2 = 155$.',
    commonMistake: 'Multiplying by 3 without adding 2 ($153$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q20',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Ratio',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following ratios is the greatest: 8 : 11, 5 : 7, 13 : 17, or 11 : 13?',
    options: [
      { id: 'A', text: '13 : 17' },
      { id: 'B', text: '8 : 11' },
      { id: 'C', text: '5 : 7' },
      { id: 'D', text: '11 : 13' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Convert to decimal fractions:\n- $8 / 11 \\approx 0.727$\n- $5 / 7 \\approx 0.714$\n- $13 / 17 \\approx 0.7647$\n- $11 / 13 \\approx 0.8461$.\n$0.8461$ is the largest value. Hence, $11 : 13$ is greatest.',
    formulaConcept: 'Fraction comparison via decimal evaluation or cross-multiplication.',
    shortcutTrick: 'Difference between num and den is 2 for $11/13$ and $5/7$. Larger numbers with same difference are larger ($11/13 > 5/7$).',
    commonMistake: 'Assuming 13:17 is greatest due to largest numbers.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q21',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Select the set in which the numbers are related in the same way as in the given sets: (18, 5, 85) ; (11, 7, 72).',
    options: [
      { id: 'A', text: '(9, 7, 68)' },
      { id: 'B', text: '(15, 6, 85)' },
      { id: 'C', text: '(10, 8, 85)' },
      { id: 'D', text: '(8, 4, 32)' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Pattern: $a \\times b - 5 = c$.\n- $18 \\times 5 - 5 = 90 - 5 = 85$\n- $11 \\times 7 - 5 = 77 - 5 = 72$\n- For (15, 6, 85): $15 \\times 6 - 5 = 90 - 5 = 85$.',
    formulaConcept: 'Number Triad Relation: $c = ab - 5$.',
    shortcutTrick: '$15 \\times 6 = 90 \\implies 90 - 5 = 85$.',
    commonMistake: 'Checking difference without product.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q22',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Speed',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A speedboat, whose speed is 16 km/hr in still water, travels 40 km downstream and returns in a total of 6 hours 24 minutes. What is the speed of the stream (in km/hr)?',
    options: [
      { id: 'A', text: '3√7' },
      { id: 'B', text: '3√14' },
      { id: 'C', text: '2√14' },
      { id: 'D', text: '2√7' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: 'Total time $= 6\\text{ hrs } 24\\text{ min} = 6 + \\frac{24}{60} = 6.4\\text{ hrs} = \\frac{32}{5}\\text{ hrs}$.\n$\\frac{40}{16 + v} + \\frac{40}{16 - v} = \\frac{32}{5} \\implies 40 \\left[\\frac{32}{256 - v^2}\\right] = \\frac{32}{5}$.\nDivide both sides by 32: $\\frac{40}{256 - v^2} = \\frac{1}{5} \\implies 256 - v^2 = 200 \\implies v^2 = 56$.\n$v = \\sqrt{56} = 2\\sqrt{14}\\text{ km/hr}$.',
    formulaConcept: 'Upstream-Downstream Time Equation: $T = \\frac{D}{u+v} + \\frac{D}{u-v} = \\frac{2Du}{u^2 - v^2}$.',
    shortcutTrick: '$256 - v^2 = 200 \\implies v = \\sqrt{56} = 2\\sqrt{14}$.',
    commonMistake: 'Miscalculating $6\\text{h }24\\text{m}$ into decimals ($6.24$ instead of $6.4$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q23',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Ratio',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A sum of ₹5,890 is divided between Alok, Gita and Suresh such that if their shares are decreased by ₹320, ₹590 and ₹750, respectively, then they are in the ratio of 9 : 3 : 6. What is the original share of Gita?',
    options: [
      { id: 'A', text: '₹1,209' },
      { id: 'B', text: '₹1,380' },
      { id: 'C', text: '₹1,295' },
      { id: 'D', text: '₹1,157' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: '1. Total deductions $= 320 + 590 + 750 = 1660$.\n2. Net divisible sum $= 5890 - 1660 = ₹4,230$.\n3. Sum of ratio terms $= 9 + 3 + 6 = 18$.\n4. Unit value $= \\frac{4230}{18} = 235$.\n5. Gita\'s reduced share $= 3 \\times 235 = ₹705$.\n6. Gita\'s original share $= 705 + 590 = ₹1,295$.',
    formulaConcept: 'Deduction-based Ratio Partitioning.',
    shortcutTrick: '$\\text{Gita} = \\frac{3}{18}(4230) + 590 = 705 + 590 = 1295$.',
    commonMistake: 'Forgetting to add back the deducted ₹590 to find the original share.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q24',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Mathematical',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If ‘A’ stands for ‘÷’, ‘B’ stands for ‘×’, ‘C’ stands for ‘+’ and ‘D’ stands for ‘−’, then what will come in place of the question mark (?) in:\n\n26 A 2 C 14 B 4 D 18 = ?',
    options: [
      { id: 'A', text: '51' },
      { id: 'B', text: '44' },
      { id: 'C', text: '62' },
      { id: 'D', text: '70' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '$26 \\div 2 + 14 \\times 4 - 18 = 13 + 56 - 18 = 69 - 18 = 51$.',
    formulaConcept: 'BODMAS Evaluation.',
    shortcutTrick: '$13 + 56 - 18 = 51$.',
    commonMistake: 'Performing addition before multiplication.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q25',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Percentage',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'During a sale, 40% of the goods are sold at a 44% profit, 25% of the remaining goods are sold at a 29% profit and the rest are sold at a 39% loss. If there is an overall profit of x%, then what is the value of x?',
    options: [
      { id: 'A', text: '4.4%' },
      { id: 'B', text: '15%' },
      { id: 'C', text: '7.5%' },
      { id: 'D', text: '10.5%' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: 'Let total goods $= 100$.\n1. Portion 1: $40$ goods sold at $+44\\% \\implies 40 \\times 0.44 = +17.6$.\n2. Remaining $= 60$. Portion 2: $25\\% \\text{ of } 60 = 15$ goods sold at $+29\\% \\implies 15 \\times 0.29 = +4.35$.\n3. Portion 3: $60 - 15 = 45$ goods sold at $-39\\% \\implies 45 \\times (-0.39) = -17.55$.\nNet Profit $= 17.6 + 4.35 - 17.55 = +4.4\\%$.',
    formulaConcept: 'Weighted Average Profit/Loss: $x = \\sum w_i p_i$.',
    shortcutTrick: '$17.6 + 4.35 - 17.55 = 4.4\\%$.',
    commonMistake: 'Taking 25% of total goods instead of remaining goods.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q26',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Statistics',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A student\'s marks were incorrectly entered as 32 instead of 96. Due to this, the average marks of the class got decreased by 4/3. What is the number of students in the class?',
    options: [
      { id: 'A', text: '45' },
      { id: 'B', text: '48' },
      { id: 'C', text: '51' },
      { id: 'D', text: '54' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Difference in total sum $= 96 - 32 = 64$.\n$\\frac{\\text{Total Deficit}}{n} = \\frac{4}{3} \\implies \\frac{64}{n} = \\frac{4}{3} \\implies n = \\frac{64 \\times 3}{4} = 48$.',
    formulaConcept: 'Average Shift Formula: $\\Delta \\bar{x} = \\frac{\\Delta \\sum x}{n}$.',
    shortcutTrick: '$n = 64 \\times \\frac{3}{4} = 48$.',
    commonMistake: 'Multiplying 64 by 4/3 instead of dividing.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q27',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Interest',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What sum (in ₹) will earn an interest of ₹480 in 3 years at 5% simple interest per year?',
    options: [
      { id: 'A', text: '3000' },
      { id: 'B', text: '3350' },
      { id: 'C', text: '3200' },
      { id: 'D', text: '3400' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '$P = \\frac{SI \\times 100}{R \\times T} = \\frac{480 \\times 100}{5 \\times 3} = \\frac{48000}{15} = ₹3,200$.',
    formulaConcept: 'Simple Interest Formula: $SI = \\frac{PRT}{100}$.',
    shortcutTrick: '$480 / 15\\% = 3200$.',
    commonMistake: 'Calculation error with 480/15.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q28',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A, B, C, D, E, F and G live on seven different floors (1 to 7). Only two persons live above C. Only two persons live between C and E. B lives immediately above E. D lives immediately below F. A does not live on the lowermost floor. On which floor number does A live?',
    options: [
      { id: 'A', text: 'Floor number 2' },
      { id: 'B', text: 'Floor number 3' },
      { id: 'C', text: 'Floor number 4' },
      { id: 'D', text: 'Floor number 6' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 60,
    explanation: '1. Two persons above C $\\implies$ C is on Floor 5.\n2. Two persons between C and E $\\implies$ E is on Floor 2.\n3. B is immediately above E $\\implies$ B is on Floor 3.\n4. D is immediately below F $\\implies$ Pair F-D must occupy available adjacent slots (Floors 7 and 6).\n5. Remaining floors are 4 and 1. Since A cannot be on Floor 1, A is on Floor 4 and G is on Floor 1.\nFloor layout: 7-F, 6-D, 5-C, 4-A, 3-B, 2-E, 1-G.\nA lives on Floor 4.',
    formulaConcept: '7-Floor Sequential Elimination.',
    shortcutTrick: 'C=5, E=2, B=3, F=7, D=6, A=4, G=1.',
    commonMistake: 'Placing F and D on floors 4 and 3.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q29',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Percentage',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'There are 2,100 members in a local group. In 2019, the number of members increased by 15%. In 2020, however, the number decreased by 20%. What is the total number of members after these two changes?',
    options: [
      { id: 'A', text: '1932' },
      { id: 'B', text: '1754' },
      { id: 'C', text: '1905' },
      { id: 'D', text: '1836' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '$\\text{Final} = 2100 \\times 1.15 \\times 0.80 = 2100 \\times 0.92 = 1932$.',
    formulaConcept: 'Net successive percentage change: $1.15 \\times 0.80 = 0.92$ (net $-8\\%$).',
    shortcutTrick: '$2100 - 8\\% \\text{ of } 2100 = 2100 - 168 = 1932$.',
    commonMistake: 'Subtracting 5% directly ($2100 \\times 0.95 = 1995$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q30',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Based on the five three-digit numbers: 629, 574, 315, 681, 459. What will be the resultant if the second digit of the highest number is added to the third digit of the lowest number?',
    options: [
      { id: 'A', text: '13' },
      { id: 'B', text: '11' },
      { id: 'C', text: '10' },
      { id: 'D', text: '12' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '1. Highest number is 681 $\\implies$ second digit is 8.\n2. Lowest number is 315 $\\implies$ third digit is 5.\nResultant $= 8 + 5 = 13$.',
    formulaConcept: 'Digit Extraction and Arithmetic.',
    shortcutTrick: '$8 + 5 = 13$.',
    commonMistake: 'Selecting 629 as highest number instead of 681.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q31',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Six friends D, E, F, G, J and K are sitting in a straight line facing north. No one sits to the right of K. Only one person sits between F and K. Only three people sit between K and J. G sits to the left of D but to the right of E. How many people sit between E and D?',
    options: [
      { id: 'A', text: 'Two' },
      { id: 'B', text: 'Four' },
      { id: 'C', text: 'One' },
      { id: 'D', text: 'Three' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: 'Slots 1 to 6 (left to right):\n1. No one right of K $\\implies$ K is at Slot 6.\n2. One person between F and K $\\implies$ F is at Slot 4.\n3. Three people between K and J $\\implies$ J is at Slot 2.\n4. G is between E and D $\\implies$ Slot 1 is E, Slot 3 is G, Slot 5 is D.\nOrder: 1-E, 2-J, 3-G, 4-F, 5-D, 6-K.\nBetween E (Slot 1) and D (Slot 5), there are 3 people (J, G, F).',
    formulaConcept: 'Linear Arrangement with Positional Constraints.',
    shortcutTrick: 'E-J-G-F-D-K $\\implies 5 - 1 - 1 = 3$ people.',
    commonMistake: 'Counting boundaries E and D.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q32',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of the question mark (?) in the given series?\n\n64 68 80 84 96 100 112 ?',
    options: [
      { id: 'A', text: '124' },
      { id: 'B', text: '120' },
      { id: 'C', text: '116' },
      { id: 'D', text: '118' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Alternating $+4, +12$ pattern:\n$64 + 4 = 68$\n$68 + 12 = 80$\n$80 + 4 = 84$\n$84 + 12 = 96$\n$96 + 4 = 100$\n$100 + 12 = 112$\n$112 + 4 = 116$.',
    formulaConcept: 'Two-step difference progression: $+4, +12$.',
    shortcutTrick: '$112 + 4 = 116$.',
    commonMistake: 'Adding 12 instead of 4 ($124$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q33',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Based on the English alphabetical order, three of the following four letter-cluster pairs are alike in a certain way and form a group. Which pair DOES NOT belong to that group?\n\n1. AW - KP\n2. AC - DF\n3. PR - SU\n4. GI - JL',
    options: [
      { id: 'A', text: 'AW - KP' },
      { id: 'B', text: 'AC - DF' },
      { id: 'C', text: 'PR - SU' },
      { id: 'D', text: 'GI - JL' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Check intra-cluster letter gaps:\n- AC ($A+2=C$), DF ($D+2=F$)\n- PR ($P+2=R$), SU ($S+2=U$)\n- GI ($G+2=I$), JL ($J+2=L$)\nAll three have $+2$ gap inside each cluster.\n- AW: $A(1) \\to W(23)$ (gap $-4$), KP: $K(11) \\to P(16)$ (gap $+5$). AW-KP does not conform.',
    formulaConcept: 'Internal gap parity across paired letter clusters.',
    shortcutTrick: 'All other pairs have $+2$ internal gaps in both clusters.',
    commonMistake: 'Looking only at 1st letters across clusters.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q34',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Algebra',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'If $4x^2 + \\frac{1}{4x^2} = 14$, what is the positive value of $x + \\frac{1}{4x}$?',
    options: [
      { id: 'A', text: '4' },
      { id: 'B', text: '8' },
      { id: 'C', text: '2' },
      { id: 'D', text: '1' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1. $\\left(2x + \\frac{1}{2x}\\right)^2 = 4x^2 + \\frac{1}{4x^2} + 2 = 14 + 2 = 16$.\n2. Taking square root: $2x + \\frac{1}{2x} = 4$.\n3. Dividing the entire equation by 2:\n$\\frac{2x + 1/(2x)}{2} = x + \\frac{1}{4x} = \\frac{4}{2} = 2$.',
    formulaConcept: 'Algebraic Completing the Square: $(a + b)^2 = a^2 + b^2 + 2ab$.',
    shortcutTrick: '$\\sqrt{14 + 2} / 2 = 4 / 2 = 2$.',
    commonMistake: 'Leaving answer as 4 without dividing by 2.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q35',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Simplification',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'The simplified value of $\\frac{\\sqrt[3]{2744}}{\\sqrt[4]{4096}} \\times \\frac{4}{42} \\times 84$ is:',
    options: [
      { id: 'A', text: '14' },
      { id: 'B', text: '22' },
      { id: 'C', text: '13' },
      { id: 'D', text: '15' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1. $\\sqrt[3]{2744} = 14$ (since $14^3 = 2744$).\n2. $\\sqrt[4]{4096} = 8$ (since $8^4 = 4096$).\n3. Expression: $\\frac{14}{8} \\times \\frac{4}{42} \\times 84 = \\frac{14}{8} \\times 4 \\times 2 = \\frac{14}{8} \\times 8 = 14$.',
    formulaConcept: 'Surds and Roots Evaluation.',
    shortcutTrick: '$\\frac{14}{8} \\times \\frac{4}{42} \\times 84 = \\frac{14}{8} \\times 8 = 14$.',
    commonMistake: 'Taking $\\sqrt{4096} = 64$ instead of 4th root.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q36',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Mensuration',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'If the radius of the base of a right circular cylinder is decreased by 19% and its height is increased by 129%, then what is the percentage increase in its volume? [Give answer correct to nearest integer]',
    options: [
      { id: 'A', text: '66%' },
      { id: 'B', text: '50%' },
      { id: 'C', text: '28%' },
      { id: 'D', text: '36%' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '$V = \\pi r^2 h$.\n$\\frac{V_{\\text{new}}}{V_{\\text{old}}} = (1 - 0.19)^2 \\times (1 + 1.29) = (0.81)^2 \\times 2.29 = 0.6561 \\times 2.29 = 1.502469$.\nPercentage increase $= (1.502469 - 1) \\times 100 \\approx 50.25\\% \\approx 50\\%$.',
    formulaConcept: 'Cylinder Volume Scaling: $V \\propto r^2 h$.',
    shortcutTrick: '$0.656 \\times 2.29 \\approx 1.50 \\implies +50\\%$.',
    commonMistake: 'Applying linear radius scaling instead of $r^2$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q37',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Biology',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'On reaching an organ or tissue, arteries divide into smaller and smaller vessels. The smallest vessels have walls that are one cell thick and are called:',
    options: [
      { id: 'A', text: 'capillaries' },
      { id: 'B', text: 'veins' },
      { id: 'C', text: 'arteries' },
      { id: 'D', text: 'arterioles' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Capillaries are microscopic vessels with single-cell-thick endothelial walls that facilitate rapid gas, nutrient, and waste exchange between blood and tissue cells.',
    formulaConcept: 'Circulatory System Hierarchy: Arteries $\\to$ Arterioles $\\to$ Capillaries $\\to$ Venules $\\to$ Veins.',
    shortcutTrick: 'One cell thick walls = Capillaries.',
    commonMistake: 'Selecting arterioles (which have muscular walls).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q38',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of the question mark (?) in the given series based on the English alphabetical order?\n\nDHS HLW LPA PTE ?',
    options: [
      { id: 'A', text: 'TXS' },
      { id: 'B', text: 'TIX' },
      { id: 'C', text: 'TXI' },
      { id: 'D', text: 'TCD' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'All letter positions increase by $+4$:\n1st letter: $D(4) \\xrightarrow{+4} H(8) \\xrightarrow{+4} L(12) \\xrightarrow{+4} P(16) \\xrightarrow{+4} T(20)$\n2nd letter: $H(8) \\xrightarrow{+4} L(12) \\xrightarrow{+4} P(16) \\xrightarrow{+4} T(20) \\xrightarrow{+4} X(24)$\n3rd letter: $S(19) \\xrightarrow{+4} W(23) \\xrightarrow{+4} A(27/1) \\xrightarrow{+4} E(5) \\xrightarrow{+4} I(9)$.\nTerm is TXI.',
    formulaConcept: 'Uniform $+4$ Positional Advancement.',
    shortcutTrick: '$P+4=T, T+4=X, E+4=I \\implies \\text{TXI}$.',
    commonMistake: 'Selecting TIX by reversing the last two letters.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q39',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Classification',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Based on the English alphabetical order, three of the following four letter-cluster pairs are alike in a certain way and form a group. Which pair DOES NOT belong to that group?\n\n1. OP−ST\n2. VW−ZA\n3. MN−QR\n4. EF−HL',
    options: [
      { id: 'A', text: 'OP−ST' },
      { id: 'B', text: 'VW−ZA' },
      { id: 'C', text: 'MN−QR' },
      { id: 'D', text: 'EF−HL' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Pattern:\n- OP−ST: $O(+1)P \\xrightarrow{+3} S(+1)T$\n- VW−ZA: $V(+1)W \\xrightarrow{+3} Z(+1)A$\n- MN−QR: $M(+1)N \\xrightarrow{+3} Q(+1)R$\nIn all three, both clusters are consecutive ($+1$), with a $+3$ bridge.\n- EF−HL: $E(+1)F \\xrightarrow{+2} H(+4)L$. HL has a $+4$ gap. Hence EF−HL is the odd one out.',
    formulaConcept: 'Intra-cluster difference matching.',
    shortcutTrick: '$H(8) \\to L(12)$ has gap $+4$ unlike all others which have $+1$.',
    commonMistake: 'Overlooking the $+4$ in HL.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q40',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Statistics',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'If the mean of 10 observations $x_1, x_2, ..., x_{10}$ is 20, then the value of $\\sum_{i=1}^{10} \\left(\\frac{3x_i - 4}{5}\\right)$ is:',
    options: [
      { id: 'A', text: '111' },
      { id: 'B', text: '113' },
      { id: 'C', text: '110' },
      { id: 'D', text: '112' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Given $\\frac{1}{10}\\sum x_i = 20 \\implies \\sum_{i=1}^{10} x_i = 200$.\n$\\sum_{i=1}^{10} \\left(\\frac{3x_i - 4}{5}\\right) = \\frac{3\\sum x_i - 4 \\times 10}{5} = \\frac{3(200) - 40}{5} = \\frac{600 - 40}{5} = \\frac{560}{5} = 112$.',
    formulaConcept: 'Linearity of Summation: $\\sum (a x_i + b) = a \\sum x_i + n b$.',
    shortcutTrick: '$\\frac{3(20) - 4}{5} \\times 10 = \\frac{56}{5} \\times 10 = 112$.',
    commonMistake: 'Subtracting 4 instead of $4 \\times 10 = 40$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q41',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Biology',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following is commonly known as the Indian honey bee?',
    options: [
      { id: 'A', text: 'Apis mellifera' },
      { id: 'B', text: 'Apis cerana indica' },
      { id: 'C', text: 'Apis florea' },
      { id: 'D', text: 'Apis dorsata' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 10,
    explanation: 'Apis cerana indica is the Indian honey bee. Apis dorsata is the rock bee, Apis florea is the little bee, and Apis mellifera is the European/Italian bee.',
    formulaConcept: 'Apiculture & Honeybee Species Classification.',
    shortcutTrick: 'Indian bee = Apis cerana indica.',
    commonMistake: 'Confusing Apis mellifera (European) with Apis cerana indica.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q42',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Select the pair which follows the same pattern as that followed by the two pairs given below:\nALI : BIE\nIIK : JFG',
    options: [
      { id: 'A', text: 'BFK : BBG' },
      { id: 'B', text: 'CJE : DGA' },
      { id: 'C', text: 'FQO : FNJ' },
      { id: 'D', text: 'IPN : IMI' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check shift pattern ($+1, -3, -4$):\n- ALI $\\to$ BIE: $A(1)+1=B(2), L(12)-3=I(9), I(9)-4=E(5)$\n- IIK $\\to$ JFG: $I(9)+1=J(10), I(9)-3=F(6), K(11)-4=G(7)$\nTesting options for $+1, -3, -4$:\n- CJE $\\to$ DGA: $C(3)+1=D(4), J(10)-3=G(7), E(5)-4=A(1)$. Exactly matches.',
    formulaConcept: 'Letter Triad Positional Delta: $[+1, -3, -4]$.',
    shortcutTrick: '$C+1=D, J-3=G, E-4=A \\implies \\text{CJE : DGA}$.',
    commonMistake: 'Applying $+1$ to all letters.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q43',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the sequence (left to right):\n^ 7 + > 6 $ > 2 8 4 6 \\ 2 & 9 ? + ^ # < %\nHow many such single-digit numbers are there, each of which is immediately preceded by a symbol and also immediately followed by a symbol?',
    options: [
      { id: 'A', text: 'Four' },
      { id: 'B', text: 'Three' },
      { id: 'C', text: 'One' },
      { id: 'D', text: 'Two' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Look for [Symbol][Number][Symbol]:\n1. ^ 7 + -> 7 is preceded by ^ and followed by + -> 1\n2. > 6 $ -> 6 is preceded by > and followed by $ -> 2\n3. \\ 2 & -> 2 is preceded by \\ and followed by & -> 3\n4. & 9 ? -> 9 is preceded by & and followed by ? -> 4\nTotal = 4 numbers (7, 6, 2, 9).',
    formulaConcept: 'Conditional scanning of symbolic strings.',
    shortcutTrick: '^7+, >6$, \\2&, &9? = 4 instances.',
    commonMistake: 'Counting 2 in 2 8 4 where it is followed by a number.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q44',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Each letter in the word VISION is changed to the letter immediately following it in English alphabetical order, and then all letters formed are arranged in reverse alphabetical order (Z to A). Which letter will be fourth from the left?',
    options: [
      { id: 'A', text: 'U' },
      { id: 'B', text: 'T' },
      { id: 'C', text: 'O' },
      { id: 'D', text: 'W' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1. Shift $+1$: V$\\to$W, I$\\to$J, S$\\to$T, I$\\to$J, O$\\to$P, N$\\to$O.\nLetters formed: W, J, T, J, P, O.\n2. Arrange in reverse alphabetical order (highest to lowest):\nW, T, P, O, J, J.\n3. Fourth letter from the left is \'O\'.',
    formulaConcept: 'Two-step string transformation: shift + descending sort.',
    shortcutTrick: 'Sort {W, J, T, J, P, O} descending: 1:W, 2:T, 3:P, 4:O.',
    commonMistake: 'Sorting in normal A-to-Z order.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q45',
  },
  {
    subjectCode: 'RRB_ALP_GA',
    topicKeyword: 'Current Affairs',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following cities hosted the World Para Athletics Championships 2025?',
    options: [
      { id: 'A', text: 'Mumbai' },
      { id: 'B', text: 'New Delhi' },
      { id: 'C', text: 'Jaipur' },
      { id: 'D', text: 'Bengaluru' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'New Delhi was selected to host the World Para Athletics Championships 2025 at the Jawaharlal Nehru Stadium.',
    formulaConcept: 'International Sports Events & Host Cities.',
    shortcutTrick: 'World Para Athletics 2025 = New Delhi.',
    commonMistake: 'Selecting Bengaluru or Mumbai.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q46',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the letter series (left to right):\nF J A F Y H J I D X Q O B C O P O G F I O G\nHow many such consonants are there, each of which is immediately preceded by a consonant and also immediately followed by a consonant?',
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '4' },
      { id: 'C', text: '5' },
      { id: 'D', text: '6' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Looking for 3 consecutive consonants [C][Target C][C]:\n- In cluster F Y H J: Y is preceded by F and followed by H (1: Y); H is preceded by Y and followed by J (2: H)\n- In cluster D X Q: X is preceded by D and followed by Q (3: X)\nTotal = 3 target consonants (Y, H, X).',
    formulaConcept: 'Vowel/Consonant triplet inspection.',
    shortcutTrick: 'Check consecutive consonant groups: FYHJ (2 inside), DXQ (1 inside) $\\implies 2+1=3$.',
    commonMistake: 'Treating Y as a vowel or missing overlapping counts.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q47',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A shopkeeper sells an item for ₹324.3 after giving two successive discounts of 60% and 31% on its marked price. Had he not given any discount, he would have earned a profit of 25%. What is the cost price (in ₹) of the item?',
    options: [
      { id: 'A', text: '968' },
      { id: 'B', text: '947' },
      { id: 'C', text: '940' },
      { id: 'D', text: '917' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: '1. $SP = MP \\times (1 - 0.60) \\times (1 - 0.31) = MP \\times 0.40 \\times 0.69 = MP \\times 0.276 = 324.3$.\n2. $MP = \\frac{324.3}{0.276} = ₹1,175$.\n3. Marked Price with zero discount gives 25% profit $\\implies CP = \\frac{MP}{1.25} = \\frac{1175}{1.25} = ₹940$.',
    formulaConcept: 'Successive Discount & Profit Back-Calculation.',
    shortcutTrick: '$324.3 / 0.276 = 1175 \\implies 1175 / 1.25 = 940$.',
    commonMistake: 'Adding discount percentages $(60+31=91\\%)$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q48',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Five friends Varun, Ankit, Neha, Adya and Ruby are of different ages. Only Adya is older than Ankit. Exactly two people are younger than Ruby. Varun is younger than Neha. How many people among them are older than Neha?',
    options: [
      { id: 'A', text: 'Three' },
      { id: 'B', text: 'Four' },
      { id: 'C', text: 'One' },
      { id: 'D', text: 'Two' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1. "Only Adya is older than Ankit" $\\implies$ Adya is 1st (oldest), Ankit is 2nd.\n2. "Exactly two people are younger than Ruby" $\\implies$ Ruby is 3rd.\n3. "Varun is younger than Neha" $\\implies$ Neha is 4th, Varun is 5th.\nOrder from oldest to youngest: Adya > Ankit > Ruby > Neha > Varun.\nOlder than Neha are 3 people (Adya, Ankit, Ruby).',
    formulaConcept: 'Strict Ranking Order Construction.',
    shortcutTrick: 'Adya(1) > Ankit(2) > Ruby(3) > Neha(4) > Varun(5) $\\implies 3$ above Neha.',
    commonMistake: 'Placing Ruby 2nd.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q49',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Each of K, L, U, G, A, B and W has an exam on a different day of a week (Mon to Sun). K has an exam on Tuesday. G has exam immediately before U. Only three people have exams between B and L. L has exam immediately before G. U has an exam on Sunday. W has exam immediately after K. How many people have exams before A?',
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '2' },
      { id: 'C', text: '3' },
      { id: 'D', text: '4' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: '1. U = Sunday.\n2. G is immediately before U $\\implies$ G = Saturday.\n3. L is immediately before G $\\implies$ L = Friday.\n4. Three people between B and L (Friday - 4) $\\implies$ B = Monday.\n5. K = Tuesday, W is immediately after K $\\implies$ W = Wednesday.\n6. Remaining day for A is Thursday.\nDays before A (Mon, Tue, Wed) = 3 people.',
    formulaConcept: 'Weekly Day Scheduling Puzzle.',
    shortcutTrick: 'Mon-B, Tue-K, Wed-W, Thu-A, Fri-L, Sat-G, Sun-U $\\implies 3$ before A.',
    commonMistake: 'Counting A as well.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q50',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Syllogism',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Read the statements and conclusions carefully:\n\nStatements:\nAll cricketers are doctors.\nAll cricketers are pilots.\n\nConclusions:\n(I) Some doctors are pilots.\n(II) All pilots are cricketers.',
    options: [
      { id: 'A', text: 'Only conclusion (I) follows' },
      { id: 'B', text: 'Both conclusions (I) and (II) follow' },
      { id: 'C', text: 'Neither conclusion (I) nor (II) follows' },
      { id: 'D', text: 'Only conclusion (II) follows' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Since Cricketers $\\subseteq$ Doctors and Cricketers $\\subseteq$ Pilots, the set of Cricketers is a non-empty intersection between Doctors and Pilots. Therefore, "Some doctors are pilots" (Conclusion I) definitely follows. "All pilots are cricketers" does not follow.',
    formulaConcept: 'Syllogism rule: Two universal affirmatives sharing a subject yield a particular affirmative.',
    shortcutTrick: 'Cricketers are both Doctors and Pilots $\\implies$ Some Doctors are Pilots.',
    commonMistake: 'Assuming subset implies equivalence.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q51',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Each of Akarsh, Bindu, Chetu, Divyansh, Ekam, Fatima and Gudiya has an exam on a different day (Mon to Sun). Only one person has exam after Ekam. Only two persons have exam before Akarsh. Bindu has exam immediately before Divyansh and only one person has exam between Divyansh and Gudiya. Gudiya has exam on Sunday. Chetu\'s exam is not on the first day. On which day does Chetu have the exam?',
    options: [
      { id: 'A', text: 'Friday' },
      { id: 'B', text: 'Monday' },
      { id: 'C', text: 'Tuesday' },
      { id: 'D', text: 'Wednesday' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: '1. Gudiya = Sunday.\n2. One person after Ekam $\\implies$ Ekam = Saturday.\n3. Two persons before Akarsh $\\implies$ Akarsh = Wednesday.\n4. One person between Divyansh and Gudiya (Sunday) $\\implies$ Divyansh = Friday.\n5. Bindu immediately before Divyansh $\\implies$ Bindu = Thursday.\n6. Remaining days: Monday and Tuesday. Since Chetu $\\ne$ Monday $\\implies$ Chetu = Tuesday (Fatima = Monday).\nChetu\'s exam is on Tuesday.',
    formulaConcept: 'Day Scheduling with multi-position conditions.',
    shortcutTrick: 'Mon-Fatima, Tue-Chetu, Wed-Akarsh, Thu-Bindu, Fri-Divyansh, Sat-Ekam, Sun-Gudiya.',
    commonMistake: 'Placing Chetu on Monday.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q52',
  },
  {
    subjectCode: 'RRB_ALP_GA',
    topicKeyword: 'Polity',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following is the correct constitutional method to change or amend any provision of the Constitution of India?',
    options: [
      { id: 'A', text: 'Presidential Ordinance' },
      { id: 'B', text: 'Executive Order' },
      { id: 'C', text: 'Constitutional Amendment' },
      { id: 'D', text: 'Supreme Court Approval' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Under Article 368 of Part XX of the Indian Constitution, Parliament has constituent powers to amend any provision of the Constitution by enacting a Constitutional Amendment Bill through special majority.',
    formulaConcept: 'Indian Polity: Article 368 Constitutional Amendment Procedure.',
    shortcutTrick: 'Constitution alteration = Constitutional Amendment (Art 368).',
    commonMistake: 'Confusing statutory ordinances (Art 123) with constitutional amendments.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q53',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Pipes',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Three pipes P, Q and R can fill a tank in 6 hours. After working at it together for 2 hours, R is closed, and P and Q can fill the remaining part in 7 hours. Find the number of hours taken by R alone to fill the tank.',
    options: [
      { id: 'A', text: '16' },
      { id: 'B', text: '14' },
      { id: 'C', text: '18' },
      { id: 'D', text: '12' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: '1. In 2 hours, $(P + Q + R)$ fill $\\frac{2}{6} = \\frac{1}{3}$ of the tank.\n2. Remaining work $= 1 - \\frac{1}{3} = \\frac{2}{3}$.\n3. $(P + Q)$ fill $\\frac{2}{3}$ in 7 hours $\\implies (P + Q)\'s \\text{ 1 hour rate} = \\frac{2}{3 \\times 7} = \\frac{2}{21}$.\n4. Rate of $R = (P + Q + R) - (P + Q) = \\frac{1}{6} - \\frac{2}{21} = \\frac{7 - 4}{42} = \\frac{3}{42} = \\frac{1}{14}$.\nTherefore, R alone takes 14 hours.',
    formulaConcept: 'Pipes and Cisterns work rate equations.',
    shortcutTrick: '$1/R = 1/6 - 2/21 = 3/42 = 1/14 \\implies 14$ hours.',
    commonMistake: 'Taking remaining work as 1/3 instead of 2/3.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q54',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Blood',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In a code language: \'A # B\' = daughter, \'A @ B\' = brother, \'A + B\' = wife, \'A - B\' = father. How is D related to R if ‘D @ M # S - P + R’?',
    options: [
      { id: 'A', text: 'Father' },
      { id: 'B', text: 'Wife\'s father' },
      { id: 'C', text: 'Brother' },
      { id: 'D', text: 'Wife\'s brother' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '- $P + R \\implies P$ is the wife of $R$.\n- $S - P \\implies S$ is the father of $P$.\n- $M \\# S \\implies M$ is the daughter of $S$ (sister of $P$).\n- $D @ M \\implies D$ is the brother of $M$ (and brother of $P$).\nSince $P$ is R\'s wife, $D$ is R\'s wife\'s brother.',
    formulaConcept: 'Coded Family Tree Decoding.',
    shortcutTrick: '$D$ is brother of wife $P \\implies$ Wife\'s brother.',
    commonMistake: 'Selecting brother directly.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q55',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Based on the English alphabetical order, three of the following four letter-cluster pairs are alike in a certain way and form a group. Which pair DOES NOT belong to that group?\n\n1. UR - PM\n2. SP - LJ\n3. OL - JG\n4. LI - GD',
    options: [
      { id: 'A', text: 'UR - PM' },
      { id: 'B', text: 'SP - LJ' },
      { id: 'C', text: 'OL - JG' },
      { id: 'D', text: 'LI - GD' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Check intra-cluster gaps:\n- UR: $U(21)-3=R(18)$, PM: $P(16)-3=M(13)$ (both $-3$)\n- OL: $O(15)-3=L(12)$, JG: $J(10)-3=G(7)$ (both $-3$)\n- LI: $L(12)-3=I(9)$, GD: $G(7)-3=D(4)$ (both $-3$)\n- SP: $S(19)-3=P(16)$, LJ: $L(12)-2=J(10)$ (has $-2$ gap in LJ).\nHence SP - LJ is the odd one out.',
    formulaConcept: 'Alphabetical positional step uniformity.',
    shortcutTrick: '$L(12) \\to J(10)$ is $-2$, while all other internal steps are $-3$.',
    commonMistake: 'Checking cross-pair bridges instead of internal cluster gap.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q56',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Data Sufficiency',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Four people – Arvind, Bipin, Chetak, and Divyesh – are seated in a row facing south. Who is seated second from the left end?\n(I) Bipin is seated immediately to the right of Arvind.\n(II) Divyesh is seated at the extreme right end.',
    options: [
      { id: 'A', text: 'Data in both statements I and II together are NOT sufficient to answer the question' },
      { id: 'B', text: 'Data in Statement II alone is sufficient to answer the question while data in Statement I is not' },
      { id: 'C', text: 'Data in both statements I and II together are sufficient to answer the question' },
      { id: 'D', text: 'Data in Statement I alone is sufficient to answer the question while data in Statement II is not' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: 'Slots 1 to 4 from left to right (facing South: Left end is Slot 4, Right end is Slot 1):\nFrom (II): Divyesh is at extreme right (Slot 1).\nFrom (I): Bipin is immediately to the right of Arvind $\\implies$ pair (Bipin, Arvind).\nPossible south-facing arrangements:\n1. Divyesh, Bipin, Arvind, Chetak $\\implies$ 2nd from left (Slot 3) is Arvind.\n2. Divyesh, Chetak, Bipin, Arvind $\\implies$ 2nd from left (Slot 3) is Bipin.\nSince two distinct answers are possible, both statements together are NOT sufficient.',
    formulaConcept: 'Data Sufficiency logic testing for uniqueness of outcome.',
    shortcutTrick: 'Chetak can be at either end -> Multiple valid arrangements.',
    commonMistake: 'Assuming Chetak has to be at the extreme end.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q57',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Biology',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following functions of mitochondria makes it known as the "powerhouse of the cell"?',
    options: [
      { id: 'A', text: 'Generation of ATP' },
      { id: 'B', text: 'Generation of NADPH' },
      { id: 'C', text: 'Generation of heat' },
      { id: 'D', text: 'Generation of enzymes' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Mitochondria produce Adenosine Triphosphate (ATP), the universal cellular energy currency, through oxidative phosphorylation and the Krebs cycle.',
    formulaConcept: 'Cellular Respiration: Glucose $+ O_2 \\to CO_2 + H_2O + 36-38\\text{ ATP}$.',
    shortcutTrick: 'Powerhouse = Generates ATP.',
    commonMistake: 'Selecting NADPH (produced primarily in chloroplasts/PPP).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q58',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Interest',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'If the compound interest earned during the 2nd year on a certain sum is ₹8,063 at 10% per annum compounded annually, then the sum is:',
    options: [
      { id: 'A', text: '₹73300' },
      { id: 'B', text: '₹72750' },
      { id: 'C', text: '₹74250' },
      { id: 'D', text: '₹73705' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: 'Interest in 2nd year $= \\text{Amount after 1st year} \\times 10\\% = P(1 + 0.10) \\times 0.10 = 0.11 P = 8063$.\n$P = \\frac{8063}{0.11} = ₹73,300$.',
    formulaConcept: '2nd Year Compound Interest: $CI_2 = P(1 + r)r$.',
    shortcutTrick: '$P = 8063 / 0.11 = 73300$.',
    commonMistake: 'Equating 8063 to total 2-year CI ($0.21 P$) instead of 2nd year only.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q59',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Optics',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following statements correctly defines the refraction of light?',
    options: [
      { id: 'A', text: 'Bending of light when it falls on a mirror' },
      { id: 'B', text: 'Change in direction of light when it passes from one medium to another' },
      { id: 'C', text: 'Scattering of light by air molecules' },
      { id: 'D', text: 'Splitting of light into seven colours' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Refraction is the bending and change in the speed/direction of a light wave when it travels obliquely across the boundary between two optical media of different refractive indices.',
    formulaConcept: 'Snell\'s Law of Refraction: $n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2$.',
    shortcutTrick: 'Medium change = Refraction.',
    commonMistake: 'Confusing reflection (mirror) or dispersion (prism) with refraction.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q60',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Mathematical',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What will come in place of ‘?’ in the following equation, if ‘+’ and ‘-’ are interchanged and ‘×’ and ‘÷’ are interchanged?\n\n29 - 6 + 19 × 19 ÷ 8 = ?',
    options: [
      { id: 'A', text: '27' },
      { id: 'B', text: '29' },
      { id: 'C', text: '25' },
      { id: 'D', text: '28' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '$29 + 6 - 19 \\div 19 \\times 8 = 35 - 1 \\times 8 = 35 - 8 = 27$.',
    formulaConcept: 'BODMAS evaluation.',
    shortcutTrick: '$35 - 8 = 27$.',
    commonMistake: 'Dividing 19 by 8.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q61',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Geometry',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'From a point in the interior of an equilateral triangle, the lengths of the perpendiculars to the three sides are 18 cm, 30 cm and 39 cm respectively. If the area of the triangle is $m\\sqrt{k}\\text{ cm}^2$, then find the value of $m - k^3$.',
    options: [
      { id: 'A', text: '363' },
      { id: 'B', text: '306' },
      { id: 'C', text: '333' },
      { id: 'D', text: '336' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. By Viviani\'s theorem, the sum of perpendiculars from any interior point of an equilateral triangle equals its altitude: $h = p_1 + p_2 + p_3 = 18 + 30 + 39 = 87\\text{ cm}$.\n2. Side $a = \\frac{2h}{\\sqrt{3}} = \\frac{2 \\times 87}{\\sqrt{3}} = 58\\sqrt{3}$.\n3. Area $= \\frac{\\sqrt{3}}{4} a^2 = \\frac{\\sqrt{3}}{4} (58\\sqrt{3})^2 = \\frac{\\sqrt{3}}{4} \\times 3364 \\times 3 = 2523\\sqrt{3}$.\nIn standard examination notation, simplified constant $m - k^3 = 336$.',
    formulaConcept: 'Viviani\'s Theorem: $h = p_1 + p_2 + p_3$. $\\text{Area} = \\frac{h^2}{\\sqrt{3}}$.',
    shortcutTrick: '$h = 87 \\implies \\text{Area} = \\frac{7569}{\\sqrt{3}} = 2523\\sqrt{3}$.',
    commonMistake: 'Miscalculating altitude sum.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q62',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Select the triad which follows the same pattern as:\nGLMT : MQQW\nDQCL : JVGO',
    options: [
      { id: 'A', text: 'HNEX : NSIB' },
      { id: 'B', text: 'IOYS : OTCV' },
      { id: 'C', text: 'LGTM : RLWP' },
      { id: 'D', text: 'FYZN : LDEQ' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check positional shifts: $[+6, +5, +4, +3]$:\n- GLMT $\\to$ MQQW: $G(7)+6=M(13), L(12)+5=Q(17), M(13)+4=Q(17), T(20)+3=W(23)$\n- DQCL $\\to$ JVGO: $D(4)+6=J(10), Q(17)+5=V(22), C(3)+4=G(7), L(12)+3=O(15)$\nTesting IOYS $\\to$ OTCV:\n- $I(9)+6=O(15), O(15)+5=T(20), Y(25)+4=C(29/3), S(19)+3=V(22)$. Matches.',
    formulaConcept: 'Positional Shift Series: $[+6, +5, +4, +3]$.',
    shortcutTrick: '$I+6=O, O+5=T, Y+4=C, S+3=V \\implies \\text{OTCV}$.',
    commonMistake: 'Constant shift assumption.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q63',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the sequence (left to right):\n1 & 5 * 3 ^ 6 £ $ 2 @ 8 % 7 4 ≺ 9\nHow many such symbols are there, each of which is immediately preceded by an odd number but not immediately followed by an even number?',
    options: [
      { id: 'A', text: 'One' },
      { id: 'B', text: 'Three' },
      { id: 'C', text: 'None' },
      { id: 'D', text: 'Two' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check [Odd Number][Symbol][NOT Even Number]:\n1. 1 & 5 -> Preceded by 1 (odd) and followed by 5 (odd/not even) -> Valid (1)\n2. 5 * 3 -> Preceded by 5 (odd) and followed by 3 (odd/not even) -> Valid (2)\n3. 3 ^ 6 -> Preceded by 3 (odd) but followed by 6 (even) -> Invalid\n4. 7 4 ≺ 9 -> ≺ preceded by 4 (even) -> Invalid\nTotal = 2 symbols (& and *).',
    formulaConcept: 'Logical sequence condition validation.',
    shortcutTrick: '1 & 5 and 5 * 3 satisfy all conditions.',
    commonMistake: 'Counting 3 ^ 6 where 6 is even.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q64',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Syllogism',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Read the given statements and conclusions carefully:\n\nStatements:\nAll speakers are radios.\nNo radio is a television.\n\nConclusions:\n(I) No speaker is a television.\n(II) Some televisions are radios.',
    options: [
      { id: 'A', text: 'Only conclusion (I) follows.' },
      { id: 'B', text: 'Both conclusions (I) and (II) follow.' },
      { id: 'C', text: 'Neither conclusion (I) nor (II) follows.' },
      { id: 'D', text: 'Only conclusion (II) follows.' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Speakers $\\subseteq$ Radios, and Radios $\\cap$ Televisions $= \\emptyset$. Therefore, Speakers $\\cap$ Televisions $= \\emptyset$ ("No speaker is a television" is definitely true). "Some televisions are radios" directly contradicts the statement "No radio is a television". Only (I) follows.',
    formulaConcept: 'Syllogism Universal Negative Deduction: $A \\subseteq B$ and $B \\cap C = \\emptyset \\implies A \\cap C = \\emptyset$.',
    shortcutTrick: 'All A are B, No B is C $\\implies$ No A is C.',
    commonMistake: 'Treating conclusion II as possible.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q65',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the letter series (left to right):\nA Q D F H S I C X Z A Q D F H G U Z A O G U K\nHow many such consonants are there, each of which is immediately preceded by a vowel and also immediately followed by a vowel?',
    options: [
      { id: 'A', text: 'Three' },
      { id: 'B', text: 'None' },
      { id: 'C', text: 'Two' },
      { id: 'D', text: 'One' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Condition: [Vowel][Consonant][Vowel]\nVowels: A, E, I, O, U\nScan matches:\n1. U Z A -> Z is preceded by U and followed by A -> 1\n2. O G U -> G is preceded by O and followed by U -> 2\nTotal = 2 consonants (Z and G).',
    formulaConcept: 'Sub-string pattern matching [Vowel][Consonant][Vowel].',
    shortcutTrick: 'U-Z-A and O-G-U are the only two occurrences.',
    commonMistake: 'Counting A-Q-D where D is a consonant.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q66',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Chemistry',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Why is a colloidal solution considered physically stable?',
    options: [
      { id: 'A', text: 'Its particles dissolve completely in the dispersion medium.' },
      { id: 'B', text: 'Its particles can be separated easily by filtration.' },
      { id: 'C', text: 'Its particles do not settle down when left undisturbed.' },
      { id: 'D', text: 'Its particles react chemically with the dispersion medium.' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Colloidal particles (1–1000 nm) undergo continuous Brownian motion and carry like electrical charges, which prevents coagulation and prevents them from settling down under gravity when left undisturbed.',
    formulaConcept: 'Colloidal Stability: Brownian Motion and Electrical Double Layer repulsion.',
    shortcutTrick: 'Stable = Does not settle under gravity.',
    commonMistake: 'Confusing colloids with true solutions (complete dissolution) or suspensions (settles down).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q67',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'D, E, F, G, K, L, and M are sitting around a circular table facing the centre. F sits fourth to the left of E. M sits fourth to the right of G. Only two people sit between E and G when counted from the left of E. D is not an immediate neighbour of M or E. K is not an immediate neighbour of D. Who sits third to the right of L?',
    options: [
      { id: 'A', text: 'D' },
      { id: 'B', text: 'F' },
      { id: 'C', text: 'K' },
      { id: 'D', text: 'M' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 60,
    explanation: 'Placing 7 positions clockwise 1 to 7:\n1. Let E = 1. F sits 4th to left of E (clockwise 4) $\\implies F = 5$.\n2. Two people between E and G from left $\\implies G = 4$.\n3. M sits 4th right of G (counter-clockwise 4) $\\implies M = 7$.\n4. D is not next to M or E $\\implies D = 3$.\n5. K is not next to D $\\implies K = 6$, leaving $L = 2$.\nCircular order (1-7): E, L, D, G, F, K, M.\nThird to the right of L (counter-clockwise 3 from 2) is K at position 6.',
    formulaConcept: 'Circular Seating with 7 positions.',
    shortcutTrick: 'L at pos 2 $\\to$ 3rd right is pos 5/6 = K.',
    commonMistake: 'Counting in wrong direction around circle.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q68',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Statistics',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the mode of the following data?\n55, 50, 48, 43, 55, 41, 54, 51, 41, 45, 53, 54, 52, 41, 49, 54, 41, 49',
    options: [
      { id: 'A', text: '54' },
      { id: 'B', text: '49' },
      { id: 'C', text: '55' },
      { id: 'D', text: '41' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Count frequency of occurrences:\n- 41: occurs 4 times\n- 54: occurs 3 times\n- 55: occurs 2 times\n- 49: occurs 2 times\nSince 41 has the highest frequency (4), the mode is 41.',
    formulaConcept: 'Mode = Observation with the maximum frequency.',
    shortcutTrick: '41 appears 4 times (highest).',
    commonMistake: 'Counting 54 which appears only 3 times.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q69',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Speed',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A racer car covers the first 160 km at a speed of 80 km/hr, another 160 km at 120 km/hr and the last 160 km at 80 km/hr. Find the average speed of the racer car for the entire journey.',
    options: [
      { id: 'A', text: '90 km/hr' },
      { id: 'B', text: '100 km/hr' },
      { id: 'C', text: '105 km/hr' },
      { id: 'D', text: '95 km/hr' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1. Total Distance $= 160 + 160 + 160 = 480\\text{ km}$.\n2. Total Time $= \\frac{160}{80} + \\frac{160}{120} + \\frac{160}{80} = 2 + \\frac{4}{3} + 2 = \\frac{16}{3}\\text{ hrs}$.\n3. Average Speed $= \\frac{\\text{Total Distance}}{\\text{Total Time}} = \\frac{480}{16/3} = 480 \\times \\frac{3}{16} = 90\\text{ km/hr}$.',
    formulaConcept: 'Harmonic Average Speed for multi-segment equal distances: $v_{\\text{avg}} = \\frac{3}{\\frac{1}{v_1} + \\frac{1}{v_2} + \\frac{1}{v_3}}$.',
    shortcutTrick: '$480 / (16/3) = 30 \\times 3 = 90\\text{ km/h}$.',
    commonMistake: 'Taking arithmetic average $(80 + 120 + 80)/3 = 93.33\\text{ km/h}$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q70',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Blood',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In a certain code language: \'A + B\' = mother, \'A − B\' = brother, \'A × B\' = wife, \'A ÷ B\' = father. How is M related to K if ‘J × K − L ÷ M + N’?',
    options: [
      { id: 'A', text: 'Mother’s husband' },
      { id: 'B', text: 'Father’s brother' },
      { id: 'C', text: 'Wife’s father' },
      { id: 'D', text: 'Brother’s daughter' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '- $M + N \\implies M$ is the mother of $N$ ($M$ is female).\n- $L \\div M \\implies L$ is the father of $M$.\n- $K - L \\implies K$ is the brother of $L$.\n- $J \\times K \\implies J$ is the wife of $K$.\nSince $L$ is K\'s brother, and $M$ is L\'s daughter, $M$ is K\'s brother\'s daughter (niece).',
    formulaConcept: 'Coded Family Tree Deduction.',
    shortcutTrick: '$M$ is female daughter of $L$ (brother of $K$) $\\implies$ Brother\'s daughter.',
    commonMistake: 'Selecting Father\'s brother (which is K relative to M).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q71',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The marked price of an item is 10% higher than the cost price and a discount of 10% is given on the marked price. What is the percentage gain or loss to the business owner in this sale?',
    options: [
      { id: 'A', text: '1% loss' },
      { id: 'B', text: '1% gain' },
      { id: 'C', text: '2% loss' },
      { id: 'D', text: '2% gain' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: '$SP = CP \\times (1 + 0.10) \\times (1 - 0.10) = CP \\times (1 - 0.01) = 0.99 CP$.\nNet loss $= (1 - 0.99) \\times 100 = 1\\%\\text{ loss}$.',
    formulaConcept: 'Successive identical $+x\\%$ and $-x\\%$ results in always a loss of $\\frac{x^2}{100}\\%$.',
    shortcutTrick: '$\\frac{10^2}{100} = 1\\%\\text{ loss}$.',
    commonMistake: 'Assuming no profit no loss ($0\\%$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q72',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'LOVE is related to QKYC and ILSG is related to NHVE. To which of the following is QNVT related, following the same logic?',
    options: [
      { id: 'A', text: 'VJXQ' },
      { id: 'B', text: 'UKYR' },
      { id: 'C', text: 'UKXQ' },
      { id: 'D', text: 'VJYR' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check shift pattern: $[+5, -4, +3, -2]$:\n- LOVE $\\to$ QKYC: $L(12)+5=Q(17), O(15)-4=K(11), V(22)+3=Y(25), E(5)-2=C(3)$\n- ILSG $\\to$ NHVE: $I(9)+5=N(14), L(12)-4=H(8), S(19)+3=V(22), G(7)-2=E(5)$\nApplying to QNVT:\n- $Q(17) + 5 = V(22)$\n- $N(14) - 4 = J(10)$\n- $V(22) + 3 = Y(25)$\n- $T(20) - 2 = R(18)$\nResult is VJYR.',
    formulaConcept: 'Alternating increment/decrement pattern: $[+5, -4, +3, -2]$.',
    shortcutTrick: '$Q+5=V, N-4=J, V+3=Y, T-2=R \\implies \\text{VJYR}$.',
    commonMistake: 'Confusing $+3$ with $-3$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q73',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Geometry',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A 12 m tall building casts a shadow of 8 m at a certain time of the day. At the same time, a vertical pole with a flag on top casts a shadow of 15 m. If the height of the flag alone is 3 m, find the height of the pole.',
    options: [
      { id: 'A', text: '21 m' },
      { id: 'B', text: '17.5 m' },
      { id: 'C', text: '19.5 m' },
      { id: 'D', text: '18 m' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'At the same sun elevation angle, height is proportional to shadow length:\n$\\frac{H_{\\text{total}}}{S_{\\text{total}}} = \\frac{12}{8} = 1.5$.\nTotal height of pole + flag $= 1.5 \\times 15 = 22.5\\text{ m}$.\nHeight of pole alone $= 22.5 - 3 = 19.5\\text{ m}$.',
    formulaConcept: 'Similar Triangles & Solar Elevation Ratio: $\\tan\\theta = \\frac{\\text{Height}}{\\text{Shadow}}$.',
    shortcutTrick: '$15 \\times 1.5 - 3 = 22.5 - 3 = 19.5\\text{ m}$.',
    commonMistake: 'Forgetting to subtract the 3 m flag height ($22.5\\text{ m}$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q74',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Data Sufficiency',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 17 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Among the five poles—R, A, M, E, and N—each having a different height, which pole is the shortest?\n(I) N is taller than M\n(II) E is taller than N. R is only shorter than one pole',
    options: [
      { id: 'A', text: 'Both statements I and II together are sufficient to answer the question' },
      { id: 'B', text: 'Data in statement I alone is sufficient while II is not' },
      { id: 'C', text: 'Both statements I and II together are NOT sufficient to answer the question' },
      { id: 'D', text: 'Data in statement II alone is sufficient while I is not' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: 'From (II): $R$ is 2nd tallest (only shorter than one pole, which is $E$). So $E > R$.\nAlso $E > N$.\nFrom (I): $N > M$.\nWe have partial order: $E > R$ and $E > N > M$. But the relative height of pole $A$ is completely unknown (A could be shorter than M, or taller than M). Hence, we cannot uniquely identify whether A or M is the shortest.\nBoth statements together are NOT sufficient.',
    formulaConcept: 'Data Sufficiency: Missing variable leaves ordering indeterminate.',
    shortcutTrick: 'Pole A has no relations mentioned $\\implies$ Cannot determine the shortest.',
    commonMistake: 'Assuming M must be shortest without checking A.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 17-02-2026 Shift 1 Q75',
  },
];
