import { RawQuestionData } from './gateQuestions.js';

export const rrbAlp2026Feb16Shift1Questions: RawQuestionData[] = [
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of ? in the given series?\n\n39 51 68 90 117 ?',
    options: [
      { id: 'A', text: '150' },
      { id: 'B', text: '149' },
      { id: 'C', text: '148' },
      { id: 'D', text: '151' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Second-order difference pattern (differences increase by $+5$):\n$51 - 39 = +12$\n$68 - 51 = +17$\n$90 - 68 = +22$\n$117 - 90 = +27$\nNext difference $= 27 + 5 = +32$.\nNext number $= 117 + 32 = 149$.',
    formulaConcept: 'Series with arithmetic differences: $d_k = 12 + 5(k-1)$.',
    shortcutTrick: '$117 + 32 = 149$.',
    commonMistake: 'Adding 27 again instead of incrementing difference.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q1',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'HEVO is related to WTKD and PMDW is related to EBSL. To which of the given options is IFWP related, following the same logic?',
    options: [
      { id: 'A', text: 'XLOE' },
      { id: 'B', text: 'XEDS' },
      { id: 'C', text: 'XULE' },
      { id: 'D', text: 'XIOP' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check letter shift ($+15$ or $-11$ mod 26):\n- HEVO $\\to$ WTKD: $H(8)+15=W(23), E(5)+15=T(20), V(22)+15=K(37/11), O(15)+15=D(30/4)$\n- PMDW $\\to$ EBSL: $P(16)+15=E(31/5), M(13)+15=B(28/2), D(4)+15=S(19), W(23)+15=L(38/12)$\nApplying to IFWP:\n- $I(9) + 15 = X(24)$\n- $F(6) + 15 = U(21)$\n- $W(23) + 15 = L(38/12)$\n- $P(16) + 15 = E(31/5)$\nResult is XULE.',
    formulaConcept: 'Uniform $+15$ Modulo 26 Alphabetic Shift.',
    shortcutTrick: '$I+15=X, F+15=U, W+15=L, P+15=E \\implies \\text{XULE}$.',
    commonMistake: 'Miscalculating $6 + 15 = 21 = U$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q2',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Biology',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following adverse effects of smoking is observed on the respiratory system?',
    options: [
      { id: 'A', text: 'Promotion of cilia in upper respiratory tract' },
      { id: 'B', text: 'Destruction of cilia in upper respiratory tract' },
      { id: 'C', text: 'Promotion of cilia in lower respiratory tract' },
      { id: 'D', text: 'Destruction of cilia in lower respiratory tract' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Tobacco smoke contains toxic chemicals and tar that paralyze and destroy the protective ciliated epithelial cells in the upper respiratory tract (trachea and bronchi), preventing the clearance of mucus, dust, and pathogens (smoker\'s cough).',
    formulaConcept: 'Human Respiratory System & Toxicological Pathology.',
    shortcutTrick: 'Smoking destroys cilia in the upper respiratory tract.',
    commonMistake: 'Selecting lower respiratory tract (where alveoli lack cilia).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q3',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a code language, \'DEAR\' is coded as 16 and \'ANGEL\' is coded as 25. How will \'BEHAVIOR\' be coded in the same language?',
    options: [
      { id: 'A', text: '64' },
      { id: 'B', text: '36' },
      { id: 'C', text: '18' },
      { id: 'D', text: '49' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Pattern: $(\\text{Number of letters in the word})^2$.\n- DEAR has 4 letters $\\implies 4^2 = 16$.\n- ANGEL has 5 letters $\\implies 5^2 = 25$.\n- BEHAVIOR has 8 letters $\\implies 8^2 = 64$.',
    formulaConcept: 'Word Length Squared Pattern: $\\text{Code} = L^2$.',
    shortcutTrick: '8 letters $\\implies 8^2 = 64$.',
    commonMistake: 'Adding letter place values instead of counting letters.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q4',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Algebra',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'The sum of the present ages of Bunty and Bubbly is 24 years. After 2 years from now, Bunty\'s age will be three times that of Bubbly\'s age. Bunty\'s present age (in years) is:',
    options: [
      { id: 'A', text: '28' },
      { id: 'B', text: '17' },
      { id: 'C', text: '22' },
      { id: 'D', text: '19' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Let present ages be Bunty = $B$ and Bubbly = $b$.\n1. $B + b = 24 \\implies B = 24 - b$.\n2. After 2 years: $(B + 2) = 3(b + 2)$.\nSubstitute $B = 24 - b$:\n$(24 - b + 2) = 3b + 6 \\implies 26 - b = 3b + 6 \\implies 4b = 20 \\implies b = 5$.\nBunty\'s present age $B = 24 - 5 = 19$ years.',
    formulaConcept: 'Linear system of age equations.',
    shortcutTrick: 'In 2 years, total age $= 24 + 4 = 28$. Ratio $= 3:1 \\implies$ Bubbly $= 28/4 = 7$ (now 5), Bunty $= 21$ (now 19).',
    commonMistake: 'Finding Bubbly\'s age (5) or future age (21).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q5',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Statistics',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A student\'s marks were incorrectly entered as 84 instead of 94. Due to this, the average marks of the class got decreased by 5/4. What is the number of students in the class?',
    options: [
      { id: 'A', text: '4' },
      { id: 'B', text: '8' },
      { id: 'C', text: '15' },
      { id: 'D', text: '17' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Mark deficit $= 94 - 84 = 10$.\n$\\frac{\\text{Deficit}}{n} = \\frac{5}{4} \\implies \\frac{10}{n} = \\frac{5}{4} \\implies n = \\frac{10 \\times 4}{5} = 8$.',
    formulaConcept: 'Average Correction Formula: $n = \\frac{\\Delta \\text{Total}}{\\Delta \\text{Average}}$.',
    shortcutTrick: '$n = 10 \\times \\frac{4}{5} = 8$.',
    commonMistake: 'Flipping numerator and denominator.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q6',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Speed',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A boat running downstream covers a distance of 18 km in 3 hours while it covers the same distance upstream in 9 hours. The speed of the boat in still water is:',
    options: [
      { id: 'A', text: '6 km/hr' },
      { id: 'B', text: '4 km/hr' },
      { id: 'C', text: '2 km/hr' },
      { id: 'D', text: '8 km/hr' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Downstream speed $v_d = \\frac{18}{3} = 6\\text{ km/hr}$.\nUpstream speed $v_u = \\frac{18}{9} = 2\\text{ km/hr}$.\nSpeed of boat in still water $= \\frac{v_d + v_u}{2} = \\frac{6 + 2}{2} = 4\\text{ km/hr}$.',
    formulaConcept: 'Boats and Streams: $u = \\frac{v_d + v_u}{2}$, $v = \\frac{v_d - v_u}{2}$.',
    shortcutTrick: '$(6 + 2) / 2 = 4\\text{ km/h}$.',
    commonMistake: 'Finding stream speed $(6-2)/2 = 2\\text{ km/h}$ instead of boat speed.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q7',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A, T, Z, R, Y and L are sitting around a circular table facing the centre. T sits second to the left of L. Only two people sit between Z and L when counted from the left of Z. A sits to the immediate left of Z and to the immediate right of R. Who is sitting second to the left of R?',
    options: [
      { id: 'A', text: 'Y' },
      { id: 'B', text: 'Z' },
      { id: 'C', text: 'L' },
      { id: 'D', text: 'T' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: 'Circular layout of 6 seats (clockwise 1 to 6):\n1. Place L at 1 $\\implies$ T (2nd left of L, clockwise 2) is at 3.\n2. Two people between Z and L from left of Z $\\implies$ Z is at 4 (opposite L).\n3. A is immediate left of Z (clockwise 1 from 4) $\\implies$ A is at 5.\n4. A is immediate right of R $\\implies$ R is at 6.\n5. Remaining position 2 is occupied by Y.\nCircular order (1-6): L, Y, T, Z, A, R.\nSecond to the left of R (clockwise 2 from 6) is Y at position 2.',
    formulaConcept: 'Circular Seating Arrangement with 6 persons.',
    shortcutTrick: 'Positions: R(6) -> L(1) -> Y(2). Second to left of R is Y.',
    commonMistake: 'Confusing clockwise/counter-clockwise when facing inward.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q8',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Blood',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In a code language: \'A + B\' = brother, \'A * B\' = B is father of A, \'A / B\' = sister, \'A - B\' = mother. How is T related to Q if \'Q + L * Z + T + G\'?',
    options: [
      { id: 'A', text: 'Sister' },
      { id: 'B', text: 'Sister\'s son' },
      { id: 'C', text: 'Mother' },
      { id: 'D', text: 'Brother\'s son' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '- $Q + L \\implies Q$ is brother of $L$.\n- $L * Z \\implies Z$ is father of $L$ (and father of $Q$).\n- $Z + T \\implies Z$ is brother of $T$.\n- $T + G \\implies T$ is brother of $G$.\nSince $Z$ is brother of $T$, $T$ is paternal uncle of $Q$, meaning $Q$ is brother\'s son (nephew) of $T$.',
    formulaConcept: 'Coded Family Tree Deduction.',
    shortcutTrick: '$Z$ is father of $Q$ and $Z$ is brother of $T \\implies T$ is uncle / $Q$ is brother\'s son.',
    commonMistake: 'Reversing relation direction.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q9',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of the question mark (?) in the given series?\n\nGKB IMF KOJ MQN ?',
    options: [
      { id: 'A', text: 'PSR' },
      { id: 'B', text: 'PTR' },
      { id: 'C', text: 'OSR' },
      { id: 'D', text: 'OSS' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '1st letter ($+2$): $G(7) \\to I(9) \\to K(11) \\to M(13) \\to O(15)$\n2nd letter ($+2$): $K(11) \\to M(13) \\to O(15) \\to Q(17) \\to S(19)$\n3rd letter ($+1, +2, +3$): $B(2) \\xrightarrow{+4} F(6) \\xrightarrow{+4} J(10) \\xrightarrow{+4} N(14) \\xrightarrow{+4} R(18)$.\nResult is OSR.',
    formulaConcept: 'Positional letter advancement: $[+2, +2, +4]$.',
    shortcutTrick: '$M+2=O, Q+2=S, N+4=R \\implies \\text{OSR}$.',
    commonMistake: 'Selecting OSS.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q10',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Optics',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If an object is placed between the centre of curvature (C) and the focus (F) of a concave mirror, what type of image will be formed?',
    options: [
      { id: 'A', text: 'Diminished, real, and inverted' },
      { id: 'B', text: 'Highly enlarged and virtual' },
      { id: 'C', text: 'Same size, real, and upright' },
      { id: 'D', text: 'Enlarged, real, and inverted' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'For a concave mirror, when an object is placed between C and F:\n- Position: Beyond C\n- Nature: Real and inverted\n- Size: Magnified / Enlarged.',
    formulaConcept: 'Mirror Formula & Ray Optics: Object between C & F forms real, inverted, magnified image beyond C.',
    shortcutTrick: 'Between C & F $\\implies$ Beyond C (Real, Inverted, Enlarged).',
    commonMistake: 'Selecting virtual (which occurs only when object is between F and Pole).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q11',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the sequence (left to right):\nT O © L L $ G £ L D V & & N * M @ J X © B K\nHow many such letters are there, each of which is immediately preceded by a letter and also immediately followed by a symbol?',
    options: [
      { id: 'A', text: '4' },
      { id: 'B', text: '3' },
      { id: 'C', text: '6' },
      { id: 'D', text: '5' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Condition: [Letter][Target Letter][Symbol]:\n1. T O © $\\implies$ O is preceded by T (Letter) and followed by © (Symbol) -> 1\n2. L L $ $\\implies$ L is preceded by L (Letter) and followed by $ (Symbol) -> 2\n3. D V & $\\implies$ V is preceded by D (Letter) and followed by & (Symbol) -> 3\n4. J X © $\\implies$ X is preceded by J (Letter) and followed by © (Symbol) -> 4\nTotal = 4 letters (O, L, V, X).',
    formulaConcept: 'String Pattern Matching.',
    shortcutTrick: 'TO©, LL$, DV&, JX© = 4 matching occurrences.',
    commonMistake: 'Counting *M@ where * is a symbol.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q12',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Work',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A, B and C together can complete a task in 20 days. A and B together can do it in 30 days, and B and C together can do it in 24 days. How long would B alone take to complete the entire work?',
    options: [
      { id: 'A', text: '48 days' },
      { id: 'B', text: '40 days' },
      { id: 'C', text: '45 days' },
      { id: 'D', text: '54 days' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '1. $(A + B + C) = \\frac{1}{20}$.\n2. $C = (A + B + C) - (A + B) = \\frac{1}{20} - \\frac{1}{30} = \\frac{3 - 2}{60} = \\frac{1}{60}$.\n3. $B = (B + C) - C = \\frac{1}{24} - \\frac{1}{60} = \\frac{5 - 2}{120} = \\frac{3}{120} = \\frac{1}{40}$.\nTherefore, B alone takes 40 days.',
    formulaConcept: 'Work-Time Subtraction equations.',
    shortcutTrick: '$C = 1/60 \\implies B = 1/24 - 1/60 = 1/40 \\implies 40$ days.',
    commonMistake: 'Adding $A+B$ and $B+C$ without subtracting $(A+B+C)$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q13',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Each of A, B, C, D, S, T and U has an exam on a different day (Mon to Sun). Only two people have their exams before D. Only one person has the exam after U. Only three people have their exams between D and B. Only one person has the exam between C and S. A has the exam immediately before C. How many people have exams between T and C?',
    options: [
      { id: 'A', text: 'One' },
      { id: 'B', text: 'Three' },
      { id: 'C', text: 'Four' },
      { id: 'D', text: 'Two' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: '1. Two people before D $\\implies$ D = Wednesday (Day 3).\n2. One person after U $\\implies$ U = Saturday (Day 6).\n3. Three people between D (Wed) and B $\\implies$ B = Sunday (Day 7).\n4. A is immediately before C (pair A-C).\n5. One person between C and S.\nAvailable slots: Mon, Tue, Thu, Fri.\nSetting A = Monday, C = Tuesday $\\implies$ S = Thursday (1 person between C and S, which is D on Wed).\n6. T = Friday.\nSchedule: Mon-A, Tue-C, Wed-D, Thu-S, Fri-T, Sat-U, Sun-B.\nBetween T (Fri) and C (Tue), there are 2 people (D on Wed, S on Thu).',
    formulaConcept: 'Weekly Day Scheduling Constraints.',
    shortcutTrick: 'Between Tue (C) and Fri (T) is Wed and Thu $\\implies 2$ people.',
    commonMistake: 'Placing A-C on Thu-Fri.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q14',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A, B, C, D, E, F and G are sitting around a circular table facing the centre. Only three people sit between A and C when counted from the left of A. Only three people sit between B and G when counted from the right of G. F sits to the immediate right of B. D is an immediate neighbour of G as well as C. How many people sit between C and F when counted from the left of F?',
    options: [
      { id: 'A', text: '4' },
      { id: 'B', text: '3' },
      { id: 'C', text: '2' },
      { id: 'D', text: '1' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 55,
    explanation: '7-seat circular configuration (clockwise 1 to 7):\n1. In a 7-person circle, "3 people between X and Y" means X and Y are diametrically opposite in a 7-seat layout (separated by 3 on one side, 2 on other).\n2. D is between G and C $\\implies$ order G-D-C.\n3. F is immediate right of B.\nComplete circular arrangement: A, E, B, F, G, D, C.\nFrom the left of F (clockwise): G, D, C $\\implies$ 2 people (G and D) sit between F and C.',
    formulaConcept: 'Circular Seating Logic for 7 persons.',
    shortcutTrick: 'F is next to G, then D, then C $\\implies$ G and D are between them (2 people).',
    commonMistake: 'Counting in counter-clockwise direction instead of left (clockwise).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q15',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Speed',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A ball is dropped from a height and falls freely for 2 seconds. Its average speed during this time is: (Consider $g = 10\\text{ m/s}^2$)',
    options: [
      { id: 'A', text: '20 m/s' },
      { id: 'B', text: '10 m/s' },
      { id: 'C', text: '5 m/s' },
      { id: 'D', text: '15 m/s' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Initial velocity $u = 0$.\nDistance covered in 2 s: $s = ut + \\frac{1}{2}gt^2 = 0 + \\frac{1}{2}(10)(2^2) = 20\\text{ m}$.\nAverage Speed $= \\frac{\\text{Total Distance}}{\\text{Total Time}} = \\frac{20\\text{ m}}{2\\text{ s}} = 10\\text{ m/s}$.\n(Alternatively: $v_{\\text{avg}} = \\frac{u + v}{2} = \\frac{0 + 20}{2} = 10\\text{ m/s}$).',
    formulaConcept: 'Uniform Acceleration Kinematics: $v_{\\text{avg}} = \\frac{u + v}{2} = \\frac{gt}{2}$.',
    shortcutTrick: '$v_{\\text{avg}} = \\frac{0 + 10(2)}{2} = 10\\text{ m/s}$.',
    commonMistake: 'Confusing final velocity ($20\\text{ m/s}$) with average speed ($10\\text{ m/s}$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q16',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Anand purchased an item and spent ₹84 on its repair. He then sold it to Bharath at a profit of 25%. Later, Bharath sold the item for ₹4,368, incurring a loss of 9%. What was Anand’s cost (in ₹) of the item just before selling it to Bharath?',
    options: [
      { id: 'A', text: '3838' },
      { id: 'B', text: '3842' },
      { id: 'C', text: '3839' },
      { id: 'D', text: '3840' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '1. Bharath sold for ₹4,368 at 9% loss:\n$\\text{Bharath\'s CP} = \\frac{4368}{1 - 0.09} = \\frac{4368}{0.91} = ₹4,800$.\n2. Anand sold to Bharath at 25% profit:\n$\\text{Anand\'s Total Cost} = \\frac{4800}{1.25} = ₹3,840$.',
    formulaConcept: 'Successive Profit/Loss Backtracking.',
    shortcutTrick: '$4368 / 0.91 = 4800 \\implies 4800 / 1.25 = 3840$.',
    commonMistake: 'Subtracting ₹84 when total cost just before selling is requested.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q17',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Mensuration',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Sumeet built a conical tent having a floor diameter of 28 m and a perpendicular height of 48 m. What was the length of a 10 m wide canvas that Sumeet needed for the purpose? [Use $\\pi = 22/7$]',
    options: [
      { id: 'A', text: '196 m' },
      { id: 'B', text: '220 m' },
      { id: 'C', text: '179 m' },
      { id: 'D', text: '200 m' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '1. Radius $r = \\frac{28}{2} = 14\\text{ m}$. Height $h = 48\\text{ m}$.\n2. Slant height $l = \\sqrt{14^2 + 48^2} = \\sqrt{196 + 2304} = \\sqrt{2500} = 50\\text{ m}$.\n3. Curved surface area of cone $= \\pi r l = \\frac{22}{7} \\times 14 \\times 50 = 22 \\times 2 \\times 50 = 2,200\\text{ m}^2$.\n4. Canvas length $= \\frac{\\text{Area}}{\\text{Width}} = \\frac{2200}{10} = 220\\text{ m}$.',
    formulaConcept: 'Cone CSA: $CSA = \\pi r l$; Canvas length $= \\frac{CSA}{w}$.',
    shortcutTrick: 'Slant height is $50\\text{ m}$. $CSA = 2200 \\implies 2200 / 10 = 220\\text{ m}$.',
    commonMistake: 'Using diameter 28 in slant height formula.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q18',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Biology',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'When a living plant cell loses water through osmosis (in a hypertonic solution), what happens to the cell contents?',
    options: [
      { id: 'A', text: 'They remain unchanged' },
      { id: 'B', text: 'They dissolve' },
      { id: 'C', text: 'They swell and burst' },
      { id: 'D', text: 'They contract and move away from the cell wall' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'When placed in a hypertonic environment, exosmosis occurs: water exits the central vacuole, causing the protoplast to shrink and peel away from the rigid cell wall—a phenomenon termed plasmolysis.',
    formulaConcept: 'Osmosis & Plant Cell Dynamics: Plasmolysis in hypertonic medium.',
    shortcutTrick: 'Water loss = Plasmolysis (protoplasm shrinks away from cell wall).',
    commonMistake: 'Selecting swell and burst (which happens in hypotonic medium without cell wall).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q19',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Data Sufficiency',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Among the five poles—I, N, C, H, and L—each having a different height, which pole is the shortest?\n(I) L is taller than H.\n(II) Only one pole is shorter than I. I is shorter than H but taller than N.',
    options: [
      { id: 'A', text: 'Both statements I and II together are sufficient to answer the question' },
      { id: 'B', text: 'Both statements I and II together are NOT sufficient' },
      { id: 'C', text: 'Data in statement II alone is sufficient to answer the question while data in statement I is not' },
      { id: 'D', text: 'Data in statement I alone is sufficient while data in statement II is not' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: 'From Statement II alone:\n"Only one pole is shorter than I" $\\implies$ I is the 4th tallest (2nd shortest).\n"I is taller than N" $\\implies$ The single pole shorter than I MUST be N.\nTherefore, N is uniquely determined as the shortest pole from Statement II alone.',
    formulaConcept: 'Data Sufficiency: Exact rank positioning from constraint statement.',
    shortcutTrick: 'Only one pole is shorter than I, and I > N $\\implies$ N is the shortest pole.',
    commonMistake: 'Believing both statements are required.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q20',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Percentage',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The price of a shirt is first increased by 10% and then increased by x%. If the overall percentage increase is 19%, what is the value of x (rounded off to nearest integer)?',
    options: [
      { id: 'A', text: '9' },
      { id: 'B', text: '8' },
      { id: 'C', text: '10' },
      { id: 'D', text: '11' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '$1.10 \\times \\left(1 + \\frac{x}{100}\\right) = 1.19 \\implies 1 + \\frac{x}{100} = \\frac{1.19}{1.10} = 1.0818 \\implies x = 8.18\\% \\approx 8\\%$.',
    formulaConcept: 'Successive percentage formula: $a + b + \\frac{ab}{100} = \\text{Net Increase}$.',
    shortcutTrick: '$10 + x + 0.1x = 19 \\implies 1.1x = 9 \\implies x = 90/11 \\approx 8.18 \\approx 8$.',
    commonMistake: 'Subtracting 10 from 19 directly ($9\\%$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q21',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Work',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The gravitational potential energy of an object near Earth\'s surface depends on:',
    options: [
      { id: 'A', text: 'Its acceleration only' },
      { id: 'B', text: 'Its velocity and mass' },
      { id: 'C', text: 'Its speed only' },
      { id: 'D', text: 'Its mass and height' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Gravitational potential energy is given by $U = mgh$, where $m$ is the mass, $g$ is acceleration due to gravity, and $h$ is the vertical height above reference datum.',
    formulaConcept: 'Gravitational Potential Energy: $U = mgh$.',
    shortcutTrick: '$PE = mgh \\implies$ Depends on mass and height.',
    commonMistake: 'Confusing with kinetic energy ($1/2 mv^2$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q22',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Biology',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Match the columns:\n\nEpithelial Tissue:\nI. Cuboidal Epithelium\nII. Columnar Epithelium\nIII. Squamous Epithelium\n\nLocation:\nA. Lining of intestine\nB. Skin\nC. Lining of kidney tubules',
    options: [
      { id: 'A', text: 'I-A; II-B; III-C' },
      { id: 'B', text: 'I-A; II-C; III-B' },
      { id: 'C', text: 'I-C; II-A; III-B' },
      { id: 'D', text: 'I-B; II-C; III-A' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '- Cuboidal epithelium forms the lining of kidney tubules and ducts of salivary glands (I-C).\n- Columnar epithelium lines the stomach and intestine for absorption and secretion (II-A).\n- Stratified squamous epithelium forms the outer protective layer of skin (III-B).\nMatching: I-C; II-A; III-B.',
    formulaConcept: 'Animal Tissues: Epithelial Tissue Classifications & Anatomical Sites.',
    shortcutTrick: 'Kidney tubules = Cuboidal; Intestine = Columnar; Skin = Squamous.',
    commonMistake: 'Swapping cuboidal and columnar locations.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q23',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Given words: SUN, RAT, HIT, BEG. In each word, every vowel is changed to the letter immediately following it and every consonant is changed to the letter immediately preceding it in alphabetical order. In how many letter-clusters thus formed will NO vowel appear?',
    options: [
      { id: 'A', text: 'None' },
      { id: 'B', text: 'Two' },
      { id: 'C', text: 'Three' },
      { id: 'D', text: 'One' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: 'Transform each word:\n1. SUN: S$\\to$R, U$\\to$V, N$\\to$M $\\implies$ RVM (0 vowels)\n2. RAT: R$\\to$Q, A$\\to$B, T$\\to$S $\\implies$ QBS (0 vowels)\n3. HIT: H$\\to$G, I$\\to$J, T$\\to$S $\\implies$ GJS (0 vowels)\n4. BEG: B$\\to$A, E$\\to$F, G$\\to$F $\\implies$ AFF (contains \'A\', 1 vowel).\nClusters with NO vowel = 3 (SUN, RAT, HIT).',
    formulaConcept: 'Word-based conditional transformation.',
    shortcutTrick: 'B becomes A (vowel) in BEG, others produce consonants only $\\implies 3$.',
    commonMistake: 'Overlooking that B (consonant) becomes A (vowel).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q24',
  },
  {
    subjectCode: 'RRB_ALP_GA',
    topicKeyword: 'Current Affairs',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In which location was Exercise Cyclone 2025 conducted between the Indian Army and Egyptian Army in February?',
    options: [
      { id: 'A', text: 'Jodhpur Desert Grounds, Rajasthan' },
      { id: 'B', text: 'Mahajan Field Firing Range, Rajasthan' },
      { id: 'C', text: 'Deesa Range, Gujarat' },
      { id: 'D', text: 'Babina Field, Uttar Pradesh' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The 3rd edition of the India-Egypt joint special forces military exercise \'Exercise Cyclone\' was held at the Mahajan Field Firing Range in Rajasthan.',
    formulaConcept: 'Joint Military Exercises of India.',
    shortcutTrick: 'Exercise Cyclone (Egypt-India) = Mahajan Range, Rajasthan.',
    commonMistake: 'Confusing Mahajan with Jodhpur or Pokhran.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q25',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the sequence (left to right):\n^ @ 4 > ? & % 2 ^ 5 * 7 3 6 ^ ? 8 6 & * 5\nHow many such numbers are there, each of which is immediately preceded by a symbol and also immediately followed by another number?',
    options: [
      { id: 'A', text: 'Two' },
      { id: 'B', text: 'One' },
      { id: 'C', text: 'Four' },
      { id: 'D', text: 'Three' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check for [Symbol][Number][Number]:\n1. * 7 3 $\\implies$ 7 is preceded by * (Symbol) and followed by 3 (Number) -> 1\n2. ? 8 6 $\\implies$ 8 is preceded by ? (Symbol) and followed by 6 (Number) -> 2\nTotal = 2 numbers (7 and 8).',
    formulaConcept: 'Sequence inspection with adjacent classification.',
    shortcutTrick: '*73 and ?86 are the two instances.',
    commonMistake: 'Counting 6 in 736 (preceded by number 3, not symbol).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q26',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the series (left to right):\n3 8 5 4 3 7 6 5 5 3 2 6 9 1 9 7 5 4 2 4 6 7\nHow many such odd digits are there, each of which is immediately preceded by an even digit and also immediately followed by an odd digit?',
    options: [
      { id: 'A', text: 'THREE' },
      { id: 'B', text: 'NONE' },
      { id: 'C', text: 'ONE' },
      { id: 'D', text: 'TWO' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: 'Pattern: [Even][Odd Target][Odd]\n1. 4 3 7 $\\implies$ 3 is preceded by 4 (Even) and followed by 7 (Odd) -> 1\n2. 6 5 5 $\\implies$ 5 is preceded by 6 (Even) and followed by 5 (Odd) -> 2\n3. 6 9 1 $\\implies$ 9 is preceded by 6 (Even) and followed by 1 (Odd) -> 3\nTotal = 3 (THREE).',
    formulaConcept: 'Parity Triplet Scanning: $[\\text{Even}][\\text{Odd}][\\text{Odd}]$.',
    shortcutTrick: '4-3-7, 6-5-5, 6-9-1.',
    commonMistake: 'Overlooking 6-5-5 where target 5 is followed by another 5.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q27',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Number System',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following numbers is divisible by 11?',
    options: [
      { id: 'A', text: '322431' },
      { id: 'B', text: '432321' },
      { id: 'C', text: '232144' },
      { id: 'D', text: '231243' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Divisibility rule for 11: $|\\sum \\text{odd digits} - \\sum \\text{even digits}|$ is a multiple of 11.\n- 232144: $(4 + 1 + 3) - (4 + 2 + 2) = 8 - 8 = 0$. Since 0 is divisible by 11, 232144 is divisible by 11.',
    formulaConcept: 'Divisibility by 11: Alternating digit sum is 0 or multiple of 11.',
    shortcutTrick: '$232144 \\implies (4+1+3) - (4+2+2) = 0$.',
    commonMistake: 'Calculation error on alternating positions.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q28',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Based on the English alphabetical order, three of the following four letter-clusters are alike in a certain way and form a group. Which letter-cluster DOES NOT belong to that group?\n\n1. BDF\n2. PRT\n3. HJL\n4. QSV',
    options: [
      { id: 'A', text: 'BDF' },
      { id: 'B', text: 'PRT' },
      { id: 'C', text: 'HJL' },
      { id: 'D', text: 'QSV' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Check letter steps:\n- BDF: $B(2) \\xrightarrow{+2} D(4) \\xrightarrow{+2} F(6)$\n- PRT: $P(16) \\xrightarrow{+2} R(18) \\xrightarrow{+2} T(20)$\n- HJL: $H(8) \\xrightarrow{+2} J(10) \\xrightarrow{+2} L(12)$\nAll three have $+2, +2$.\n- QSV: $Q(17) \\xrightarrow{+2} S(19) \\xrightarrow{+3} V(22)$ (has $+3$ instead of $+2$).\nHence QSV is the odd one out.',
    formulaConcept: 'Letter Triplet Difference Parity.',
    shortcutTrick: '$S(19) \\to V(22)$ is $+3$.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q29',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of the question mark (?) in the given series based on alphabetical order?\n\nACG IKO QSW YAE ?',
    options: [
      { id: 'A', text: 'GMJ' },
      { id: 'B', text: 'GMI' },
      { id: 'C', text: 'GIM' },
      { id: 'D', text: 'GYT' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'All letters advance by $+8$ modulo 26 across successive clusters:\n- 1st: $A(1) \\xrightarrow{+8} I(9) \\xrightarrow{+8} Q(17) \\xrightarrow{+8} Y(25) \\xrightarrow{+8} G(33/7)$\n- 2nd: $C(3) \\xrightarrow{+8} K(11) \\xrightarrow{+8} S(19) \\xrightarrow{+8} A(27/1) \\xrightarrow{+8} I(9)$\n- 3rd: $G(7) \\xrightarrow{+8} O(15) \\xrightarrow{+8} W(23) \\xrightarrow{+8} E(31/5) \\xrightarrow{+8} M(13)$.\nResult is GIM.',
    formulaConcept: 'Uniform $+8$ Modulo 26 Sequence.',
    shortcutTrick: '$Y+8=G, A+8=I, E+8=M \\implies \\text{GIM}$.',
    commonMistake: 'Selecting GMI by misplacing the last two characters.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q30',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Pipes',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Two pipes, A and B, can fill a tank in 20 minutes and 30 minutes, respectively. If both pipes are opened together, the time taken to fill the tank is:',
    options: [
      { id: 'A', text: '13 minutes' },
      { id: 'B', text: '12 minutes' },
      { id: 'C', text: '14 minutes' },
      { id: 'D', text: '15 minutes' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: '$T = \\frac{A \\times B}{A + B} = \\frac{20 \\times 30}{20 + 30} = \\frac{600}{50} = 12\\text{ minutes}$.',
    formulaConcept: 'Combined Work Rate: $T = \\frac{xy}{x+y}$.',
    shortcutTrick: '$600 / 50 = 12$ minutes.',
    commonMistake: 'Averaging the times ($25$ minutes).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q31',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Select the set in which the numbers are related in the same way as in the given sets:\n(153, 228, 303)\n(129, 204, 279)',
    options: [
      { id: 'A', text: '(172, 237, 322)' },
      { id: 'B', text: '(168, 247, 342)' },
      { id: 'C', text: '(191, 266, 381)' },
      { id: 'D', text: '(113, 188, 263)' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Constant addition of $+75$ across triplet:\n- $153 + 75 = 228$, $228 + 75 = 303$\n- $129 + 75 = 204$, $204 + 75 = 279$\nTesting (113, 188, 263):\n- $113 + 75 = 188$, $188 + 75 = 263$. Matches.',
    formulaConcept: 'Arithmetic Triad with common difference $d = 75$.',
    shortcutTrick: '$113 + 75 = 188, 188 + 75 = 263$.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q32',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Each of Aditi, Aryan, Rahul, Kirti, Riya, Tanvi and Mia has an exam on a different day (Mon to Sun). Aryan has an exam on Wednesday. Aditi has exam immediately after Riya. Only two people have exams between Aryan and Riya. Rahul has exam immediately after Kirti. Aryan has exam immediately before Tanvi. How many people have exams after Mia?',
    options: [
      { id: 'A', text: '5' },
      { id: 'B', text: '2' },
      { id: 'C', text: '4' },
      { id: 'D', text: '1' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: '1. Aryan = Wednesday (Day 3).\n2. Tanvi is immediately after Aryan $\\implies$ Tanvi = Thursday (Day 4).\n3. Two people between Aryan (Wed) and Riya $\\implies$ Riya = Saturday (Day 6).\n4. Aditi is immediately after Riya $\\implies$ Aditi = Sunday (Day 7).\n5. Rahul immediately after Kirti $\\implies$ Pair Kirti-Rahul must be Mon-Tue (Days 1 & 2).\n6. Remaining slot for Mia is Friday (Day 5).\nPeople having exams after Mia (Sat-Riya, Sun-Aditi) = 2 people.',
    formulaConcept: 'Linear Day Schedule Grid.',
    shortcutTrick: 'Mia is on Friday $\\implies 2$ people (Sat & Sun) after Mia.',
    commonMistake: 'Counting Friday as well.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q33',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Each vowel in the word PRODUCT is changed to the letter immediately following it and each consonant is changed to the letter immediately preceding it in the English alphabetical order. Which letter will be third from the left?',
    options: [
      { id: 'A', text: 'C' },
      { id: 'B', text: 'B' },
      { id: 'C', text: 'Q' },
      { id: 'D', text: 'P' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Third letter of PRODUCT is \'O\'. Since \'O\' is a vowel, it is changed to the next letter in the alphabet: $O + 1 = P$.',
    formulaConcept: 'Direct Target Letter Extraction & Rule Application.',
    shortcutTrick: '3rd letter is vowel O $\\implies O + 1 = P$.',
    commonMistake: 'Applying consonant rule to O ($O - 1 = N$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q34',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Data Sufficiency',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Four people – Mehul, Nitin, Prakash, and Sandeep – are sitting in a straight line facing north. Who is sitting at the extreme left end?\n(I) Nitin is sitting immediately to the right of Mehul.\n(II) Prakash is sitting immediately to the left of Sandeep.',
    options: [
      { id: 'A', text: 'Data in both statements I and II together are NOT sufficient to answer the question' },
      { id: 'B', text: 'Data in both statements I and II together are sufficient' },
      { id: 'C', text: 'Data in Statement II alone is sufficient while Statement I is not' },
      { id: 'D', text: 'Data in Statement I alone is sufficient while Statement II is not' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: 'From (I): Pair (Mehul, Nitin).\nFrom (II): Pair (Prakash, Sandeep).\nCombining both, two distinct linear orderings are valid:\n1. Mehul, Nitin, Prakash, Sandeep $\\implies$ Extreme left is Mehul.\n2. Prakash, Sandeep, Mehul, Nitin $\\implies$ Extreme left is Prakash.\nSince the extreme left person cannot be uniquely identified, both statements together are NOT sufficient.',
    formulaConcept: 'Data Sufficiency on disjoint paired permutations.',
    shortcutTrick: 'Two independent blocks of 2 can be arranged in 2 orders $\\implies$ Insufficient.',
    commonMistake: 'Assuming order of statements dictates linear sequence.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q35',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Blood',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'In a code language: \'A + B\' = mother, \'A − B\' = brother, \'A × B\' = wife, \'A ÷ B\' = father. How is M related to P if ‘M + N ÷ O × P − Q’?',
    options: [
      { id: 'A', text: 'Mother’s husband' },
      { id: 'B', text: 'Daughter' },
      { id: 'C', text: 'Brother’s wife' },
      { id: 'D', text: 'Wife’s father\'s mother' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: '- $P - Q \\implies P$ is brother of $Q$.\n- $O \\times P \\implies O$ is wife of $P$.\n- $N \\div O \\implies N$ is father of $O$ (wife\'s father).\n- $M + N \\implies M$ is mother of $N$ (wife\'s father\'s mother).\nTherefore, $M$ is P\'s wife\'s father\'s mother.',
    formulaConcept: 'Complex Multi-generational Coded Relations.',
    shortcutTrick: '$O$ is wife, $N$ is wife\'s father, $M$ is wife\'s father\'s mother.',
    commonMistake: 'Stopping at wife\'s mother.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q36',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Direction',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Wasim starts from Point A(0,0) and drives 24 km south. He turns right and drives 24 km, turns right and drives 31 km. He turns right and drives 33 km. He takes a final right turn, drives 7 km and stops at Point P. How far and towards which direction should he drive to reach Point A again?',
    options: [
      { id: 'A', text: '6 km to the east' },
      { id: 'B', text: '8 km to the west' },
      { id: 'C', text: '9 km to the west' },
      { id: 'D', text: '7 km to the east' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: 'Coordinates from $A(0,0)$:\n1. 24 km South $\\to (0, -24)$\n2. Right (West) 24 km $\\to (-24, -24)$\n3. Right (North) 31 km $\\to (-24, 7)$\n4. Right (East) 33 km $\\to (9, 7)$\n5. Right (South) 7 km $\\to (9, 0) = P$.\nTo reach $A(0,0)$ from $P(9, 0)$, Wasim must drive 9 km West.',
    formulaConcept: 'Displacement Summation: $x = -24 + 33 = 9$, $y = -24 + 31 - 7 = 0$.',
    shortcutTrick: '$P = (9, 0) \\implies 9\\text{ km West}$ to reach $(0,0)$.',
    commonMistake: 'Selecting 9 km to the east (vector from A to P).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q37',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Mathematical',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If ‘A’ stands for ‘÷’, ‘B’ stands for ‘×’, ‘C’ stands for ‘+’ and ‘D’ stands for ‘-’, what will come in place of the question mark (?) in:\n\n45 C 9 B 7 D 195 A 13 = ?',
    options: [
      { id: 'A', text: '93' },
      { id: 'B', text: '94' },
      { id: 'C', text: '95' },
      { id: 'D', text: '90' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '$45 + 9 \\times 7 - 195 \\div 13 = 45 + 63 - 15 = 108 - 15 = 93$.',
    formulaConcept: 'BODMAS Rule.',
    shortcutTrick: '$45 + 63 - 15 = 93$.',
    commonMistake: 'Adding before multiplying ($54 \\times 7$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q38',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Percentage',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Aman earns ₹36,000 per month. He spends 30% on rent, 25% on food and 20% on education. He saves the rest. Find his total savings in one year.',
    options: [
      { id: 'A', text: '₹1,04,400' },
      { id: 'B', text: '₹1,11,000' },
      { id: 'C', text: '₹1,08,000' },
      { id: 'D', text: '₹1,15,800' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '1. Total expenditure percentage $= 30\\% + 25\\% + 20\\% = 75\\%$.\n2. Monthly savings percentage $= 100\\% - 75\\% = 25\\%$.\n3. Monthly savings $= 36000 \\times 0.25 = ₹9,000$.\n4. Annual savings (12 months) $= 9000 \\times 12 = ₹1,08,000$.',
    formulaConcept: 'Budgeting & Yearly Income Projections.',
    shortcutTrick: '$36000 \\times 0.25 \\times 12 = 36000 \\times 3 = ₹1,08,000$.',
    commonMistake: 'Calculating for one month only (₹9,000).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q39',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Number System',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'The LCM of the decimal numbers 0.9, 3.7 and 0.54 is:',
    options: [
      { id: 'A', text: '99.9' },
      { id: 'B', text: '106' },
      { id: 'C', text: '105' },
      { id: 'D', text: '100' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Express with equal decimal places (2 decimal places):\n$0.90 = \\frac{90}{100}$, $3.70 = \\frac{370}{100}$, $0.54 = \\frac{54}{100}$.\nLCM of numerators {90, 370, 54}:\n- $90 = 2 \\times 3^2 \\times 5$\n- $370 = 2 \\times 5 \\times 37$\n- $54 = 2 \\times 3^3$\n$\\text{LCM}(90, 370, 54) = 2 \\times 3^3 \\times 5 \\times 37 = 270 \\times 37 = 9990$.\nDividing by 100 gives $\\frac{9990}{100} = 99.9$.',
    formulaConcept: 'LCM of Decimal Fractions: Make decimal digits equal, find integer LCM, divide by scaling base.',
    shortcutTrick: '$\\text{LCM}(90, 370, 54) / 100 = 9990 / 100 = 99.9$.',
    commonMistake: 'Finding LCM without equalizing decimal places.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q40',
  },
  {
    subjectCode: 'RRB_ALP_GA',
    topicKeyword: 'Polity',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'How many members are elected to the Public Accounts Committee (PAC) of Indian Parliament from the Rajya Sabha?',
    options: [
      { id: 'A', text: '15' },
      { id: 'B', text: '7' },
      { id: 'C', text: '22' },
      { id: 'D', text: '5' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The Public Accounts Committee consists of 22 members in total: 15 members elected from Lok Sabha and 7 members elected from Rajya Sabha through proportional representation.',
    formulaConcept: 'Parliamentary Committees Composition: PAC = 15 (LS) + 7 (RS) = 22.',
    shortcutTrick: 'Total 22 = 15 Lok Sabha + 7 Rajya Sabha.',
    commonMistake: 'Selecting 22 (total count) or 15 (Lok Sabha count).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q41',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Mensuration',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The volume of a cylinder having diameter 18 cm and height 35 cm is: [Take $\\pi = 22/7$]',
    options: [
      { id: 'A', text: '8910 cm3' },
      { id: 'B', text: '8918 cm3' },
      { id: 'C', text: '8902 cm3' },
      { id: 'D', text: '8920 cm3' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Radius $r = \\frac{18}{2} = 9\\text{ cm}$.\n$V = \\pi r^2 h = \\frac{22}{7} \\times 9^2 \\times 35 = 22 \\times 81 \\times 5 = 110 \\times 81 = 8,910\\text{ cm}^3$.',
    formulaConcept: 'Cylinder Volume: $V = \\pi r^2 h$.',
    shortcutTrick: '$22 \\times 5 \\times 81 = 110 \\times 81 = 8910$.',
    commonMistake: 'Using diameter 18 instead of radius 9.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q42',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Based on the English alphabetical order, three of the following four letter-cluster pairs are alike in a certain way and form a group. Which pair DOES NOT belong to that group?\n\n1. RS-VW\n2. TZ-AB\n3. GH-KL\n4. AB-EF',
    options: [
      { id: 'A', text: 'RS-VW' },
      { id: 'B', text: 'TZ-AB' },
      { id: 'C', text: 'GH-KL' },
      { id: 'D', text: 'AB-EF' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Pattern:\n- RS-VW: $R(+1)S \\xrightarrow{+3} V(+1)W$\n- GH-KL: $G(+1)H \\xrightarrow{+3} K(+1)L$\n- AB-EF: $A(+1)B \\xrightarrow{+3} E(+1)F$\nIn all three, both clusters are consecutive ($+1$) with a $+3$ gap between clusters.\n- TZ-AB: $T(20) \\xrightarrow{+6} Z(26) \\xrightarrow{+1} A(+1)B$. TZ has $+6$ internal gap.\nHence TZ-AB is the odd one out.',
    formulaConcept: 'Intra-cluster difference uniformity.',
    shortcutTrick: 'TZ has $+6$ gap, whereas all other clusters have consecutive letters ($+1$).',
    commonMistake: 'Missing the internal jump in TZ.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q43',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a certain code language, ‘HAST’ is coded as ‘3586’ and ‘DAHS’ is coded as ‘6357’. What is the code for ‘D’ in the given code language?',
    options: [
      { id: 'A', text: '5' },
      { id: 'B', text: '6' },
      { id: 'C', text: '3' },
      { id: 'D', text: '7' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Common letters between HAST and DAHS: {H, A, S}.\nCommon code digits between {3,5,8,6} and {6,3,5,7}: {3, 5, 6}.\nRemaining unique letter in DAHS is \'D\', and unique digit is \'7\'.\nTherefore, code for \'D\' is 7.',
    formulaConcept: 'Character frequency intersection in cipher analysis.',
    shortcutTrick: 'D is unique to DAHS $\\implies 7$ is unique to its code.',
    commonMistake: 'Positional index confusion.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q44',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Select the pair which follows the same pattern as:\nVQG : WNJ\nDUN : ERQ',
    options: [
      { id: 'A', text: 'NPL : OLO' },
      { id: 'B', text: 'IRI : JOL' },
      { id: 'C', text: 'PNQ : QKS' },
      { id: 'D', text: 'KRG : LOI' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check letter shift pattern: $[+1, -3, +3]$:\n- VQG $\\to$ WNJ: $V(22)+1=W(23), Q(17)-3=N(14), G(7)+3=J(10)$\n- DUN $\\to$ ERQ: $D(4)+1=E(5), U(21)-3=R(18), N(14)+3=Q(17)$\nTesting IRI $\\to$ JOL:\n- $I(9)+1=J(10), R(18)-3=O(15), I(9)+3=L(12)$. Exactly matches.',
    formulaConcept: 'Positional Alphabetic Triad Shifts: $[+1, -3, +3]$.',
    shortcutTrick: '$I+1=J, R-3=O, I+3=L \\implies \\text{JOL}$.',
    commonMistake: 'Selecting NPL : OLO ($L+3=O$, but $P-3=M \\ne L$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q45',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Venn',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Select the Venn diagram that best illustrates the relationship between the following classes:\nLawyers, Teachers, Parents',
    options: [
      { id: 'A', text: 'Three disjoint separate circles' },
      { id: 'B', text: 'Three mutually intersecting circles' },
      { id: 'C', text: 'One large circle enclosing two separate circles' },
      { id: 'D', text: 'Two concentric circles intersecting a third' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'A person can be simultaneously a Lawyer, a Teacher (e.g. law professor), and a Parent. Some lawyers are parents, some teachers are parents, and some individuals are all three. Therefore, three mutually intersecting circles best represent the relationship.',
    formulaConcept: 'Venn Diagram Representation of Non-exclusive overlapping sets.',
    shortcutTrick: 'All 3 categories overlap with one another $\\implies$ 3 mutually intersecting circles.',
    commonMistake: 'Assuming lawyers and teachers cannot overlap.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q46',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Select the set in which the numbers are related in the same way as in the given sets: (24, 8, 384) ; (18, 6, 216).',
    options: [
      { id: 'A', text: '(15, 9, 240)' },
      { id: 'B', text: '(17, 6, 204)' },
      { id: 'C', text: '(13, 10, 130)' },
      { id: 'D', text: '(24, 3, 240)' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Pattern: $a \\times b \\times 2 = c$.\n- $24 \\times 8 \\times 2 = 192 \\times 2 = 384$\n- $18 \\times 6 \\times 2 = 108 \\times 2 = 216$\n- For (17, 6, 204): $17 \\times 6 \\times 2 = 102 \\times 2 = 204$. Matches.',
    formulaConcept: 'Product scaling: $c = 2ab$.',
    shortcutTrick: '$17 \\times 12 = 204$.',
    commonMistake: 'Trying squared operations.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q47',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Based on the English alphabetical order, three of the following four letter-cluster pairs are alike in a certain way and form a group. Which pair DOES NOT belong to that group?\n\n1. NO−ST\n2. RS−WX\n3. YZ−DE\n4. MN−QU',
    options: [
      { id: 'A', text: 'NO−ST' },
      { id: 'B', text: 'RS−WX' },
      { id: 'C', text: 'YZ−DE' },
      { id: 'D', text: 'MN−QU' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Pattern across pairs ($+5, +5$):\n- NO−ST: $N(14)+5=S(19), O(15)+5=T(20)$\n- RS−WX: $R(18)+5=W(23), S(19)+5=X(24)$\n- YZ−DE: $Y(25)+5=D(30/4), Z(26)+5=E(31/5)$\nAll three have $+5$ on both letters.\n- MN−QU: $M(13)+4=Q(17), N(14)+7=U(21)$ (violates $+5$ rule).\nHence MN−QU does not belong.',
    formulaConcept: 'Positional Shift Parity across paired clusters.',
    shortcutTrick: '$N(14) \\to U(21)$ is $+7$, unlike $+5$ in all other pairs.',
    commonMistake: 'Checking consecutive letters only.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q48',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A, Q, N, L, R and K live on six different floors (1 to 6). L lives on an even-numbered floor but not on the topmost floor. Only three people live between K and N. R lives immediately below Q. K lives immediately above L. A lives on the topmost floor. Who lives on floor number 3?',
    options: [
      { id: 'A', text: 'K' },
      { id: 'B', text: 'A' },
      { id: 'C', text: 'R' },
      { id: 'D', text: 'Q' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: '1. A is on Floor 6 (topmost).\n2. L is on an even floor not 6 $\\implies$ L can be on Floor 4 or 2.\n3. K lives immediately above L $\\implies$ If L = 4, K = 5. Then 3 people between K (5) and N $\\implies$ N is on Floor 1 (5 - 3 - 1 = 1).\n4. Remaining floors for Q and R are 3 and 2. Since R is immediately below Q $\\implies$ Q = Floor 3, R = Floor 2.\nFloor layout: 6-A, 5-K, 4-L, 3-Q, 2-R, 1-N.\nFloor number 3 is occupied by Q.',
    formulaConcept: '6-Floor Puzzle Logic.',
    shortcutTrick: 'Layout: 6-A, 5-K, 4-L, 3-Q, 2-R, 1-N $\\implies$ Floor 3 = Q.',
    commonMistake: 'Placing L on floor 2.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q49',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Chemistry',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'To neutralise excess acidity in the human stomach, one can take:',
    options: [
      { id: 'A', text: 'Lemon juice' },
      { id: 'B', text: 'Antacids like Mg(OH)₂' },
      { id: 'C', text: 'HCl solution' },
      { id: 'D', text: 'Vinegar' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Mild bases such as Magnesium Hydroxide ($Mg(OH)_2$ / Milk of Magnesia) or Sodium Hydrogen Carbonate ($NaHCO_3$) act as antacids to neutralize excess hydrochloric acid in gastric juice without irritating the mucous lining.',
    formulaConcept: 'Acid-Base Neutralization: $Mg(OH)_2 + 2HCl \\to MgCl_2 + 2H_2O$.',
    shortcutTrick: 'Antacid = Milk of Magnesia $Mg(OH)_2$.',
    commonMistake: 'Selecting acidic substances like lemon juice or vinegar.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q50',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Statistics',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The marks obtained by 9 students of a class in mathematics are 76, 85, 47, 67, 85, 76, 47, 76, 67. What is the mode of these numbers?',
    options: [
      { id: 'A', text: '85' },
      { id: 'B', text: '47' },
      { id: 'C', text: '67' },
      { id: 'D', text: '76' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Frequency table:\n- 76: occurs 3 times\n- 85: occurs 2 times\n- 47: occurs 2 times\n- 67: occurs 2 times\nThe mark 76 has the highest frequency (3). Hence mode = 76.',
    formulaConcept: 'Mode is the most frequent data observation.',
    shortcutTrick: '76 appears 3 times.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q51',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Partnership',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Praveen and Sheenu are partners in a business. Praveen invests ₹35,000 for 9 months and Sheenu invests ₹42,000 for 10 months. Out of a total profit of ₹31,570, find Sheenu\'s share.',
    options: [
      { id: 'A', text: '₹18,020' },
      { id: 'B', text: '₹18,240' },
      { id: 'C', text: '₹18,040' },
      { id: 'D', text: '₹18,640' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: 'Profit sharing ratio $= (C_1 \\times T_1) : (C_2 \\times T_2)$:\n$\\text{Praveen} : \\text{Sheenu} = (35000 \\times 9) : (42000 \\times 10) = 315000 : 420000 = 315 : 420 = 3 : 4$.\nTotal ratio units $= 3 + 4 = 7$.\nSheenu\'s share $= \\frac{4}{7} \\times 31570 = 4 \\times 4510 = ₹18,040$.',
    formulaConcept: 'Compound Partnership Profit Ratio: $P_1 : P_2 = C_1 T_1 : C_2 T_2$.',
    shortcutTrick: '$31570 / 7 = 4510 \\implies 4510 \\times 4 = ₹18,040$.',
    commonMistake: 'Dividing profit equally without taking time duration into account.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q52',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Below are given two sets of numbers:\n10 - 5 - 25 - 30 ; 4 - 2 - 4 - 9\nWhich of the given options follows the same set of operations?',
    options: [
      { id: 'A', text: '12 - 6 - 36 - 40' },
      { id: 'B', text: '7 - 49 - 54 - 60' },
      { id: 'C', text: '10 - 20 - 40 - 50' },
      { id: 'D', text: '8 - 4 - 16 - 21' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Pattern: Given 1st number $2k$:\n- 2nd number $= \\frac{2k}{2} = k$\n- 3rd number $= k^2$\n- 4th number $= k^2 + 5$.\nVerify:\n- $10 \\to 5 \\to 5^2=25 \\to 25+5=30$\n- $4 \\to 2 \\to 2^2=4 \\to 4+5=9$\nTesting 8 - 4 - 16 - 21:\n- $8 \\to 4 \\to 4^2=16 \\to 16+5=21$. Exactly matches.',
    formulaConcept: 'Mathematical Sequence Relation: $(2k, k, k^2, k^2+5)$.',
    shortcutTrick: '$8/2=4, 4^2=16, 16+5=21$.',
    commonMistake: 'Selecting Option A where 4th number is $36+4=40$ instead of $+5$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q53',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Algebra',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Among five people named V, W, X, Y and Z: X is thrice the age of Y. The age of V is 3. Y is half the age of Z. W is twice the age of V. If Z is four times the age of W, what is the age of X?',
    options: [
      { id: 'A', text: '38' },
      { id: 'B', text: '34' },
      { id: 'C', text: '40' },
      { id: 'D', text: '36' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '1. $V = 3$.\n2. $W = 2 \\times V = 2 \\times 3 = 6$.\n3. $Z = 4 \\times W = 4 \\times 6 = 24$.\n4. $Y = \\frac{Z}{2} = \\frac{24}{2} = 12$.\n5. $X = 3 \\times Y = 3 \\times 12 = 36$.',
    formulaConcept: 'Sequential Direct Substitution.',
    shortcutTrick: '$X = 3 \\times \\frac{4(2 \\times 3)}{2} = 3 \\times 12 = 36$.',
    commonMistake: 'Arithmetic error in multiplying $3 \\times 12$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q54',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Number System',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'If 1 is added to each odd digit and 2 is subtracted from each even digit in the number 7531468, how many digits will appear more than once in the new number thus formed?',
    options: [
      { id: 'A', text: 'One' },
      { id: 'B', text: 'Three' },
      { id: 'C', text: 'None' },
      { id: 'D', text: 'Two' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Given digits: 7, 5, 3, 1, 4, 6, 8\nApplying operations:\n- Odd digits (+1): $7+1=8, 5+1=6, 3+1=4, 1+1=2$\n- Even digits (-2): $4-2=2, 6-2=4, 8-2=6$\nNew digits formed: 8, 6, 4, 2, 2, 4, 6.\nFrequency of digits:\n- 2: appears twice\n- 4: appears twice\n- 6: appears twice\n- 8: appears once\nDigits appearing more than once are 2, 4, and 6 (Three digits).',
    formulaConcept: 'Conditional Digit Modification and Frequency Tally.',
    shortcutTrick: 'Digits 2, 4, 6 appear twice $\\implies$ 3 digits.',
    commonMistake: 'Counting total count of repeated occurrences instead of distinct digits.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q55',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A store marks up an item by 50% and then provides a discount of 20% on the marked price. If the final selling price is ₹2,400, what was the cost price (in ₹)?',
    options: [
      { id: 'A', text: '1,800' },
      { id: 'B', text: '2,050' },
      { id: 'C', text: '2,100' },
      { id: 'D', text: '2,000' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '$SP = CP \\times 1.50 \\times (1 - 0.20) = CP \\times 1.50 \\times 0.80 = 1.20 CP = 2400$.\n$CP = \\frac{2400}{1.20} = ₹2,000$.',
    formulaConcept: 'Markup and Discount Relationship: $SP = CP(1 + m)(1 - d)$.',
    shortcutTrick: '$2400 / 1.2 = 2000$.',
    commonMistake: 'Taking net percentage as $50 - 20 = 30\\%$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q56',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'A shopkeeper sells an item for ₹225.6 after giving two successive discounts of 90% and 50% on its marked price. Had he not given any discount, he would have earned a profit of 41%. What is the cost price (in ₹) of the item?',
    options: [
      { id: 'A', text: '3,182' },
      { id: 'B', text: '3,204' },
      { id: 'C', text: '3,194' },
      { id: 'D', text: '3,200' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. $SP = MP \\times (1 - 0.90) \\times (1 - 0.50) = MP \\times 0.10 \\times 0.50 = 0.05 MP = 225.6$.\n2. $MP = \\frac{225.6}{0.05} = 4512$.\n3. Zero discount gives 41% profit on CP $\\implies CP = \\frac{MP}{1.41} = \\frac{4512}{1.41} = ₹3,200$.',
    formulaConcept: 'Successive Discounts to CP Formula.',
    shortcutTrick: '$MP = 225.6 \\times 20 = 4512 \\implies 4512 / 1.41 = 3200$.',
    commonMistake: 'Dividing 4512 by 0.41 instead of 1.41.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q57',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Speed',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A faster train, 300 meters long, crosses a platform 600 meters in length in 40 seconds. A slower train, 450 meters long, takes 60 seconds to cross the same platform. Find the time it will take for the two trains to completely pass each other when traveling in opposite directions.',
    options: [
      { id: 'A', text: '18.75 seconds' },
      { id: 'B', text: '18.18 seconds' },
      { id: 'C', text: '17.85 seconds' },
      { id: 'D', text: '17.58 seconds' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. Speed of faster train $v_1 = \\frac{300 + 600}{40} = \\frac{900}{40} = 22.5\\text{ m/s}$.\n2. Speed of slower train $v_2 = \\frac{450 + 600}{60} = \\frac{1050}{60} = 17.5\\text{ m/s}$.\n3. Relative speed in opposite directions $= v_1 + v_2 = 22.5 + 17.5 = 40\\text{ m/s}$.\n4. Total distance to clear each other $= L_1 + L_2 = 300 + 450 = 750\\text{ m}$.\n5. Crossing time $= \\frac{750}{40} = 18.75\\text{ seconds}$.',
    formulaConcept: 'Relative Speed of Crossing Trains: $t = \\frac{L_1 + L_2}{v_1 + v_2}$.',
    shortcutTrick: '$750 / (22.5 + 17.5) = 750 / 40 = 18.75\\text{ s}$.',
    commonMistake: 'Including the platform length when trains cross each other.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q58',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Mathematical',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What will come in place of ‘?’ in the following equation, if ‘+’ and ‘-’ are interchanged and ‘×’ and ‘÷’ are interchanged?\n\n31 - 26 × 1 ÷ 24 + 45 = ?',
    options: [
      { id: 'A', text: '612' },
      { id: 'B', text: '608' },
      { id: 'C', text: '611' },
      { id: 'D', text: '610' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Substitute interchanged operators:\n$31 + 26 \\div 1 \\times 24 - 45$\n1. Division: $26 \\div 1 = 26$\n2. Multiplication: $26 \\times 24 = 624$\n3. Expression: $31 + 624 - 45 = 655 - 45 = 610$.',
    formulaConcept: 'BODMAS Evaluation.',
    shortcutTrick: '$31 + 624 - 45 = 610$.',
    commonMistake: 'Subtracting 45 before adding.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q59',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Direction',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Yatin starts from Point A(0,0) and drives 21 km East. He turns left and drives 15 km, turns left and drives 29 km. He turns left and drives 26 km. He takes a final left turn, drives 8 km and stops at Point P. How far and towards which direction should he drive to reach Point A again?',
    options: [
      { id: 'A', text: '10 km to the North' },
      { id: 'B', text: '9 km to the South' },
      { id: 'C', text: '9 km to the North' },
      { id: 'D', text: '11 km to the North' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: 'Coordinates starting from $A(0,0)$:\n1. 21 km East $\\to (21, 0)$\n2. Left (North) 15 km $\\to (21, 15)$\n3. Left (West) 29 km $\\to (-8, 15)$\n4. Left (South) 26 km $\\to (-8, -11)$\n5. Left (East) 8 km $\\to (0, -11) = P$.\nTo reach $A(0,0)$ from $P(0, -11)$, Yatin must drive 11 km North.',
    formulaConcept: 'Vector displacement analysis: $x = 21 - 29 + 8 = 0$, $y = 15 - 26 = -11$.',
    shortcutTrick: '$P = (0, -11) \\implies 11\\text{ km North}$ to reach origin.',
    commonMistake: 'Selecting 11 km South.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q60',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Statistics',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the mode of the following data?\n89, 76, 76, 88, 81, 81, 65, 90, 83, 89, 64, 63, 78, 64, 82, 87, 79, 89, 87, 65, 86, 77, 80, 70, 67',
    options: [
      { id: 'A', text: '76' },
      { id: 'B', text: '64' },
      { id: 'C', text: '81' },
      { id: 'D', text: '89' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Frequency count:\n- 89: occurs 3 times\n- 76: occurs 2 times\n- 81: occurs 2 times\n- 65: occurs 2 times\n- 64: occurs 2 times\n- 87: occurs 2 times\n89 has the highest frequency (3). Hence the mode is 89.',
    formulaConcept: 'Mode of ungrouped dataset.',
    shortcutTrick: '89 appears 3 times (highest count).',
    commonMistake: 'Selecting 76 which appears only twice.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q61',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Interest',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'On a certain sum, if at the same rate of interest for 2 years, the simple interest is ₹66 and the compound interest is ₹67, then what is the sum (in ₹)?',
    options: [
      { id: 'A', text: '1089' },
      { id: 'B', text: '1093' },
      { id: 'C', text: '1084' },
      { id: 'D', text: '1082' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '1. SI for 1 year $= \\frac{66}{2} = ₹33$.\n2. Difference $CI - SI = 67 - 66 = ₹1$.\n3. The ₹1 difference is 1 year\'s interest on 1st year\'s SI (₹33) $\\implies R = \\frac{1}{33} \\times 100\\%$.\n4. Principal $P = \\frac{SI_1 \\times 100}{R} = \\frac{33 \\times 100}{(1/33 \\times 100)} = 33^2 = ₹1,089$.',
    formulaConcept: '2-Year CI and SI Difference: $P = \\frac{(SI/2)^2}{CI - SI}$.',
    shortcutTrick: '$P = \\frac{33^2}{1} = 1089$.',
    commonMistake: 'Squaring 66 instead of half-SI (33).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q62',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Partnership',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Rajesh and Naresh start a business by investing ₹66,000 and ₹29,000, respectively. Rajesh invests his money for 2 months and Naresh for 12 months. At the end of the year, 5% of the total profit is ₹7,036. What is Naresh’s share of the profit (in ₹)?',
    options: [
      { id: 'A', text: '1,03,156' },
      { id: 'B', text: '1,02,022' },
      { id: 'C', text: '1,02,145' },
      { id: 'D', text: '1,03,148' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 45,
    explanation: '1. Total Profit: $5\\% \\text{ of Total} = 7036 \\implies \\text{Total Profit} = 7036 \\times 20 = ₹1,40,720$.\n2. Profit Ratio $= (66000 \\times 2) : (29000 \\times 12) = 132000 : 348000 = 132 : 348 = 11 : 29$.\n3. Total Ratio units $= 11 + 29 = 40$.\n4. Naresh\'s share $= \\frac{29}{40} \\times 140720 = 29 \\times 3518 = ₹1,02,022$.',
    formulaConcept: 'Partnership with Time Weighting and Percentage Profit scaling.',
    shortcutTrick: '$3518 \\times 29 = 102,022$.',
    commonMistake: 'Using ₹7,036 directly without multiplying by 20.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q63',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Analogies',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Select the triad which follows the same pattern as:\nLHC – PLG – TPK\nSOJ – WSN – AWR',
    options: [
      { id: 'A', text: 'UQL – YUP – CYU' },
      { id: 'B', text: 'UHK – XTP – FBX' },
      { id: 'C', text: 'VRM – ZVQ – DZU' },
      { id: 'D', text: 'RNI – XTP – AVQ' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check shift pattern: $+4$ on all letters across the triad:\n- LHC $\\xrightarrow{+4}$ PLG $\\xrightarrow{+4}$ TPK: $L(12)+4=P(16)+4=T(20); H(8)+4=L(12)+4=P(16); C(3)+4=G(7)+4=K(11)$\n- SOJ $\\xrightarrow{+4}$ WSN $\\xrightarrow{+4}$ AWR: $S(19)+4=W(23)+4=A(27/1); O(15)+4=S(19)+4=W(23); J(10)+4=N(14)+4=R(18)$\nTesting VRM – ZVQ – DZU:\n- $V(22)+4=Z(26)+4=D(30/4)$\n- $R(18)+4=V(22)+4=Z(26)$\n- $M(13)+4=Q(17)+4=U(21)$. Matches.',
    formulaConcept: 'Triad Advancement with $+4$ Constant Shift.',
    shortcutTrick: '$V+4=Z+4=D, R+4=V+4=Z, M+4=Q+4=U \\implies \\text{VRM – ZVQ – DZU}$.',
    commonMistake: 'Option A has CYU where $L+4=P+4=T \\ne U$.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q64',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Refer to the sequence (left to right):\nF Y $ F O € Z # J © G * U N @ M $ N © £ © &\nHow many such letters are there, each of which is immediately preceded by a symbol and also immediately followed by a symbol?',
    options: [
      { id: 'A', text: '5' },
      { id: 'B', text: '4' },
      { id: 'C', text: '6' },
      { id: 'D', text: '7' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Check for [Symbol][Letter][Symbol]:\n1. $ F O -> F is preceded by $ and followed by O (Letter, not symbol) -> No\n2. € Z # -> Z is preceded by € and followed by # -> 1\n3. # J © -> J is preceded by # and followed by © -> 2\n4. © G * -> G is preceded by © and followed by * -> 3\n5. @ M $ -> M is preceded by @ and followed by $ -> 4\n6. $ N © -> N is preceded by $ and followed by © -> 5\nTotal = 5 letters (Z, J, G, M, N).',
    formulaConcept: 'Pattern Matching in character strings.',
    shortcutTrick: '€Z#, #J©, ©G*, @M$, $N© = 5 instances.',
    commonMistake: 'Counting U in *UN@ where U is followed by letter N.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q65',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Series',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should come in place of the question mark (?) in the given series?\n\n145 132 120 109 99 90 ?',
    options: [
      { id: 'A', text: '78' },
      { id: 'B', text: '80' },
      { id: 'C', text: '82' },
      { id: 'D', text: '84' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Differences decrease by 1 sequentially:\n$145 - 13 = 132$\n$132 - 12 = 120$\n$120 - 11 = 109$\n$109 - 10 = 99$\n$99 - 9 = 90$\n$90 - 8 = 82$.',
    formulaConcept: 'Decreasing Difference Series: $-13, -12, -11, -10, -9, -8$.',
    shortcutTrick: '$90 - 8 = 82$.',
    commonMistake: 'Subtracting 9 again ($81$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q66',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Geometry',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Determine the arc length (in units) of a sector, if the central angle of the sector with radius 6 units is 60°. [Take $\\pi = 22/7$]',
    options: [
      { id: 'A', text: '22/7' },
      { id: 'B', text: '44/7' },
      { id: 'C', text: '11/7' },
      { id: 'D', text: '33/7' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Arc Length $L = \\frac{\\theta}{360^\\circ} \\times 2\\pi r = \\frac{60^\\circ}{360^\\circ} \\times 2 \\times \\frac{22}{7} \\times 6 = \\frac{1}{6} \\times 12 \\times \\frac{22}{7} = 2 \\times \\frac{22}{7} = \\frac{44}{7}\\text{ units}$.',
    formulaConcept: 'Arc Length of Circular Sector: $L = \\frac{\\theta}{360^\\circ} \\cdot 2\\pi r$.',
    shortcutTrick: '$\\frac{1}{6} \\times 2\\pi(6) = 2\\pi = 2 \\times \\frac{22}{7} = \\frac{44}{7}$.',
    commonMistake: 'Computing sector area instead of arc length.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q67',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Syllogism',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Read the given statements and conclusions carefully:\n\nStatements:\nSome bugs are moths.\nSome moths are parrots.\n\nConclusions:\n(I) Some parrots are bugs.\n(II) All moths are bugs.',
    options: [
      { id: 'A', text: 'Only conclusion (II) follows.' },
      { id: 'B', text: 'Only conclusion (I) follows.' },
      { id: 'C', text: 'Both conclusions (I) and (II) follow.' },
      { id: 'D', text: 'Neither conclusion (I) nor (II) follows.' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Two particular affirmative ("Some") premises do not yield any definite conclusion linking the non-overlapping terms (Bugs and Parrots). Thus, neither conclusion (I) nor conclusion (II) definitely follows.',
    formulaConcept: 'Syllogism Rule: Two "Some" statements with an undistributed middle term yield no valid deduction.',
    shortcutTrick: 'Some + Some $\\implies$ No definite conclusion.',
    commonMistake: 'Assuming transitive relation between bugs and parrots.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q68',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Work',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: '5 printers can print 9,000 pages in 6 hours. How many printers are needed to print 28,800 pages in 8 hours at the same rate?',
    options: [
      { id: 'A', text: '11' },
      { id: 'B', text: '12' },
      { id: 'C', text: '13' },
      { id: 'D', text: '10' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '$\\frac{M_1 \\times H_1}{W_1} = \\frac{M_2 \\times H_2}{W_2} \\implies \\frac{5 \\times 6}{9000} = \\frac{M_2 \\times 8}{28800}$.\n$\\frac{30}{9000} = \\frac{1}{300} = \\frac{8 M_2}{28800} \\implies 8 M_2 = \\frac{28800}{300} = 96 \\implies M_2 = \\frac{96}{8} = 12\\text{ printers}$.',
    formulaConcept: 'Chain Rule in Work and Time: $\\frac{M_1 T_1}{W_1} = \\frac{M_2 T_2}{W_2}$.',
    shortcutTrick: '1 printer = 300 pages/hr. To print 28800 in 8 hrs: $28800 / (8 \\times 300) = 28800 / 2400 = 12$.',
    commonMistake: 'Inverting work numerator and denominator.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q69',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Seating',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'T, W, A, L, O and B live on six different floors (1 to 6). A lives on an even-numbered floor. T lives immediately below A. Exactly one person lives between T and L. Exactly one person lives between W and L. W lives immediately above O. O does not live on the lowermost floor. Who lives immediately above L?',
    options: [
      { id: 'A', text: 'T' },
      { id: 'B', text: 'A' },
      { id: 'C', text: 'O' },
      { id: 'D', text: 'W' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 50,
    explanation: '1. A is on even floor, T is immediately below A (pair A-T).\n2. If A = 6, T = 5. One person between T (5) and L $\\implies$ L = 3.\n3. One person between W and L (3) $\\implies$ W = 5 or 1. But T=5, so W must be on Floor 5? No, W is immediately above O $\\implies$ Pair W-O.\nIf A = 2, T = 1. One person between T (1) and L $\\implies$ L = 3. One person between W and L (3) $\\implies$ W = 5. Since W is immediately above O $\\implies$ O = Floor 4. Remaining B = Floor 6.\nFloor layout: 6-B, 5-W, 4-O, 3-L, 2-A, 1-T.\nImmediately above L (Floor 3) lives O (Floor 4).',
    formulaConcept: '6-Floor Arrangement Puzzle with Interleaved Constraints.',
    shortcutTrick: 'Layout: 6-B, 5-W, 4-O, 3-L, 2-A, 1-T $\\implies$ O is immediately above L.',
    commonMistake: 'Placing A on floor 6.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q70',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Geometry',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If two lines are parallel and a transversal makes an angle of 65° with one line, what is the measure of the corresponding angle on the other line?',
    options: [
      { id: 'A', text: '65°' },
      { id: 'B', text: '115°' },
      { id: 'C', text: '25°' },
      { id: 'D', text: '55°' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 10,
    explanation: 'According to the Corresponding Angles Postulate, when two parallel lines are cut by a transversal, corresponding angles are equal in measure ($65^\\circ$).',
    formulaConcept: 'Parallel Lines & Transversal Geometry: Corresponding angles are equal.',
    shortcutTrick: 'Corresponding angles are equal = 65°.',
    commonMistake: 'Selecting supplementary consecutive interior angle ($180^\\circ - 65^\\circ = 115^\\circ$).',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q71',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Interest',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What sum (in ₹) will earn an interest of ₹460 in 4 years at 10% simple interest per year?',
    options: [
      { id: 'A', text: '1300' },
      { id: 'B', text: '1150' },
      { id: 'C', text: '950' },
      { id: 'D', text: '1350' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: '$P = \\frac{SI \\times 100}{R \\times T} = \\frac{460 \\times 100}{10 \\times 4} = \\frac{46000}{40} = ₹1,150$.',
    formulaConcept: 'Simple Interest: $P = \\frac{100 \\times SI}{RT}$.',
    shortcutTrick: '$460 / 40\\% = 460 / 0.4 = 1150$.',
    commonMistake: 'Calculation error with 460/4.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q72',
  },
  {
    subjectCode: 'RRB_ALP_REASON',
    topicKeyword: 'Coding',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Each vowel in the word TRASHED is changed to the letter immediately following it and each consonant is changed to the letter immediately preceding it in the English alphabetical order. Which letter will be third from the left in the new group?',
    options: [
      { id: 'A', text: 'Q' },
      { id: 'B', text: 'R' },
      { id: 'C', text: 'G' },
      { id: 'D', text: 'B' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The third letter of TRASHED is \'A\'. Since \'A\' is a vowel, it is replaced by the next letter: $A + 1 = B$.',
    formulaConcept: 'Direct Target Letter Extraction.',
    shortcutTrick: '3rd letter is vowel A $\\implies A + 1 = B$.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q73',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Chemistry',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following physical observations supports the kinetic theory statement that "matter is made of discrete small particles with spaces between them"?',
    options: [
      { id: 'A', text: 'Oil floats above the surface after gentle stirring.' },
      { id: 'B', text: 'Chalk powder remains visible even after mixing.' },
      { id: 'C', text: 'Sugar dissolves in water without change in the water level.' },
      { id: 'D', text: 'Sand settles at the bottom when mixed with water.' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'When sugar crystals dissolve in water, the individual sugar molecules occupy the intermolecular spaces between liquid water molecules, resulting in no measurable rise in total liquid volume.',
    formulaConcept: 'Particulate Nature of Matter & Intermolecular Spaces.',
    shortcutTrick: 'Sugar dissolving without volume increase proves intermolecular spaces.',
    commonMistake: 'Selecting insoluble suspensions like sand or chalk.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q74',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Profit',
    year: 2026,
    shift: 'Shift 1',
    paper: 'CEN 01/2025 CBT-1 16 Feb 2026 S1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Arvind bought an article for ₹x. He sold it to Biru at a loss of 30%. Biru spent ₹198 on its transportation and sold it to Minu at a profit of 50%. If Minu bought it for ₹1,053, then what is the value of x?',
    options: [
      { id: 'A', text: '671' },
      { id: 'B', text: '696' },
      { id: 'C', text: '715' },
      { id: 'D', text: '720' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '1. Arvind\'s SP $= 0.70x$.\n2. Biru\'s total cost $= 0.70x + 198$.\n3. Biru sold at 50% profit for ₹1,053:\n$(0.70x + 198) \\times 1.50 = 1053 \\implies 0.70x + 198 = \\frac{1053}{1.50} = 702$.\n$0.70x = 702 - 198 = 504$.\n$x = \\frac{504}{0.70} = 720$.',
    formulaConcept: 'Multi-stage Transaction Linear Equation.',
    shortcutTrick: '$702 - 198 = 504 \\implies x = 504 / 0.7 = 720$.',
    commonMistake: 'Applying profit percentage before adding transportation overhead.',
    sourceRef: 'RRB ALP CEN 01/2025 CBT 1 16-02-2026 Shift 1 Q75',
  },
];
