import { RawQuestionData } from './gateQuestions.js';

export const rrbAlp2024PartBQuestions: RawQuestionData[] = [
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'AC',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'What is the phase difference between the line voltage and phase voltage in a star-connected load?',
    options: [
      { id: 'A', text: '120°' },
      { id: 'B', text: '30°' },
      { id: 'C', text: '90°' },
      { id: 'D', text: '0°' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'In a 3-phase star-connected AC system, the line voltage ($V_L$) is the vector difference between two phase voltages ($V_L = V_{RY} = V_R - V_Y$). The phasor relationship gives $V_L = \\sqrt{3} V_{ph} \\angle 30^\\circ$. Hence, the line voltage leads the corresponding phase voltage by $30^\\circ$.',
    formulaConcept: 'Star Connection Relations: $V_L = \\sqrt{3} V_{ph} \\angle 30^\\circ$, $I_L = I_{ph}$.',
    shortcutTrick: 'Star connection = Line voltage leads Phase voltage by 30°.',
    commonMistake: 'Confusing 120° (phase displacement between individual phases) with 30° (line to phase angle).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q1',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Transformers',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Calculate the voltage regulation (in percentage) of the transformer if the no load secondary voltage is 250 V and full load secondary voltage is 200 V?',
    options: [
      { id: 'A', text: '50%' },
      { id: 'B', text: '25%' },
      { id: 'C', text: '20%' },
      { id: 'D', text: '100%' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Voltage Regulation (down) $\\% = \\frac{V_{NL} - V_{FL}}{V_{FL}} \\times 100 = \\frac{250 - 200}{200} \\times 100 = \\frac{50}{200} \\times 100 = 25\\%$.',
    formulaConcept: 'Voltage Regulation $\\% = \\frac{V_{NL} - V_{FL}}{V_{FL}} \\times 100$.',
    shortcutTrick: '$50 / 200 = 1/4 = 25\\%$.',
    commonMistake: 'Dividing by no-load voltage (250 V) which gives 20% regulation up.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q2',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Transformers',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In the open circuit test of a transformer, the supply frequency should be:',
    options: [
      { id: 'A', text: 'lower than the rated frequency' },
      { id: 'B', text: 'independent of the rated frequency' },
      { id: 'C', text: 'higher than the rated frequency' },
      { id: 'D', text: 'equal to the rated frequency' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Core losses (hysteresis loss $P_h \\propto f$ and eddy current loss $P_e \\propto f^2$) depend directly on frequency. Therefore, the open circuit test must be conducted at exact rated voltage and rated frequency to determine true core losses.',
    formulaConcept: 'Transformer OC Test parameters: Rated Voltage & Rated Frequency applied to LV side.',
    shortcutTrick: 'Core losses depend on frequency -> Must test at Rated Frequency.',
    commonMistake: 'Thinking test frequency does not affect iron losses.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q3',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Power Electronics',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A TRIAC (Triode for Alternating Current) is a __________ device.',
    options: [
      { id: 'A', text: 'Bilateral device' },
      { id: 'B', text: 'Unilateral device' },
      { id: 'C', text: 'One-terminal device' },
      { id: 'D', text: 'Two-terminal device' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'A TRIAC is a 3-terminal, bidirectional (bilateral) semiconductor switch equivalent to two inverse-parallel (anti-parallel) connected SCRs with a common gate, allowing conduction in both directions of AC.',
    formulaConcept: 'Power Semiconductor Switches: SCR = Unidirectional; TRIAC = Bidirectional / Bilateral.',
    shortcutTrick: 'TRIAC controls AC in BOTH directions = Bilateral.',
    commonMistake: 'Confusing SCR (unilateral) with TRIAC (bilateral).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q4',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'DC Machines',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A DC generator is running at constant speed. If the load current increases, what happens to the terminal voltage?',
    options: [
      { id: 'A', text: 'Increases' },
      { id: 'B', text: 'Decreases' },
      { id: 'C', text: 'Fluctuates randomly' },
      { id: 'D', text: 'Remains constant' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Terminal voltage $V = E_g - I_a R_a$. As load current increases, armature voltage drop ($I_a R_a$) increases and demagnetizing armature reaction weakens flux, reducing $V$.',
    formulaConcept: 'DC Generator Load Characteristics: $V = E_g - I_a R_a - \\Delta V_{\\text{brush}}$.',
    shortcutTrick: 'Higher current = Higher internal $IR$ drop $\\implies$ Terminal voltage drops.',
    commonMistake: 'Assuming speed constancy keeps terminal voltage constant.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q5',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Safety',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Why is it important for every person to follow safety procedures in the workplace?',
    options: [
      { id: 'A', text: 'To reduce operational costs significantly' },
      { id: 'B', text: 'To minimise risks and avoid accidents' },
      { id: 'C', text: 'To increase overall production efficiency' },
      { id: 'D', text: 'To limit the need for frequent supervision' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The primary purpose of workplace safety protocols and SOPs is the preservation of human life, injury prevention, and mitigation of operational hazards.',
    formulaConcept: 'Workplace Health and Safety Objectives: Accident Prevention & Hazard Elimination.',
    shortcutTrick: 'Safety = Minimise risks & prevent accidents.',
    commonMistake: 'Selecting secondary economic benefits over core human safety.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q6',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Tools',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Which of the following vices consists of a handle and a small collet chuck at one end for holding very small workpieces or drill bits?',
    options: [
      { id: 'A', text: 'Toolmaker’s vice' },
      { id: 'B', text: 'Pipe vice' },
      { id: 'C', text: 'Hand vice' },
      { id: 'D', text: 'Pin vice' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'A pin vice is a small handheld vice featuring a miniature collet chuck at the tip, used by watchmakers and instrument electricians for gripping small pins, wires, and micro-drills.',
    formulaConcept: 'Workshop Hand Tools: Bench Vice, Hand Vice, Pin Vice, Pipe Vice.',
    shortcutTrick: 'Collet chuck for pins/micro-wires = Pin Vice.',
    commonMistake: 'Confusing Pin Vice with Hand Vice or Toolmaker\'s Vice.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q7',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Wiring',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'What type of components are used for tapping in the ring main system?',
    options: [
      { id: 'A', text: 'Directly from the main supply' },
      { id: 'B', text: 'Through fuses and controlling switches' },
      { id: 'C', text: 'Through capacitors' },
      { id: 'D', text: 'Using transformers' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'In a ring main distribution system, tap-offs/sub-circuits are protected and isolated via fused connection units (FCUs) and controlling circuit breakers/switches.',
    formulaConcept: 'Electrical Installation Standards: Ring Main Wiring & Fused Tap-offs.',
    shortcutTrick: 'All sub-circuit tap-offs require protective fuses and switches.',
    commonMistake: 'Tapping directly without protective switchgear.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q8',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Power Electronics',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is a key advantage of using MOSFETs in electronic circuits compared to other types of transistors (e.g., BJTs)?',
    options: [
      { id: 'A', text: 'Ability to amplify both AC and DC signals' },
      { id: 'B', text: 'High input impedance and low power consumption' },
      { id: 'C', text: 'Ability to handle higher voltages and currents than BJTs' },
      { id: 'D', text: 'High frequency response' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Because the gate of a MOSFET is insulated by a thin silicon dioxide ($SiO_2$) layer, its steady-state gate current is virtually zero, resulting in ultra-high input impedance ($10^{12}\\,\\Omega$) and minimal gate drive power consumption.',
    formulaConcept: 'MOSFET Characteristics: Voltage-controlled device with near-infinite DC input resistance.',
    shortcutTrick: 'Insulated Gate ($SiO_2$) = Extremely high input impedance.',
    commonMistake: 'Treating MOSFET as a current-controlled device.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q9',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Alternators',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In rotating armature type alternator, magnetic field is produced by:',
    options: [
      { id: 'A', text: 'Commutator' },
      { id: 'B', text: 'DC electromagnets placed on stator' },
      { id: 'C', text: 'Slip rings on rotor' },
      { id: 'D', text: 'Slip rings and brushes' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'In a rotating armature synchronous generator, the field poles are fixed on the stationary stator and excited by DC current, while the AC armature winding rotates on the rotor shaft.',
    formulaConcept: 'Alternator Types: Rotating Field (standard large units) vs. Rotating Armature (small low-voltage units).',
    shortcutTrick: 'Rotating Armature $\\implies$ Field is on Stator.',
    commonMistake: 'Confusing rotating armature with rotating field alternators.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q10',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Drawing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Arrange the following steps in the correct order to draw an equilateral triangle with each side of 35 mm.\n1. Join CA and CB.\n2. Draw a line and mark AB 35 mm as the side of the triangle.\n3. With radius AB and center A and B, draw arcs cutting at C.\n4. ABC is the required triangle.',
    options: [
      { id: 'A', text: '1, 2, 4, 3' },
      { id: 'B', text: '2, 1, 3, 4' },
      { id: 'C', text: '2, 3, 1, 4' },
      { id: 'D', text: '3, 2, 1, 4' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Correct geometric construction procedure:\nStep 2: Draw base line segment $AB = 35\\text{ mm}$.\nStep 3: Using compass with radius $AB$, draw intersecting arcs from centers A and B to find vertex C.\nStep 1: Join line segments CA and CB.\nStep 4: ABC is the finished equilateral triangle.\nSequence: 2, 3, 1, 4.',
    formulaConcept: 'Geometric Construction of Equilateral Triangles using compass and straightedge.',
    shortcutTrick: 'Base (2) -> Arcs (3) -> Join (1) -> Complete (4).',
    commonMistake: 'Joining lines before locating intersection point C.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q11',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Capacitors',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following best describes the construction of a mica capacitor?',
    options: [
      { id: 'A', text: 'A ceramic disc with metal coatings' },
      { id: 'B', text: 'A thin polymer film rolled into a cylinder' },
      { id: 'C', text: 'A liquid electrolyte between two aluminium plates' },
      { id: 'D', text: 'Alternating layers of metal foil and mica sheets' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Mica capacitors are constructed by sandwiching sheets of natural/synthetic mica dielectric between alternating layers of metal (aluminium or silver) foil, clamped and encapsulated in resin.',
    formulaConcept: 'Capacitor Types: Mica, Ceramic, Electrolytic, Paper/Film.',
    shortcutTrick: 'Mica capacitor = Alternating layers of metal foil and mica sheets.',
    commonMistake: 'Confusing mica capacitors with rolled polymer film capacitors.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q12',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Fuses',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'Which component in a magnetic hydraulic MCB holds the ferrous plunger?',
    options: [
      { id: 'A', text: 'A non-ferrous tube' },
      { id: 'B', text: 'A bimetallic strip' },
      { id: 'C', text: 'A thermal coil' },
      { id: 'D', text: 'A fuse element' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'In a hydraulic-magnetic circuit breaker, the movable iron/ferrous plunger is sealed inside a non-ferrous (brass/copper/phosphor bronze) tube filled with silicone damping fluid to prevent magnetic shielding of the outer coil.',
    formulaConcept: 'Hydraulic-Magnetic Trip Mechanism: Solenoid surrounding a sealed non-magnetic tube with viscous dampening.',
    shortcutTrick: 'Plunger tube must be NON-FERROUS so coil flux can act on the inside plunger.',
    commonMistake: 'Confusing thermal bimetallic MCB with hydraulic magnetic MCB.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q13',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Power Electronics',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following is a fundamental characteristic of a Silicon Controlled Rectifier (SCR)?',
    options: [
      { id: 'A', text: 'It cannot control the flow of current.' },
      { id: 'B', text: 'It is a two-terminal device.' },
      { id: 'C', text: 'It has no gate terminal.' },
      { id: 'D', text: 'It is a four-layer, three-junction device.' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'A Silicon Controlled Rectifier (SCR / Thyristor) is a 4-layer ($P-N-P-N$), 3-junction ($J_1, J_2, J_3$), 3-terminal (Anode, Cathode, Gate) solid-state switch.',
    formulaConcept: 'Thyristor Structure: 4 layers (P-N-P-N), 3 junctions, 3 terminals.',
    shortcutTrick: 'SCR = 4 Layers, 3 Junctions, 3 Terminals.',
    commonMistake: 'Confusing SCR with DIAC (2-terminal) or BJT (3-layer).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q14',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Alternators',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The magnitude of dynamically induced EMF in a conductor moving in a magnetic field is given as:\n(Where: B = flux density, L = active length of conductor, V = linear velocity, and q = angle of cutting)',
    options: [
      { id: 'A', text: 'BLV Cosq' },
      { id: 'B', text: '(BV Cosq)L' },
      { id: 'C', text: 'BLV Sinq' },
      { id: 'D', text: '(BL Sinq)/V' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'According to Faraday\'s law and Lorentz force on charges: $e = B \\cdot L \\cdot v \\cdot \\sin\\theta$ (or $BLV \\sin q$), reaching maximum when moving perpendicular to magnetic field lines ($\\theta = 90^\\circ$).',
    formulaConcept: 'Dynamically Induced EMF: $e = B l v \\sin\\theta$.',
    shortcutTrick: '$e = B L V \\sin\\theta$.',
    commonMistake: 'Selecting cosine component.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q15',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Tools',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Gaskets, seals and leather/rubber spacers are made and punched out using:',
    options: [
      { id: 'A', text: 'centre punch' },
      { id: 'B', text: 'prick punch' },
      { id: 'C', text: 'hollow punch' },
      { id: 'D', text: 'pin punch' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'A hollow punch has a cylindrical cutting edge designed to punch clean circular holes in soft sheet materials like leather, rubber, gasket paper, and plastic.',
    formulaConcept: 'Workshop Punches: Centre punch ($90^\\circ$), Prick punch ($30^\\circ/60^\\circ$), Pin punch (driving pins), Hollow punch (sheet cutting).',
    shortcutTrick: 'Cutting gasket discs = Hollow Punch.',
    commonMistake: 'Selecting centre punch (used for locating drill holes).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q16',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Drawing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'According to BIS SP 46-2003, which of the following applications is correctly represented by a chain-thin line (long dash-dot) in engineering drawings?',
    options: [
      { id: 'A', text: 'Hidden edges' },
      { id: 'B', text: 'Dimension lines' },
      { id: 'C', text: 'Visible edges' },
      { id: 'D', text: 'Center lines' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Under BIS SP 46 / ISO 128 conventions:\n- Center lines & Pitch circles $\\to$ Long dash-dotted (Chain thin) lines\n- Hidden edges $\\to$ Dashed thin lines\n- Dimension lines $\\to$ Continuous thin lines\n- Visible outlines $\\to$ Continuous thick lines.',
    formulaConcept: 'Line Types in Engineering Drawing (Type G: Chain thin).',
    shortcutTrick: 'Chain thin line (dash-dot) = Center line.',
    commonMistake: 'Confusing dashed lines (hidden outlines) with chain-thin lines (center lines).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q17',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Alternators',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Alternators run at a speed _______ synchronous speed.',
    options: [
      { id: 'A', text: 'less than or greater than' },
      { id: 'B', text: 'only greater than' },
      { id: 'C', text: 'equal to' },
      { id: 'D', text: 'only less than' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Alternators (synchronous generators) operate strictly at synchronous speed: $N_s = \\frac{120 f}{P}$.',
    formulaConcept: 'Synchronous Speed Formula: $N_s = \\frac{120 f}{P}$. Slip $s = 0$ in synchronous machines.',
    shortcutTrick: 'Alternator = Synchronous machine = Equal to synchronous speed.',
    commonMistake: 'Confusing with induction motors which run below synchronous speed.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q18',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Transformers',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A transformer\'s open circuit test is used to determine:',
    options: [
      { id: 'A', text: 'core losses and no load current' },
      { id: 'B', text: 'stray loss' },
      { id: 'C', text: 'copper loss' },
      { id: 'D', text: 'windage loss' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The Open Circuit (OC) test on a transformer measures the no-load current ($I_0$) and no-load power, which represents the iron/core loss ($P_i$) and magnetizing parameters ($R_0, X_0$). Copper loss is determined by the Short Circuit (SC) test.',
    formulaConcept: 'Transformer Testing: OC Test $\\to$ Core Loss; SC Test $\\to$ Full-load Copper Loss.',
    shortcutTrick: 'OC Test = Iron / Core Loss; SC Test = Copper Loss.',
    commonMistake: 'Selecting copper loss for OC test.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q19',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Fuses',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'How long does a standard semi-enclosed fuse element take to melt when carrying twice its rated current?',
    options: [
      { id: 'A', text: '2 minutes' },
      { id: 'B', text: '5 minutes' },
      { id: 'C', text: '30 seconds' },
      { id: 'D', text: '1 minute' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'According to Indian and British electrical wiring standards (IS 2086 / BS 3036), a standard rewireable fuse wire (fusing factor $\\approx 1.4 - 2.0$) carries twice its rated current for approximately 2 minutes before reaching melting temperature.',
    formulaConcept: 'Fuse Time-Current Characteristics & Fusing Factor.',
    shortcutTrick: 'At 2x rated current, standard fuse melts in ~2 minutes.',
    commonMistake: 'Assuming instantaneous melting at 2x rated load.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q20',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Transformers',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A 20 kVA, 2500/250 V, 50 Hz, single phase transformer gave the open circuit test result (on low voltage side) as 250 V, 1.6 A and 100 W; then the no load power factor is:',
    options: [
      { id: 'A', text: '0.15' },
      { id: 'B', text: '0.1' },
      { id: 'C', text: '0.2' },
      { id: 'D', text: '0.25' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: '$W_0 = V_0 \\cdot I_0 \\cdot \\cos\\phi_0$.\n$100 = 250 \\times 1.6 \\times \\cos\\phi_0 = 400 \\times \\cos\\phi_0$.\n$\\cos\\phi_0 = \\frac{100}{400} = 0.25$.',
    formulaConcept: 'No-load Power Factor: $\\cos\\phi_0 = \\frac{W_0}{V_0 I_0}$.',
    shortcutTrick: '$100 / (250 \\times 1.6) = 100 / 400 = 0.25$.',
    commonMistake: 'Dividing kVA rating instead of test power.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q21',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Magnetism',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If two inductors are connected in series with mutual inductance M (aiding), what is the equivalent inductance?',
    options: [
      { id: 'A', text: 'Leq = (L1 + L2) / (L1 * L2)' },
      { id: 'B', text: 'Leq = L1 + L2 - 2M' },
      { id: 'C', text: 'Leq = L1 + L2 + 2M' },
      { id: 'D', text: 'Leq = (L1 + L2) / 2' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'When two series inductors are magnetically coupled such that their fluxes aid each other (series-aiding): $L_{eq} = L_1 + L_2 + 2M$. For series-opposing, $L_{eq} = L_1 + L_2 - 2M$.',
    formulaConcept: 'Coupled Series Inductance: $L_{eq} = L_1 + L_2 \\pm 2M$.',
    shortcutTrick: 'Aiding = $+2M$; Opposing = $-2M$.',
    commonMistake: 'Using $-2M$ for aiding connection.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q22',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Safety',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What should you do to ensure personal safety at work?',
    options: [
      { id: 'A', text: 'Wear personal protective equipment.' },
      { id: 'B', text: 'Take risks to finish tasks quickly.' },
      { id: 'C', text: 'Work in a hurry without checking equipment.' },
      { id: 'D', text: 'Ignore warning signs and instructions.' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 10,
    explanation: 'Wearing appropriate PPE (Personal Protective Equipment) such as insulated gloves, helmet, safety shoes, and goggles is essential to protect workers from electrical, mechanical, and chemical hazards.',
    formulaConcept: 'PPE Hierarchy of Controls in Occupational Safety.',
    shortcutTrick: 'Safety = Always wear PPE.',
    commonMistake: 'Bypassing safety rules for speed.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q23',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Alternators',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a star connected alternator, the relation between line voltage $E_L$ and phase voltage $E_{ph}$ is given by:',
    options: [
      { id: 'A', text: 'EL = 3 Eph' },
      { id: 'B', text: 'EL = √3 Eph' },
      { id: 'C', text: 'EL = Eph / 3' },
      { id: 'D', text: 'EL = Eph' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'In star (Y) connection: $E_L = \\sqrt{3} E_{ph}$ and $I_L = I_{ph}$. In delta ($\\Delta$) connection: $E_L = E_{ph}$ and $I_L = \\sqrt{3} I_{ph}$.',
    formulaConcept: '3-Phase AC Star vs Delta relationships.',
    shortcutTrick: 'Star = $\\sqrt{3} \\times$ Phase Voltage.',
    commonMistake: 'Selecting $E_L = 3 E_{ph}$ or confusing with Delta connection.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q24',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Alternators',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Low speed diesel engine alternators and hydro-generators employ rotors of __________ type.',
    options: [
      { id: 'A', text: 'cylindrical stator construction' },
      { id: 'B', text: 'rotating armature construction' },
      { id: 'C', text: 'salient pole construction' },
      { id: 'D', text: 'slip ring construction' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Salient pole rotors have projecting poles, large diameter, and short axial length, making them ideal for low-speed/medium-speed prime movers (hydro-turbines and diesel engines). High-speed turbo-alternators use non-salient (cylindrical) rotors.',
    formulaConcept: 'Rotor Types in Synchronous Machines: Salient Pole (Low Speed) vs Cylindrical (High Speed).',
    shortcutTrick: 'Low speed / Diesel / Hydro = Salient Pole.',
    commonMistake: 'Selecting cylindrical rotor (which is for high-speed steam turbo-generators).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q25',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Fuses',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'At what overload percentage does the solenoid attract the armature fully, causing instantaneous magnetic tripping in an MCB?',
    options: [
      { id: 'A', text: '1000%' },
      { id: 'B', text: '700%' },
      { id: 'C', text: '130%' },
      { id: 'D', text: '300%' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'In miniature circuit breakers (MCBs), mild overloads (113%–145%) trigger inverse-time bimetallic thermal tripping. At heavy overloads/short-circuits of approximately 700% (7 times rated current, standard Type C range 5x-10x), the electromagnetic solenoid develops sufficient force to pull the armature instantaneously.',
    formulaConcept: 'MCB Trip Characteristics: Thermal Trip (Overload 1.3x) vs Magnetic Trip (Short Circuit ~7x / 700%).',
    shortcutTrick: 'Instantaneous magnetic trip happens at high overload (700%).',
    commonMistake: 'Selecting thermal overload threshold (130%).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q26',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Batteries',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a lead-acid battery, what is the chemical composition of the active material used for the positive plate when charged?',
    options: [
      { id: 'A', text: 'Sulphuric acid (H₂SO₄)' },
      { id: 'B', text: 'Lead (Pb)' },
      { id: 'C', text: 'Lead dioxide (PbO₂)' },
      { id: 'D', text: 'Lead sulfate (PbSO₄)' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'In a charged lead-acid cell:\n- Positive plate: Lead Dioxide ($PbO_2$, dark chocolate brown)\n- Negative plate: Spongy Lead ($Pb$, slate grey)\n- Electrolyte: Dilute $H_2SO_4$.\nDuring discharge, both plates convert to Lead Sulfate ($PbSO_4$).',
    formulaConcept: 'Lead-Acid Battery Chemistry: $PbO_2 + Pb + 2H_2SO_4 \\rightleftharpoons 2PbSO_4 + 2H_2O$.',
    shortcutTrick: 'Positive = $PbO_2$ (Brown); Negative = $Pb$ (Grey).',
    commonMistake: 'Confusing positive plate ($PbO_2$) with negative plate ($Pb$).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q27',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Ohm',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the primary material used in the resistance wire of wire-wound resistors?',
    options: [
      { id: 'A', text: 'Nichrome' },
      { id: 'B', text: 'Copper' },
      { id: 'C', text: 'Silver' },
      { id: 'D', text: 'Aluminium' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Nichrome (an alloy of Nickel and Chromium) and Manganin/Constantan are used in wire-wound resistors because of their high resistivity, high melting point, and low temperature coefficient of resistance.',
    formulaConcept: 'High Resistance Alloys: Nichrome ($80\\%\\text{ Ni}, 20\\%\\text{ Cr}$), Eureka/Constantan, Manganin.',
    shortcutTrick: 'Resistance wire = Nichrome / Eureka.',
    commonMistake: 'Selecting low resistance conducting metals like Copper or Silver.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q28',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Drawing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'When selecting a sheet size for an original engineering drawing, what should be the primary consideration?',
    options: [
      { id: 'A', text: 'The size of the reproduction.' },
      { id: 'B', text: 'The clarity and resolution required.' },
      { id: 'C', text: 'The orientation of the drawing (horizontal or vertical).' },
      { id: 'D', text: 'The standard size of the drawing office.' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'According to drawing office practice (IS:962 / SP:46), the primary criterion for sheet size selection is ensuring complete clarity, readability, and necessary resolution of all components and dimensions without overcrowding.',
    formulaConcept: 'Engineering Drawing Standards: Sheet selection criteria for legibility.',
    shortcutTrick: 'Clarity and readability are paramount in technical drafting.',
    commonMistake: 'Choosing sheet size purely based on reproduction size.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q29',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Measuring',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following instruments is specifically used to test the earth resistance of an earthing system?',
    options: [
      { id: 'A', text: 'Megger' },
      { id: 'B', text: 'Clamp meter' },
      { id: 'C', text: 'Multimeter' },
      { id: 'D', text: 'Oscilloscope' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'An Earth Tester (Earth Megger) uses a hand-driven generator or DC-to-AC converter with potential and current auxiliary spikes to measure earth electrode resistance accurately without DC electrolytic polarization errors.',
    formulaConcept: 'Earth Resistance Testing: Fall-of-Potential method using Earth Megger.',
    shortcutTrick: 'Earth testing = Earth Megger.',
    commonMistake: 'Using standard multimeter which introduces contact and polarization errors.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q30',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Tools',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Which of the following files is used for filing narrow grooves, keyways and angles above 10°?',
    options: [
      { id: 'A', text: 'Knife-edge file' },
      { id: 'B', text: 'Triangular file' },
      { id: 'C', text: 'Half round file' },
      { id: 'D', text: 'Square file' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'A knife-edge file has a cross-section of a sharp wedge with an included angle of approximately $10^\\circ$, specifically designed for narrow slots, keyways, and acute angles greater than $10^\\circ$.',
    formulaConcept: 'Hand File Classification: Flat, Hand, Square, Triangular ($60^\\circ$), Knife-edge ($10^\\circ$).',
    shortcutTrick: 'Angle $\\ge 10^\\circ$ & narrow slots = Knife-edge file.',
    commonMistake: 'Selecting triangular file (which is for $60^\\circ$ corners).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q31',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Safety',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following is an important safety measure during an electrical power failure in a workshop?',
    options: [
      { id: 'A', text: 'Continuing to use equipment without verifying power status' },
      { id: 'B', text: 'Ensuring all machines and electrical equipment are turned off' },
      { id: 'C', text: 'Using candles for lighting' },
      { id: 'D', text: 'Ignoring alarm systems' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Turning off all machine switches and master breakers during an outage prevents sudden unexpected machine restarts, high inrush currents, and worker injuries when power is restored.',
    formulaConcept: 'Workshop Safety Protocols: Isolation & Lockout during power blackouts.',
    shortcutTrick: 'Power cut -> Switch OFF all machines immediately.',
    commonMistake: 'Leaving machines in "ON" state causing hazard upon sudden resumption.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q32',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'DC Machines',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A 220 V DC shunt generator has a field resistance of 110 Ω. What is the shunt field current?',
    options: [
      { id: 'A', text: '1.5 A' },
      { id: 'B', text: '10 A' },
      { id: 'C', text: '20 A' },
      { id: 'D', text: '2 A' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Shunt field current $I_{sh} = \\frac{V}{R_{sh}} = \\frac{220\\text{ V}}{110\\,\\Omega} = 2\\text{ A}$.',
    formulaConcept: 'DC Shunt Generator Circuit: $I_{sh} = \\frac{V_t}{R_{sh}}$.',
    shortcutTrick: '$220 / 110 = 2\\text{ A}$.',
    commonMistake: 'Multiplying 220 by 110.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q33',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Speed',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a velocity-time graph, a negative slope represents _____ .',
    options: [
      { id: 'A', text: 'distance' },
      { id: 'B', text: 'acceleration' },
      { id: 'C', text: 'retardation' },
      { id: 'D', text: 'displacement' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Slope of v-t graph $= \\frac{dv}{dt}$. A negative slope indicates decreasing velocity over time, which represents negative acceleration (retardation or deceleration).',
    formulaConcept: 'Kinematics: Slope of $v-t$ curve $= a = \\frac{dv}{dt}$.',
    shortcutTrick: 'Negative slope of velocity = Retardation (Deceleration).',
    commonMistake: 'Selecting distance (which is area under v-t graph).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q34',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Drawing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Non-functional dimensions (NF) in engineering drawings are _______________ .',
    options: [
      { id: 'A', text: 'derived from the values of the related features of a drawing' },
      { id: 'B', text: 'essential for the function of the space or component' },
      { id: 'C', text: 'directly derived from the values given on a drawing' },
      { id: 'D', text: 'not essential for the function of the space or component' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Non-functional dimensions (NF) are required for manufacturing and fabrication processes but do not directly govern the operational fit, clearance, or working function of the part.',
    formulaConcept: 'ISO Dimensioning Terminology: F (Functional), NF (Non-Functional), Aux (Auxiliary).',
    shortcutTrick: 'Non-functional = NOT essential for component function.',
    commonMistake: 'Confusing Non-Functional with Auxiliary reference dimensions.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q35',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Earthing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In the context of earthing in an electrical system, _______ has the greatest impact on overall earth resistance.',
    options: [
      { id: 'A', text: 'soil resistivity' },
      { id: 'B', text: 'the material of the grounding rod' },
      { id: 'C', text: 'the voltage applied to the ground' },
      { id: 'D', text: 'the length of the earthing conductor' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Earth resistance is overwhelmingly dominated by the soil resistivity ($\\rho_s$) of the surrounding earth mass (determined by moisture, soil composition, and salt content), which accounts for over 90% of the total earth loop resistance.',
    formulaConcept: 'Earth Resistance Formula: $R = \\frac{\\rho}{2\\pi L} \\ln\\left(\\frac{8L}{d}\\right)$. $R$ is directly proportional to soil resistivity $\\rho$.',
    shortcutTrick: 'Soil resistivity $\\rho$ is the single largest variable in earth resistance.',
    commonMistake: 'Assuming rod metal material dominates resistance.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q36',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Power Electronics',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'What type of device is a Unijunction Transistor (UJT)?',
    options: [
      { id: 'A', text: 'Bipolar junction device' },
      { id: 'B', text: 'Metal-oxide-semiconductor device' },
      { id: 'C', text: 'Unipolar junction device' },
      { id: 'D', text: 'Optical device' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'A UJT consists of a lightly doped N-type silicon bar with two base contacts ($B_1, B_2$) and a single heavily doped P-type emitter forming a single PN junction. Because current conduction involves both majority and minority carriers upon trigger, it is classified among bipolar junction devices in standard trade syllabi.',
    formulaConcept: 'UJT Structure & Intrinsic Standoff Ratio: $\\eta = \\frac{R_{B1}}{R_{B1} + R_{B2}}$.',
    shortcutTrick: 'UJT has 3 terminals (E, B1, B2) and 1 PN junction.',
    commonMistake: 'Confusing UJT with unipolar JFET/MOSFET.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q37',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Transformers',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A 20 kVA, 2500/250 V, 50 Hz, single phase transformer gave the open circuit test result (on low voltage side) as 250 V and 100 W; then the core loss current ($I_w$) is:',
    options: [
      { id: 'A', text: '0.3 A' },
      { id: 'B', text: '0.4 A' },
      { id: 'C', text: '0.2 A' },
      { id: 'D', text: '0.1 A' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Core loss power $W_0 = V_0 \\times I_w$.\n$I_w = \\frac{W_0}{V_0} = \\frac{100\\text{ W}}{250\\text{ V}} = 0.4\\text{ A}$.',
    formulaConcept: 'Transformer Core Loss Current Component: $I_w = I_0 \\cos\\phi_0 = \\frac{W_0}{V_0}$.',
    shortcutTrick: '$100 / 250 = 0.4\\text{ A}$.',
    commonMistake: 'Dividing 100 by the HV side voltage (2500 V).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q38',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Tools',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Which of the following hand-operated drilling machines is used for drilling small diameter holes up to 6 mm in light sheet metal and wood?',
    options: [
      { id: 'A', text: 'Breast drilling machine' },
      { id: 'B', text: 'Bevel gear type drilling machine' },
      { id: 'C', text: 'Ratchet drilling machine' },
      { id: 'D', text: 'Electric hand drill' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'A hand-operated bevel gear type drilling machine (hand drill) is compact, light, and specifically rated for drilling small holes up to 6 mm diameter.',
    formulaConcept: 'Hand Drilling Equipment: Hand drill (bevel gear, up to 6 mm), Breast drill (up to 12 mm), Ratchet brace (heavy structural drilling).',
    shortcutTrick: 'Holes up to 6 mm = Bevel gear hand drill.',
    commonMistake: 'Selecting breast drill (which is for larger bits up to 12 mm).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q39',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Safety',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the primary reason for electrical injuries when a person comes in contact with electrical equipment?',
    options: [
      { id: 'A', text: 'Electrical devices are too powerful.' },
      { id: 'B', text: 'Electrical equipment is not properly grounded.' },
      { id: 'C', text: 'Devices are used for too long.' },
      { id: 'D', text: 'Current flows through the body causing harm.' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Electrical shocks, burns, ventricular fibrillation, and electrocution occur directly because an electric current traverses human body tissues, disrupting nervous and cardiac signals.',
    formulaConcept: 'Physiological effects of electric current: $I = V / R_{\\text{body}}$. Current magnitude determines shock severity.',
    shortcutTrick: 'Harm is caused by CURRENT flowing through human tissue.',
    commonMistake: 'Attributing shock solely to voltage without current flow.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q40',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Ohm',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A circuit consists of three resistors: 15 ohms, 10 ohms, and 20 ohms. The 15-ohm resistor is in series with the parallel combination of the 10-ohm and 20-ohm resistors. If a 24 V battery is applied across the circuit, what is the total current flowing through the circuit?',
    options: [
      { id: 'A', text: '2.1 A' },
      { id: 'B', text: '1.1 A' },
      { id: 'C', text: '0.1 A' },
      { id: 'D', text: '3.1 A' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: '1. Parallel combination of $10\\,\\Omega$ and $20\\,\\Omega$:\n$R_p = \\frac{10 \\times 20}{10 + 20} = \\frac{200}{30} = 6.67\\,\\Omega$.\n2. Total circuit resistance:\n$R_{\\text{total}} = 15 + 6.67 = 21.67\\,\\Omega$.\n3. Total current:\n$I = \\frac{V}{R_{\\text{total}}} = \\frac{24}{21.67} = 1.107\\text{ A} \\approx 1.1\\text{ A}$.',
    formulaConcept: 'Series-Parallel DC Circuit Analysis.',
    shortcutTrick: '$24 / 21.67 \\approx 1.1\\text{ A}$.',
    commonMistake: 'Summing all three in series ($45\\,\\Omega \\implies 0.53\\text{ A}$).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q41',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Transformers',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The magnetic permeability ($\\mu$) of an ideal transformer core is equal to:',
    options: [
      { id: 'A', text: 'infinite' },
      { id: 'B', text: 'unity' },
      { id: 'C', text: 'low value' },
      { id: 'D', text: 'zero' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'An ideal transformer core has infinite permeability ($\\mu = \\infty$), meaning zero reluctance ($\\mathcal{R} = 0$), so zero magnetizing current is required to establish flux in the core.',
    formulaConcept: 'Properties of Ideal Transformer: $\\mu = \\infty$, Reluctance $= 0$, Winding resistance $= 0$, Core loss $= 0$.',
    shortcutTrick: 'Ideal Core = Infinite Permeability & Zero Reluctance.',
    commonMistake: 'Selecting unity (1) instead of infinite.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q42',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'AC',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a three-phase balanced system, if the load is purely resistive, the phase current is ___________ .',
    options: [
      { id: 'A', text: '90° ahead of the line voltage' },
      { id: 'B', text: '90° behind the line voltage' },
      { id: 'C', text: 'unrelated to the line voltage' },
      { id: 'D', text: 'in phase with the phase voltage' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'In any purely resistive circuit, the current and voltage waveforms reach peaks and zeroes simultaneously, meaning current is in phase with voltage (power factor $\\cos\\phi = 1$, phase angle $\\phi = 0^\\circ$).',
    formulaConcept: 'Pure Resistive AC Circuit: Phase angle $\\phi = 0^\\circ$, Power Factor $= 1.0$.',
    shortcutTrick: 'Resistive = In-phase.',
    commonMistake: 'Confusing with inductive (lagging by 90°) or capacitive (leading by 90°) loads.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q43',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Earthing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Read the given statements carefully:\n\nStatement 1: Plate earthing ensures a low-resistance path for fault current to safely flow into the earth.\nStatement 2: The resistance of the earthing system is not affected by the soil type or moisture content.',
    options: [
      { id: 'A', text: 'Statement 1 is correct, but Statement 2 is incorrect.' },
      { id: 'B', text: 'Both Statement 1 and Statement 2 are incorrect.' },
      { id: 'C', text: 'Statement 1 is incorrect, but Statement 2 is correct.' },
      { id: 'D', text: 'Both Statement 1 and Statement 2 are correct.' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Statement 1 is correct (earthing safely diverts fault currents). Statement 2 is completely incorrect because soil resistivity depends heavily on soil moisture, chemical composition, and temperature.',
    formulaConcept: 'Earthing Principles & Factors affecting earth electrode resistance.',
    shortcutTrick: 'Soil moisture directly alters earth resistance $\\implies$ Statement 2 is false.',
    commonMistake: 'Assuming earth resistance is an invariant constant.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q44',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Ohm',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If the current flowing through a conductor is 5 A and the resistance of the conductor is 10 ohms, what will be the voltage across the conductor, according to Ohm\'s Law?',
    options: [
      { id: 'A', text: '5 V' },
      { id: 'B', text: '50 V' },
      { id: 'C', text: '10 V' },
      { id: 'D', text: '15 V' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 10,
    explanation: 'Ohm\'s Law: $V = I \\times R = 5\\text{ A} \\times 10\\,\\Omega = 50\\text{ V}$.',
    formulaConcept: 'Ohm\'s Law: $V = I \\cdot R$.',
    shortcutTrick: '$5 \\times 10 = 50\\text{ V}$.',
    commonMistake: 'Dividing 10 by 5.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q45',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Magnetism',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'When a strong permanent magnet is brought close to a weak magnet with similar orientation, what will likely happen?',
    options: [
      { id: 'A', text: 'The strong magnet will lose its magnetism.' },
      { id: 'B', text: 'The strong magnet will induce magnetism in the weak magnet.' },
      { id: 'C', text: 'The weak magnet will disappear.' },
      { id: 'D', text: 'The weak magnet will repel the strong magnet.' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'A strong magnetic field aligns magnetic domains in adjacent ferromagnetic materials or weaker magnets, inducing stronger aligned magnetic dipoles via magnetic induction.',
    formulaConcept: 'Magnetic Induction & Domain Theory of Magnetism.',
    shortcutTrick: 'Strong fields induce alignment in weaker magnetic domains.',
    commonMistake: 'Assuming the strong magnet loses its field.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q46',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'DC Machines',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'What is the effect of increasing the field current in a DC shunt motor?',
    options: [
      { id: 'A', text: 'The motor speed decreases.' },
      { id: 'B', text: 'The motor speed increases.' },
      { id: 'C', text: 'The motor stops immediately.' },
      { id: 'D', text: 'The torque decreases.' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Motor speed $N = \\frac{V - I_a R_a}{k \\Phi}$. Increasing field current ($I_f$) increases magnetic flux per pole ($\\Phi$). Since speed is inversely proportional to flux ($N \\propto \\frac{1}{\\Phi}$), the motor speed decreases.',
    formulaConcept: 'DC Motor Speed Equation: $N \\propto \\frac{E_b}{\\Phi}$.',
    shortcutTrick: 'More flux $\\Phi \\implies$ Lower speed $N$.',
    commonMistake: 'Assuming higher field current speeds up the motor.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q47',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Tools',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which part of an engineer\'s hand file is fitted onto the tang for safely gripping and holding the file?',
    options: [
      { id: 'A', text: 'Edge' },
      { id: 'B', text: 'Handle' },
      { id: 'C', text: 'Tang' },
      { id: 'D', text: 'Tip or Point' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The wooden or plastic handle is fitted over the pointed tang of the file to provide safe handling and avoid hand injury from the sharp tang.',
    formulaConcept: 'Parts of an Engineer\'s File: Tip/Point, Face, Edge, Heel, Shoulder, Tang, Handle.',
    shortcutTrick: 'Handle fits over the tang.',
    commonMistake: 'Confusing tang (metal end) with handle.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q48',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Capacitors',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Where are ceramic capacitors commonly used in electronic engineering?',
    options: [
      { id: 'A', text: 'High-power motors' },
      { id: 'B', text: 'Transformers' },
      { id: 'C', text: 'Mobile Phones' },
      { id: 'D', text: 'TV circuits' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Ceramic capacitors offer high stability, low parasitics, and excellent high-frequency characteristics, making them standard for RF bypassing, filtering, and tuning in TV and radio circuits.',
    formulaConcept: 'Capacitor Applications by Dielectric Type.',
    shortcutTrick: 'High-frequency bypass in TV/RF = Ceramic capacitor.',
    commonMistake: 'Selecting heavy power motors which use electrolytic/oil capacitors.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q49',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Safety',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following organisations is responsible for formulating and enforcing workplace safety regulations in factories and ports in India?',
    options: [
      { id: 'A', text: 'World Health Organization (WHO)' },
      { id: 'B', text: 'Food and Drug Administration (FDA)' },
      { id: 'C', text: 'Directorate General of Factory Advice Service and Labour Institutes (DGFASLI)' },
      { id: 'D', text: 'Environmental Protection Agency (EPA)' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'DGFASLI (attached office of Ministry of Labour & Employment, Govt of India) serves as the national technical arm for occupational safety and health in factories and docks.',
    formulaConcept: 'Indian Occupational Safety Statutory Bodies.',
    shortcutTrick: 'Factories safety in India = DGFASLI.',
    commonMistake: 'Selecting international or US agencies (WHO, EPA, FDA).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q50',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Drawing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A drawing instrument box is used to carry all ______________ instruments.',
    options: [
      { id: 'A', text: 'screening' },
      { id: 'B', text: 'drilling' },
      { id: 'C', text: 'drawing' },
      { id: 'D', text: 'casting' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 10,
    explanation: 'A drawing instrument box contains compasses, dividers, lengthener bars, ruling pens, and lead cases for engineering drawing.',
    formulaConcept: 'Engineering Drawing Tools & Equipment.',
    shortcutTrick: 'Instrument box = drawing instruments.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q51',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Tools',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the primary advantage of giving heat treatment (hardening and tempering) to a cutting tool material?',
    options: [
      { id: 'A', text: 'To make surgical knives of sharp edges' },
      { id: 'B', text: 'To increase the weight of the material' },
      { id: 'C', text: 'To decrease the melting point of the material' },
      { id: 'D', text: 'To change it from one element to another element' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Heat treatment processes (hardening, quenching, tempering) optimize hardness, wear resistance, and edge retention, allowing tools like surgical scalpels and blades to hold extremely sharp cutting edges.',
    formulaConcept: 'Metallurgy & Heat Treatment of Steels: Hardening, Tempering, Annealing, Normalising.',
    shortcutTrick: 'Heat treatment imparts hardness and sharp edge retention.',
    commonMistake: 'Believing heat treatment changes elemental identity.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q52',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Drawing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'For what purpose are drawing pins and clips used in engineering drawings?',
    options: [
      { id: 'A', text: 'To fasten the drawing sheet on to the drawing board firmly so that it does not shake' },
      { id: 'B', text: 'To draw horizontal lines, parallel lines and to guide/hold the set squares' },
      { id: 'C', text: 'To transfer dimensions and dividing lines into a number of equal parts' },
      { id: 'D', text: 'To support the drawing paper/tracing paper for making drawings' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Drawing pins, drafting tape, and spring clips secure the drawing sheet firmly to the drafting board to prevent movement during drafting.',
    formulaConcept: 'Drafting Board Accessories and Sheet Fastening.',
    shortcutTrick: 'Pins & clips = Fasten drawing sheet firmly.',
    commonMistake: 'Confusing with T-square (which draws horizontal lines).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q53',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Algebra',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'If $\\sin\\theta = \\frac{3}{5}$, find $\\cos\\theta$.',
    options: [
      { id: 'A', text: '5/4' },
      { id: 'B', text: '3/5' },
      { id: 'C', text: '4/5' },
      { id: 'D', text: '3/4' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: '$\\cos\\theta = \\sqrt{1 - \\sin^2\\theta} = \\sqrt{1 - \\left(\\frac{3}{5}\\right)^2} = \\sqrt{1 - \\frac{9}{25}} = \\sqrt{\\frac{16}{25}} = \\frac{4}{5}$.',
    formulaConcept: 'Fundamental Trigonometric Identity: $\\sin^2\\theta + \\cos^2\\theta = 1$. (3-4-5 Pythagorean triplet).',
    shortcutTrick: '3-4-5 right triangle: Opposite=3, Hypotenuse=5 $\\implies$ Adjacent=4 $\\implies \\cos\\theta = 4/5$.',
    commonMistake: 'Writing $\\tan\\theta = 3/4$ instead of $\\cos\\theta$.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q54',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Power Electronics',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the primary application of a Unijunction Transistor (UJT) in power electronic circuits?',
    options: [
      { id: 'A', text: 'Frequency modulation' },
      { id: 'B', text: 'Triggering of SCRs and TRIACs' },
      { id: 'C', text: 'Voltage regulation' },
      { id: 'D', text: 'Amplification of signals' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Due to its negative resistance characteristic, the UJT is predominantly configured as a relaxation oscillator to generate synchronized gate firing pulses for triggering SCRs and TRIACs.',
    formulaConcept: 'UJT Relaxation Oscillator: Pulse generation for thyristor phase control.',
    shortcutTrick: 'UJT = Relaxation oscillator to trigger SCR / TRIAC.',
    commonMistake: 'Treating UJT as a linear amplifier.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q55',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Mensuration',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A circular hole of radius 3 cm is cut from a rectangular sheet of dimensions 12 cm × 10 cm. Find the remaining area (Take $\\pi = 3.14$).',
    options: [
      { id: 'A', text: '95.86 cm²' },
      { id: 'B', text: '100 cm²' },
      { id: 'C', text: '75.74 cm²' },
      { id: 'D', text: '91.74 cm²' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: '1. Area of rectangle $= 12 \\times 10 = 120\\text{ cm}^2$.\n2. Area of circle $= \\pi r^2 = 3.14 \\times 3^2 = 3.14 \\times 9 = 28.26\\text{ cm}^2$.\n3. Remaining Area $= 120 - 28.26 = 91.74\\text{ cm}^2$.',
    formulaConcept: 'Composite Planar Area: $A_{\\text{rem}} = A_{\\text{rect}} - A_{\\text{circle}}$.',
    shortcutTrick: '$120 - 28.26 = 91.74\\text{ cm}^2$.',
    commonMistake: 'Using diameter instead of radius for circle area.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q56',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Power Electronics',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'What happens if the gate trigger current is removed while a TRIAC is in the conducting state?',
    options: [
      { id: 'A', text: 'The TRIAC will not be affected.' },
      { id: 'B', text: 'The TRIAC will remain conducting until the current falls below the holding current.' },
      { id: 'C', text: 'The TRIAC will stop conducting immediately.' },
      { id: 'D', text: 'The TRIAC will behave like a short circuit permanently.' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Once latched (anode current exceeding latching current $I_L$), thyristor family devices like TRIACs remain fully conducting regardless of gate signal removal until the principal current drops below the holding current ($I_H$).',
    formulaConcept: 'Latching Current ($I_L$) vs. Holding Current ($I_H$) in Thyristors.',
    shortcutTrick: 'Gate loses control after firing; conduction continues until current $< I_H$.',
    commonMistake: 'Thinking thyristors turn off instantly when gate current ceases (like transistors).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q57',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Magnetism',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Air-cored inductors are most commonly used in circuits operating at/in:',
    options: [
      { id: 'A', text: 'high frequencies from 1 MHz to several hundred MHz' },
      { id: 'B', text: 'audio frequency range (20 Hz – 20 kHz)' },
      { id: 'C', text: 'low frequencies below 50 Hz' },
      { id: 'D', text: 'DC power supply circuits' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Air-cored inductors eliminate magnetic core losses (hysteresis and eddy currents) and core saturation at very high radio frequencies (RF: 1 MHz to hundreds of MHz).',
    formulaConcept: 'Inductor Core Selection: Iron core (Low frequency/50 Hz), Ferrite (Medium/RF), Air core (Very high RF).',
    shortcutTrick: 'Air core = No core losses = High frequencies (MHz).',
    commonMistake: 'Selecting low 50 Hz power frequencies where iron cores are needed for large inductance.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q58',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'AC',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Which of the following options is correct regarding balanced three-phase systems?\n\nStatement 1: In a balanced three-phase system, the power delivered to the load depends on both the phase current and the phase voltage.\nStatement 2: The line voltage in a star-connected system is always greater than the phase voltage by a factor of √3.',
    options: [
      { id: 'A', text: 'Both Statement 1 and Statement 2 are true.' },
      { id: 'B', text: 'Statement 1 is true, and Statement 2 is false.' },
      { id: 'C', text: 'Statement 1 is false, and Statement 2 is true.' },
      { id: 'D', text: 'Both Statement 1 and Statement 2 are false.' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Statement 1 is true: $P = 3 V_{ph} I_{ph} \\cos\\phi$. Statement 2 is true: for star connection, $V_L = \\sqrt{3} V_{ph} \\approx 1.732 V_{ph} > V_{ph}$.',
    formulaConcept: '3-Phase Power Formula: $P = 3 V_{ph} I_{ph} \\cos\\phi = \\sqrt{3} V_L I_L \\cos\\phi$.',
    shortcutTrick: 'Both statements represent fundamental 3-phase AC laws.',
    commonMistake: 'Confusing line voltage relation in Delta with Star.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q59',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Tools',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following types of pliers is used to shape loops in electrical wires and to form curves in light metal strips?',
    options: [
      { id: 'A', text: 'Flat nose pliers' },
      { id: 'B', text: 'End cutting pliers' },
      { id: 'C', text: 'Round nose pliers' },
      { id: 'D', text: 'Slip-joint pliers' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Round nose pliers have tapering round conical jaws specifically designed to bend wire ends into eyelets/loops for terminal screw connections and form curves in thin sheets.',
    formulaConcept: 'Electrician Pliers Types: Combination, Flat nose, Round nose, Side cutting, Long nose.',
    shortcutTrick: 'Round jaws = Form circular wire loops.',
    commonMistake: 'Selecting flat nose pliers (which form square bends).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q60',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Measuring',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'When measuring the resistance of a resistor using an ohmmeter, what does a reading of zero resistance ($0\\,\\Omega$) indicate?',
    options: [
      { id: 'A', text: 'The ohmmeter is malfunctioning.' },
      { id: 'B', text: 'The resistor is open-circuited.' },
      { id: 'C', text: 'The resistor is functioning normally.' },
      { id: 'D', text: 'The resistor is short-circuited.' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'A reading of zero ohms across a component that should possess resistance indicates a short circuit (zero resistance path). An open circuit reads infinite resistance ($\\infty$).',
    formulaConcept: 'Ohmmeter Fault Diagnostics: $0\\,\\Omega = \\text{Short Circuit}$; $\\infty\\,\\Omega = \\text{Open Circuit}$.',
    shortcutTrick: '$0\\,\\Omega = \\text{Short}$; $\\infty = \\text{Open}$.',
    commonMistake: 'Confusing zero resistance with open circuit.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q61',
  },
  {
    subjectCode: 'RRB_ALP_MATH',
    topicKeyword: 'Fractions',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the sum of $\\left(\\frac{3}{8}\\right) + \\left(\\frac{5}{12}\\right)$?',
    options: [
      { id: 'A', text: '7/12' },
      { id: 'B', text: '17/24' },
      { id: 'C', text: '8/20' },
      { id: 'D', text: '19/24' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'LCM of 8 and 12 is 24.\n$\\frac{3 \\times 3}{24} + \\frac{5 \\times 2}{24} = \\frac{9 + 10}{24} = \\frac{19}{24}$.',
    formulaConcept: 'Addition of fractions using Lowest Common Multiple (LCM).',
    shortcutTrick: '$(9 + 10) / 24 = 19/24$.',
    commonMistake: 'Adding numerators and denominators directly ($(3+5)/(8+12) = 8/20$).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q62',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'DC Machines',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the main purpose of continuity testing in a DC generator?',
    options: [
      { id: 'A', text: 'To check voltage regulation' },
      { id: 'B', text: 'To detect open or broken windings' },
      { id: 'C', text: 'To test insulation resistance' },
      { id: 'D', text: 'To measure current flow' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'A continuity test using a test lamp or multimeter verifies whether an electrical path is complete and uninterrupted, identifying broken conductors or open-circuited field/armature coils.',
    formulaConcept: 'Electrical Machine Diagnostics: Continuity Test (Open circuits) vs Insulation Test (Megger).',
    shortcutTrick: 'Continuity = Checks for unbroken circuit (detects open circuits).',
    commonMistake: 'Confusing continuity test with insulation resistance test.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q63',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Earthing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following statements is NOT true if an electrical system is not properly earthed?',
    options: [
      { id: 'A', text: 'It may lead to damage of electrical equipment.' },
      { id: 'B', text: 'It can increase the risk of electric shock.' },
      { id: 'C', text: 'It provides constant voltage supply regardless of perturbation in load side.' },
      { id: 'D', text: 'It may cause the electric current to flow in an uncontrolled manner.' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Earthing does NOT regulate or maintain constant load voltage. Its sole purpose is protective safety, voltage stabilization relative to ground, and fault current diversion.',
    formulaConcept: 'Objectives of Equipment Earthing: Human shock protection, Lightning discharge, Fault clearance.',
    shortcutTrick: 'Earthing provides safety, not load voltage regulation.',
    commonMistake: 'Assuming earthing acts as an active voltage regulator.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q64',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Safety',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the primary objective of an emergency evacuation plan in an industrial facility?',
    options: [
      { id: 'A', text: 'To increase productivity' },
      { id: 'B', text: 'To ensure safe and orderly evacuation during emergencies' },
      { id: 'C', text: 'To allow workers to leave early' },
      { id: 'D', text: 'To avoid safety drills' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 10,
    explanation: 'An Emergency Evacuation Plan maps egress routes, assembly points, and warden roles to ensure life safety through quick, orderly exit during fires, gas leaks, or explosions.',
    formulaConcept: 'Industrial Safety & Disaster Management Protocols.',
    shortcutTrick: 'Evacuation plan = Safe and orderly evacuation during crisis.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q65',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Earthing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following is a key safety measure to follow when installing an earthing system?',
    options: [
      { id: 'A', text: 'Ensure the earthing system is properly inspected and tested for safety compliance.' },
      { id: 'B', text: 'Use flexible conductors for earthing connections.' },
      { id: 'C', text: 'Use thin copper wires for earthing to reduce costs.' },
      { id: 'D', text: 'Ensure the earthing system is designed for maximum efficiency.' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Under Indian Electricity Rules (IE Rule 61 / IS 3043), newly installed grounding systems must undergo formal testing with an Earth Megger to verify resistance ($< 1\\,\\Omega$ for substations, $< 5\\,\\Omega$ for domestic/commercial) before commissioning.',
    formulaConcept: 'Statutory Earthing Inspection & Earth Resistance Thresholds.',
    shortcutTrick: 'Inspect and test for regulatory safety compliance.',
    commonMistake: 'Using undersized earthing conductors to save cost.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q66',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Earthing',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'IEEE Standard 80 provides international recommendations and guidelines for ______ .',
    options: [
      { id: 'A', text: 'voltage regulation in power systems' },
      { id: 'B', text: 'measurement of electrical power consumption' },
      { id: 'C', text: 'proper installation of grounding and bonding systems in electrical installations' },
      { id: 'D', text: 'standards for electrical insulation materials' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'IEEE Standard 80 is the universally recognized \'Guide for Safety in AC Substation Grounding\', establishing design formulas for earth grid resistance, step potential, and touch potential.',
    formulaConcept: 'IEEE 80 Substation Grounding Standard: Step and Touch Potential Safety Criteria.',
    shortcutTrick: 'IEEE 80 = Substation Grounding & Earthing Grid Standard.',
    commonMistake: 'Confusing IEEE 80 with IEEE 519 (Harmonics) or IEEE C57 (Transformers).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q67',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'DC Machines',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Why is armature resistance control (rheostatic control) NOT suitable for speed control in high-power DC motors?',
    options: [
      { id: 'A', text: 'It causes high torque fluctuations.' },
      { id: 'B', text: 'It increases field current.' },
      { id: 'C', text: 'It results in poor efficiency due to high power loss.' },
      { id: 'D', text: 'It cannot reduce the motor speed.' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'In armature rheostatic control, the full armature current ($I_a$) flows through the external series resistance, dissipating massive power as heat ($I_a^2 R_{\\text{ext}}$), resulting in extremely low operating efficiency and requiring large heat dissipators.',
    formulaConcept: 'Armature Speed Control: $N = \\frac{V - I_a(R_a + R_{\\text{ext}})}{k\\Phi}$. Power loss $= I_a^2 R_{\\text{ext}}$.',
    shortcutTrick: 'Large current through rheostat = Massive $I^2R$ power loss = Poor efficiency.',
    commonMistake: 'Assuming speed cannot be lowered by rheostat.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q68',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Measuring',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'When using a multimeter / ammeter to measure electric current, which of the following connections is correct?',
    options: [
      { id: 'A', text: 'The multimeter is connected directly to the power source.' },
      { id: 'B', text: 'The multimeter is connected only across resistive components.' },
      { id: 'C', text: 'The multimeter is connected in parallel with the load.' },
      { id: 'D', text: 'The multimeter is connected in series with the load.' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'An ammeter has near-zero internal resistance and must be connected in series with the load to measure the total circuit current. Connecting an ammeter in parallel creates a short-circuit fault.',
    formulaConcept: 'Meter Connections: Ammeter in SERIES (low $R_m$), Voltmeter in PARALLEL (high $R_v$).',
    shortcutTrick: 'Current = Series connection.',
    commonMistake: 'Connecting ammeter in parallel (which blows internal fuse).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q69',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'DC Machines',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the basic working principle of a DC generator?',
    options: [
      { id: 'A', text: 'Mutual induction' },
      { id: 'B', text: 'Lenz’s law' },
      { id: 'C', text: 'Faraday’s law of electromagnetic induction' },
      { id: 'D', text: 'Electrostatic induction' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'All generators operate on Faraday\'s Law of Electromagnetic Induction: whenever a conductor moves and cuts magnetic flux lines, an electromotive force (EMF) is dynamically induced in it.',
    formulaConcept: 'Faraday\'s Law of Induction: $e = -N \\frac{d\\Phi}{dt} = B l v \\sin\\theta$.',
    shortcutTrick: 'Generator converts mechanical to electrical via Faraday\'s Law.',
    commonMistake: 'Confusing with Transformer which uses mutual induction.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q70',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'AC',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a balanced star-connected 3-phase AC system, the neutral point ___________.',
    options: [
      { id: 'A', text: 'carries current even in balanced loading conditions' },
      { id: 'B', text: 'is always at a voltage equal to any phase' },
      { id: 'C', text: 'is at a higher constant voltage relative to the ground' },
      { id: 'D', text: 'is at zero potential with respect to all phases' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Under balanced 3-phase loading, the vector sum of line currents is zero ($\\vec{I}_R + \\vec{I}_Y + \\vec{I}_B = 0$). Consequently, neutral current is zero ($I_N = 0$) and the neutral star point sits at zero electrical potential.',
    formulaConcept: 'Balanced 3-Phase Star Neutral: $I_N = 0\\text{ A}$, $V_N = 0\\text{ V}$.',
    shortcutTrick: 'Balanced load = Zero neutral current and Zero neutral potential.',
    commonMistake: 'Assuming neutral carries current in balanced state.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q71',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Fuses',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Where are Kit-Kat type (rewireable) porcelain fuses commonly used?',
    options: [
      { id: 'A', text: 'Power generation plants' },
      { id: 'B', text: 'Domestic and small industrial electrical circuits' },
      { id: 'C', text: 'Electronic circuits' },
      { id: 'D', text: 'High-voltage transmission systems' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Kit-Kat (semi-enclosed rewireable porcelain) fuses are standard protective devices in low-voltage domestic, commercial, and small industrial installations up to 415 V / 200 A.',
    formulaConcept: 'Fuse Categories: Rewireable (Kit-Kat), Cartridge, HRC (High Rupturing Capacity).',
    shortcutTrick: 'Kit-Kat fuses = Domestic and small industrial circuits.',
    commonMistake: 'Thinking Kit-Kat fuses are used in high-voltage grids.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q72',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'AC',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A three-phase AC circuit is connected with a star-connected balanced load of 100 Ω per phase. If the phase voltage of each phase is 200 V, the current in each phase will be ____ .',
    options: [
      { id: 'A', text: '0.5 A' },
      { id: 'B', text: '4 A' },
      { id: 'C', text: '2 A' },
      { id: 'D', text: '1 A' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Phase current $I_{ph} = \\frac{V_{ph}}{Z_{ph}} = \\frac{200\\text{ V}}{100\\,\\Omega} = 2\\text{ A}$.',
    formulaConcept: '3-Phase Star Ohm\'s Law: $I_{ph} = \\frac{V_{ph}}{Z_{ph}}$.',
    shortcutTrick: '$200 / 100 = 2\\text{ A}$.',
    commonMistake: 'Dividing by $\\sqrt{3}$ unnecessarily when phase voltage is already given.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q73',
  },
  {
    subjectCode: 'RRB_ALP_TRADE',
    topicKeyword: 'Fuses',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Which of the following factors DOES NOT affect the current carrying capacity / rating of a fuse wire?',
    options: [
      { id: 'A', text: 'The cross-sectional area of the conductor' },
      { id: 'B', text: 'The type of electrical load' },
      { id: 'C', text: 'The ambient temperature' },
      { id: 'D', text: 'The colour of the fuse holder' },
    ],
    correctAnswers: ['D'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'Fuse fusing current ($I = k \\cdot d^{1.5}$) depends on fuse wire diameter, material composition, wire length, thermal enclosure, and ambient temperature. The external color of the porcelain or plastic holder has zero electrical effect.',
    formulaConcept: 'Preece\'s Law for Fuses: $I = k d^{1.5}$.',
    shortcutTrick: 'Color of plastic/ceramic body has no electrical impact.',
    commonMistake: 'None.',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q74',
  },
  {
    subjectCode: 'RRB_ALP_SCIENCE',
    topicKeyword: 'Units',
    year: 2024,
    shift: 'Shift 1',
    paper: 'CEN 01/2024 Part-B',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The unit for specific gravity (relative density) is _____ .',
    options: [
      { id: 'A', text: 'no unit (dimensionless)' },
      { id: 'B', text: 'm/s²' },
      { id: 'C', text: 'kg/m³' },
      { id: 'D', text: 'g/cm³' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 10,
    explanation: 'Specific Gravity is the dimensionless ratio of the density of a substance to the density of pure water at $4^\\circ\\text{C}$: $\\text{SG} = \\frac{\\rho_{\\text{substance}}}{\\rho_{\\text{water}}}$. Being a ratio of identical units, it is unitless.',
    formulaConcept: 'Relative Density / Specific Gravity $= \\frac{\\rho}{\\rho_{\\text{ref}}}$.',
    shortcutTrick: 'Ratio of two densities = No units.',
    commonMistake: 'Selecting density units ($\\text{kg/m}^3$).',
    sourceRef: 'RRB ALP CEN 01/2024 Part-B Q75',
  },
];
