import { RawQuestionData } from './gateQuestions.js';

export const rrbJeQuestions: RawQuestionData[] = [
  // --- 2024 ---
  {
    subjectCode: 'RRB_JE_MACHINES',
    topicKeyword: 'Induction',
    year: 2024,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A 4-pole, 50 Hz, 3-phase induction motor operates at a full load speed of 1440 RPM. What is the rotor slip frequency (in Hz)?',
    options: [
      { id: 'A', text: '1 Hz' },
      { id: 'B', text: '2 Hz' },
      { id: 'C', text: '2.5 Hz' },
      { id: 'D', text: '5 Hz' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 30,
    explanation: 'Synchronous speed $N_s = \\frac{120 \\times f}{P} = \\frac{120 \\times 50}{4} = 1500\\text{ RPM}$.\nRotor slip $s = \\frac{N_s - N}{N_s} = \\frac{1500 - 1440}{1500} = \\frac{60}{1500} = 0.04$ (4%).\nRotor frequency $f_r = s \\times f = 0.04 \\times 50 = 2.0\\text{ Hz}$.',
    formulaConcept: '$N_s = \\frac{120 f}{P}, \\quad s = \\frac{N_s - N}{N_s}, \\quad f_r = s \\cdot f$',
    shortcutTrick: '$\\Delta N = 1500 - 1440 = 60$. Slip frequency $f_r = \\frac{60}{1500} \\times 50 = \\frac{60}{30} = 2\\text{ Hz}$.',
    commonMistake: 'Directly multiplying 1440 by frequency instead of calculating slip first.',
    sourceRef: 'RRB JE 2024 CBT-2 Shift 1',
  },
  {
    subjectCode: 'RRB_JE_MEAS',
    topicKeyword: 'Two-Wattmeter',
    year: 2024,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'HARD',
    questionText: 'In the two-wattmeter method used to measure power in a balanced 3-phase load, one wattmeter reads zero ($W_1 = P, W_2 = 0$). What is the power factor of the load?',
    options: [
      { id: 'A', text: '1.0 (Unity)' },
      { id: 'B', text: '0.866' },
      { id: 'C', text: '0.5' },
      { id: 'D', text: '0.0 (Zero)' },
    ],
    correctAnswers: ['C'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 40,
    explanation: 'Formula for power factor angle in 2-wattmeter method:\n$\\tan \\phi = \\sqrt{3} \\frac{W_1 - W_2}{W_1 + W_2}$.\nWhen $W_2 = 0$:\n$\\tan \\phi = \\sqrt{3} \\frac{W_1}{W_1} = \\sqrt{3} \\implies \\phi = 60^\\circ$.\nPower factor $\\cos \\phi = \\cos 60^\\circ = 0.5$.',
    formulaConcept: '$\\tan \\phi = \\sqrt{3}\\frac{W_1 - W_2}{W_1 + W_2}, \\quad \\text{pf} = \\cos \\phi$',
    shortcutTrick: '3 Key Cases: W1=W2 => pf=1.0; One reads 0 => pf=0.5; W1=-W2 => pf=0.',
    commonMistake: 'Assuming zero wattmeter reading implies zero power factor.',
    sourceRef: 'RRB JE 2024 CBT-2 Shift 2',
  },
  {
    subjectCode: 'RRB_JE_CIRCUITS',
    topicKeyword: 'Network Theorems',
    year: 2024,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Maximum Power Transfer Theorem states that maximum power is transferred from a source to a load when load resistance $R_L$ is equal to:',
    options: [
      { id: 'A', text: 'Thevenin equivalent resistance of the source ($R_{th}$)' },
      { id: 'B', text: 'Zero ohms' },
      { id: 'C', text: 'Infinite ohms' },
      { id: 'D', text: 'Half of the internal resistance' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'For maximum power transfer in DC circuits, $R_L = R_{th}$. Under this matched condition, maximum power transferred is $P_{\\max} = \\frac{V_{th}^2}{4 R_{th}}$, and transfer efficiency is exactly 50%.',
    formulaConcept: '$P_{\\max} = \\frac{V_{th}^2}{4 R_{th}}, \\quad \\eta = 50\\%$',
    shortcutTrick: 'Efficiency at max power is 50%, not 100%!',
    commonMistake: 'Thinking max power gives 100% efficiency.',
    sourceRef: 'RRB JE 2024 Shift 1 EE Paper',
  },
  {
    subjectCode: 'RRB_JE_POWER',
    topicKeyword: 'Transmission Lines',
    year: 2024,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Bundled conductors are primarily employed in Extra High Voltage (EHV) transmission lines to:',
    options: [
      { id: 'A', text: 'Reduce corona loss and radio interference by increasing self GMD' },
      { id: 'B', text: 'Increase line resistance to limit short-circuit current' },
      { id: 'C', text: 'Reduce the mechanical sag of the conductors' },
      { id: 'D', text: 'Eliminate skin effect completely' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'Bundled conductors increase the effective radius (Geometric Mean Radius or self GMD) of the conductor phase. This reduces the electric field gradient (voltage stress) at the conductor surface, significantly reducing corona loss, audible noise, and radio interference, while also reducing line inductance and increasing transmission capacity.',
    formulaConcept: '$r\'_{\\text{bundle}} = \\sqrt[n]{n \\cdot r \\cdot d^{n-1}}, \\quad E_{\\max} = \\frac{V}{r \\ln(D/r)}$',
    shortcutTrick: 'Bundled Conductors = Higher GMR = Reduced Corona & Lower Inductance.',
    commonMistake: 'Believing bundled conductors are used to increase mechanical strength.',
    sourceRef: 'RRB JE 2024 CBT-2 Shift 2',
  },

  // --- 2023 ---
  {
    subjectCode: 'RRB_JE_MACHINES',
    topicKeyword: 'Transformers',
    year: 2023,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In a transformer, open circuit (OC) test and short circuit (SC) test are performed respectively to determine:',
    options: [
      { id: 'A', text: 'Core losses and copper losses' },
      { id: 'B', text: 'Copper losses and core losses' },
      { id: 'C', text: 'Friction losses and windage losses' },
      { id: 'D', text: 'Insulation resistance only' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: '1. OC Test: Conducted at rated voltage on LV side with HV open. Measures Core (Iron) loss.\n2. SC Test: Conducted at reduced voltage with rated current. Measures full-load Copper loss ($I^2R$).',
    formulaConcept: '$P_{\\text{core}} = P_{\\text{hysteresis}} + P_{\\text{eddy}}$',
    shortcutTrick: 'OC = Open circuit (rated V) = Core Loss. SC = Short circuit (rated I) = Copper Loss ($I^2R$).',
    commonMistake: 'Reversing the order between OC and SC.',
    sourceRef: 'RRB JE 2023 CBT-2 Technical Paper',
  },
  {
    subjectCode: 'RRB_JE_POWER',
    topicKeyword: 'Transmission Lines',
    year: 2023,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The phenomenon in which the receiving end voltage of a long transmission line exceeds the sending end voltage at no-load or light load conditions is known as:',
    options: [
      { id: 'A', text: 'Ferranti Effect' },
      { id: 'B', text: 'Skin Effect' },
      { id: 'C', text: 'Proximity Effect' },
      { id: 'D', text: 'Corona Effect' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'The Ferranti Effect occurs in long transmission lines under no load or light load due to line charging current (capacitance). The voltage drop across line inductance due to charging current is in phase with sending voltage, resulting in $V_R > V_S$. Mitigated with shunt reactors.',
    formulaConcept: '$V_R - V_S \\approx \\frac{1}{2} \\omega^2 L C V_R$',
    shortcutTrick: 'VR > VS under light load = Ferranti. Cured by Shunt Reactor.',
    commonMistake: 'Confusing with Corona effect (violet glow & ozone smell).',
    sourceRef: 'RRB JE 2023 Technical Paper',
  },
  {
    subjectCode: 'RRB_JE_CIRCUITS',
    topicKeyword: 'Kirchhoff',
    year: 2023,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Kirchhoff\'s Current Law (KCL) and Kirchhoff\'s Voltage Law (KVL) are respectively based on the conservation of:',
    options: [
      { id: 'A', text: 'Charge and Energy' },
      { id: 'B', text: 'Energy and Charge' },
      { id: 'C', text: 'Momentum and Energy' },
      { id: 'D', text: 'Mass and Charge' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'KCL states $\\sum I_{\\text{in}} = \\sum I_{\\text{out}}$ (Conservation of Electric Charge at a node). KVL states $\\sum V = 0$ around any closed loop (Conservation of Energy).',
    formulaConcept: 'KCL $\\iff$ Conservation of Charge. KVL $\\iff$ Conservation of Energy.',
    shortcutTrick: 'KCL = Current = Charge (C with C). KVL = Voltage = Energy.',
    commonMistake: 'Reversing the order between charge and energy.',
    sourceRef: 'RRB JE 2023 CBT-2 Shift 2',
  },

  // --- 2022 ---
  {
    subjectCode: 'RRB_JE_MEAS',
    topicKeyword: 'PMMC',
    year: 2022,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A PMMC galvanometer has an internal resistance of $100\\,\\Omega$ and full-scale deflection current of $1\\,\\text{mA}$. What shunt resistance is required to convert it into an ammeter reading up to $1\\,\\text{A}$?',
    options: [
      { id: 'A', text: '$0.1001\\,\\Omega$' },
      { id: 'B', text: '$1.000\\,\\Omega$' },
      { id: 'C', text: '$10.0\\,\\Omega$' },
      { id: 'D', text: '$0.010\\,\\Omega$' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 35,
    explanation: 'Multiplying factor $m = \\frac{I}{I_m} = \\frac{1\\text{ A}}{1\\text{ mA}} = 1000$.\nShunt resistance $R_{sh} = \\frac{R_m}{m - 1} = \\frac{100}{1000 - 1} = \\frac{100}{999} \\approx 0.1001\\,\\Omega$.',
    formulaConcept: '$R_{sh} = \\frac{R_m}{m - 1}, \\quad m = \\frac{I}{I_m}$',
    shortcutTrick: '$R_{sh} \\approx R_m / m = 100 / 1000 = 0.1\\,\\Omega$. Pick closest value slightly above 0.1.',
    commonMistake: 'Using $m$ instead of $m - 1$ in exact denominator.',
    sourceRef: 'RRB JE 2022 CBT-2 Shift 1',
  },
  {
    subjectCode: 'RRB_JE_MACHINES',
    topicKeyword: 'DC Motors',
    year: 2022,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Which DC motor is best suited for electric traction locomotives due to its exceptionally high starting torque?',
    options: [
      { id: 'A', text: 'DC Series Motor' },
      { id: 'B', text: 'DC Shunt Motor' },
      { id: 'C', text: 'Cumulative Compound Motor' },
      { id: 'D', text: 'Differential Compound Motor' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'In a DC series motor, before magnetic saturation, field flux $\\Phi \\propto I_a$. Therefore torque $T \\propto \\Phi I_a \\propto I_a^2$. At starting when armature current is high, torque develops proportionally to the square of current, making it ideal for heavy starting loads like trains, cranes, and hoists.',
    formulaConcept: '$T_{\\text{start}} \\propto I_a^2$ (for series motor).',
    shortcutTrick: 'Traction / Cranes = DC Series Motor ($T \\propto I_a^2$). Constant speed machine tools = DC Shunt Motor.',
    commonMistake: 'Choosing DC shunt motor which has linear torque $T \\propto I_a$.',
    sourceRef: 'RRB JE 2022 CBT-2 Shift 2',
  },

  // --- 2021 ---
  {
    subjectCode: 'RRB_JE_MACHINES',
    topicKeyword: 'DC Motors',
    year: 2021,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'For speeds above rated speed, which method of speed control is employed in a DC shunt motor?',
    options: [
      { id: 'A', text: 'Field flux control (field weakening)' },
      { id: 'B', text: 'Armature voltage control' },
      { id: 'C', text: 'Armature resistance control' },
      { id: 'D', text: 'Tapped field control' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'In DC shunt motor:\n- Below rated base speed: Armature voltage control (Ward-Leonard) is used (Constant Torque drive).\n- Above rated base speed: Field flux control (field weakening by adding rheostat in shunt field) is used (Constant Power drive, since $N \\propto 1/\\Phi$).',
    formulaConcept: '$N \\propto \\frac{V - I_a R_a}{\\Phi}$',
    shortcutTrick: 'Above base speed = Field Weakening (Constant Power). Below base speed = Armature Control (Constant Torque).',
    commonMistake: 'Selecting armature resistance control for above rated speed.',
    sourceRef: 'RRB JE 2021 Technical Shift 2',
  },
  {
    subjectCode: 'RRB_JE_MEAS',
    topicKeyword: 'Bridges',
    year: 2021,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'Which AC bridge is specifically employed for the precise measurement of capacitance and dielectric loss / dissipation factor ($\\tan \\delta$) of high voltage cables?',
    options: [
      { id: 'A', text: 'Schering Bridge' },
      { id: 'B', text: 'Maxwell\'s Inductance Bridge' },
      { id: 'C', text: 'Anderson\'s Bridge' },
      { id: 'D', text: 'Hay\'s Bridge' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'Schering Bridge is used for measuring unknown capacitance and dielectric loss factor ($\\tan \\delta = \\omega C_4 R_4$) of insulating materials and high voltage cables. Anderson and Maxwell bridges measure inductance.',
    formulaConcept: '$\\tan \\delta = \\omega C_4 R_4$ (Schering Bridge).',
    shortcutTrick: 'Capacitance & Dielectric Loss = Schering Bridge. High-Q Inductance = Hay\'s Bridge. Low-Q Inductance = Maxwell Bridge.',
    commonMistake: 'Confusing Schering bridge with Anderson bridge.',
    sourceRef: 'RRB JE 2021 Electrical Paper',
  },

  // --- 2020 ---
  {
    subjectCode: 'RRB_JE_CIRCUITS',
    topicKeyword: 'AC Fundamentals',
    year: 2020,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In a series RLC circuit at resonant frequency $f_0$, what is the circuit impedance and the phase angle between voltage and current?',
    options: [
      { id: 'A', text: 'Impedance $Z = R$ (minimum) and phase angle $\\theta = 0^\\circ$ (unity power factor)' },
      { id: 'B', text: 'Impedance $Z = \\infty$ (maximum) and phase angle $\\theta = 90^\\circ$' },
      { id: 'C', text: 'Impedance $Z = \\sqrt{R^2 + (\\omega L)^2}$ and phase angle $\\theta = 45^\\circ$' },
      { id: 'D', text: 'Impedance $Z = 0$ and phase angle $\\theta = -90^\\circ$' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 25,
    explanation: 'At series resonance: $X_L = X_C \\implies \\omega L = 1/(\\omega C)$. Net reactance $X = X_L - X_C = 0$. Total impedance $Z = \\sqrt{R^2 + 0^2} = R$ (purely resistive and minimum). Hence current is maximum and in phase with voltage ($\\cos \\theta = 1.0$).',
    formulaConcept: '$f_0 = \\frac{1}{2\\pi \\sqrt{LC}}, \\quad Z_{\\text{res}} = R$',
    shortcutTrick: 'Series Resonance: Z is minimum (= R), Current is maximum, power factor is unity.',
    commonMistake: 'Confusing series resonance (minimum Z) with parallel resonance (maximum Z / dynamic impedance).',
    sourceRef: 'RRB JE 2020 Stage 2 Paper',
  },
  {
    subjectCode: 'RRB_JE_MACHINES',
    topicKeyword: 'Synchronous',
    year: 2020,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'An over-excited synchronous motor operates at what power factor?',
    options: [
      { id: 'A', text: 'Leading power factor' },
      { id: 'B', text: 'Lagging power factor' },
      { id: 'C', text: 'Unity power factor' },
      { id: 'D', text: 'Zero power factor lagging' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'In a synchronous motor:\n- Over-excited ($E_b > V$): Draws leading current, acts as a synchronous condenser (supplies reactive power $Q$).\n- Under-excited ($E_b < V$): Draws lagging current.\n- Normal excitation ($E_b = V \\cos \\delta$): Unity power factor.',
    formulaConcept: 'Synchronous Motor: Over-excited = Leading pf; Under-excited = Lagging pf. (Opposite of synchronous generator!).',
    shortcutTrick: 'Over-excited MOTOR = Leading (like capacitor). Over-excited GENERATOR = Lagging (like inductor).',
    commonMistake: 'Confusing synchronous motor excitation with synchronous generator excitation.',
    sourceRef: 'RRB JE 2020 Technical Shift 2',
  },

  // --- 2019 ---
  {
    subjectCode: 'RRB_JE_POWER',
    topicKeyword: 'Switchgear',
    year: 2019,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A Buchholz relay is installed in oil-immersed transformers between the:',
    options: [
      { id: 'A', text: 'Main tank and the conservator tank' },
      { id: 'B', text: 'Conservator tank and the breather' },
      { id: 'C', text: 'HV bushing and LV bushing' },
      { id: 'D', text: 'Main tank and radiator tubes' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 20,
    explanation: 'A Buchholz relay is a gas-actuated protective device installed in the connecting pipe between the main transformer tank and the conservator tank. It detects slow/incipient internal faults (gives alarm) and severe short circuit faults (trips circuit breaker).',
    formulaConcept: 'Buchholz relay = Gas-operated relay for internal transformer faults (> 500 kVA).',
    shortcutTrick: 'Buchholz = Bridge between Main Tank and Conservator.',
    commonMistake: 'Placing it between conservator and silica gel breather.',
    sourceRef: 'RRB JE 2019 CBT-2 Shift 1',
  },
  {
    subjectCode: 'RRB_JE_CIRCUITS',
    topicKeyword: 'Network Theorems',
    year: 2019,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The Superposition Theorem is applicable only to circuits that contain:',
    options: [
      { id: 'A', text: 'Linear and bilateral network elements' },
      { id: 'B', text: 'Non-linear elements like diodes and transistors' },
      { id: 'C', text: 'Unilateral elements only' },
      { id: 'D', text: 'Time-varying non-linear resistances' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.33,
    avgExpectedSeconds: 15,
    explanation: 'The Superposition Theorem is based on the linearity principle ($f(x_1 + x_2) = f(x_1) + f(x_2)$ and $f(ax) = a f(x)$). It requires that all circuit components have linear voltage-current characteristics and are bilateral.',
    formulaConcept: 'Superposition Condition: System must obey Additivity and Homogeneity (Linearity).',
    shortcutTrick: 'Superposition = Linear & Bilateral only. Cannot calculate power directly ($P \\propto I^2$ is non-linear).',
    commonMistake: 'Applying superposition theorem directly to power calculations.',
    sourceRef: 'RRB JE 2019 Shift 2 Technical Paper',
  },
];
