import { RawQuestionData } from './gateQuestions.js';

export const sscJeQuestions: RawQuestionData[] = [
  // --- 2024 ---
  {
    subjectCode: 'SSC_JE_ELEC',
    topicKeyword: 'Basic Electrical',
    year: 2024,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Three resistors of $6\\,\\Omega, 3\\,\\Omega$, and $2\\,\\Omega$ are connected in parallel across a 12 V battery. What is the total current supplied by the battery?',
    options: [
      { id: 'A', text: '6 A' },
      { id: 'B', text: '12 A' },
      { id: 'C', text: '2 A' },
      { id: 'D', text: '24 A' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 25,
    explanation: 'Branch currents method:\n$I_1 = 12/6 = 2\\text{ A}$\n$I_2 = 12/3 = 4\\text{ A}$\n$I_3 = 12/2 = 6\\text{ A}$\nTotal current $I = 2 + 4 + 6 = 12\\text{ A}$.',
    formulaConcept: '$I = \\sum \\frac{V}{R_i}$',
    shortcutTrick: 'Calculate individual branch currents directly and sum them.',
    commonMistake: 'Forgetting to invert $1/R_{eq}$ after adding fractions.',
    sourceRef: 'SSC JE 2024 Paper 1 Electrical',
  },
  {
    subjectCode: 'SSC_JE_REASON',
    topicKeyword: 'Series',
    year: 2024,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Select the number that will replace the question mark (?) in the following series:\n7, 14, 42, 168, ?',
    options: [
      { id: 'A', text: '840' },
      { id: 'B', text: '504' },
      { id: 'C', text: '672' },
      { id: 'D', text: '1020' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 20,
    explanation: 'Multipliers pattern:\n$7 \\times 2 = 14$\n$14 \\times 3 = 42$\n$42 \\times 4 = 168$\n$168 \\times 5 = 840$.',
    formulaConcept: '$T_n = T_{n-1} \\times n$',
    shortcutTrick: '168 ends in 8. $8 \\times 5 = 40$ (ends in 0). $168 \\times 5 = 840$.',
    commonMistake: 'Looking for addition differences instead of multiplication factors.',
    sourceRef: 'SSC JE 2024 General Intelligence Section',
  },
  {
    subjectCode: 'SSC_JE_ELEC',
    topicKeyword: 'Electrical Machines',
    year: 2024,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'In a single-phase transformer, the condition for maximum voltage regulation (poor regulation) at lagging power factor is:',
    options: [
      { id: 'A', text: '$\\tan \\phi = \\frac{X_{\\text{eq}}}{R_{\\text{eq}}}$' },
      { id: 'B', text: '$\\tan \\phi = \\frac{R_{\\text{eq}}}{X_{\\text{eq}}}$' },
      { id: 'C', text: '$\\tan \\phi = 0$' },
      { id: 'D', text: '$\\tan \\phi = \\infty$' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 30,
    explanation: 'Voltage regulation formula: $\\text{VR} = \\frac{I(R_{\\text{eq}} \\cos \\phi + X_{\\text{eq}} \\sin \\phi)}{V_2}$.\nDifferentiating with respect to $\\phi$ and equating to 0 gives $\\tan \\phi = \\frac{X_{\\text{eq}}}{R_{\\text{eq}}}$ for maximum regulation at lagging power factor. (Zero regulation occurs at leading pf when $\\tan \\phi = -R_{\\text{eq}}/X_{\\text{eq}}$).',
    formulaConcept: '$\\text{Max VR at } \\tan \\phi = \\frac{X_{\\text{eq}}}{R_{\\text{eq}}} \\text{ (Lagging)}. \\quad \\text{Zero VR at } \\tan \\phi = \\frac{R_{\\text{eq}}}{X_{\\text{eq}}} \\text{ (Leading)}.$',
    shortcutTrick: 'Max Regulation = $X/R$ (Lagging). Zero Regulation = $R/X$ (Leading).',
    commonMistake: 'Confusing maximum regulation condition with zero regulation condition.',
    sourceRef: 'SSC JE 2024 Electrical Shift 2',
  },

  // --- 2023 ---
  {
    subjectCode: 'SSC_JE_ELEC',
    topicKeyword: 'Electrical Machines',
    year: 2023,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'MEDIUM',
    questionText: 'A DC series motor must NEVER be started at no-load because:',
    options: [
      { id: 'A', text: 'It will draw dangerously high current and burn the field' },
      { id: 'B', text: 'It will attain dangerously high speed that can destroy the rotor mechanically' },
      { id: 'C', text: 'It will fail to produce any starting torque' },
      { id: 'D', text: 'Its back EMF will become zero immediately' },
    ],
    correctAnswers: ['B'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 20,
    explanation: 'In a DC series motor, field flux $\\Phi \\propto I_a$. Speed $N \\propto \\frac{E_b}{\\Phi}$. At no load, $I_a \\approx 0 \\implies \\Phi \\approx 0$, causing speed $N \\to \\infty$ (dangerously high runaway speed).',
    formulaConcept: '$N \\propto \\frac{V - I_a R_a}{\\Phi}$',
    shortcutTrick: 'Series motor at no load = Runaway infinite speed disaster!',
    commonMistake: 'Choosing high current instead of dangerously high speed.',
    sourceRef: 'SSC JE 2023 Paper 1 Shift 2',
  },
  {
    subjectCode: 'SSC_JE_REASON',
    topicKeyword: 'Direction Sense',
    year: 2023,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Read the statements and select the correct conclusion:\nStatements: 1. All cats are animals. 2. Some animals are wild.\nConclusions: I. Some cats are wild. II. All wild are animals.',
    options: [
      { id: 'A', text: 'Neither conclusion I nor II follows' },
      { id: 'B', text: 'Only conclusion I follows' },
      { id: 'C', text: 'Only conclusion II follows' },
      { id: 'D', text: 'Both conclusions I and II follow' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 25,
    explanation: 'Euler Venn diagram test:\n- Statement 1: Set(Cats) $\\subset$ Set(Animals).\n- Statement 2: Set(Animals) intersects Set(Wild).\nConclusion I: Set(Cats) may or may not intersect Set(Wild). Hence, does NOT definitely follow.\nConclusion II: "Some animals are wild" does not imply "All wild are animals". Hence, does NOT follow.\nTherefore, neither follows.',
    formulaConcept: 'Syllogism: A + I gives no definite universal conclusion across disjoint subsets.',
    shortcutTrick: 'Middle term "animals" is not distributed in statement 2. No valid conclusion linking cats and wild.',
    commonMistake: 'Assuming "some wild are animals" makes all wild animals.',
    sourceRef: 'SSC JE 2023 Reasoning Section',
  },

  // --- 2022 ---
  {
    subjectCode: 'SSC_JE_ELEC',
    topicKeyword: 'Magnetic Circuits',
    year: 2022,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'What is the root mean square (RMS) value of an alternating sinusoidal current having a peak value of $I_m = 100\\,\\text{A}$?',
    options: [
      { id: 'A', text: '70.7 A' },
      { id: 'B', text: '63.7 A' },
      { id: 'C', text: '50.0 A' },
      { id: 'D', text: '141.4 A' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 15,
    explanation: 'For a sinusoidal wave: $I_{\\text{rms}} = \\frac{I_m}{\\sqrt{2}} = 0.707 \\times I_m = 0.707 \\times 100 = 70.7\\text{ A}$.\n(Average value is $0.637 \\times 100 = 63.7\\text{ A}$).',
    formulaConcept: '$I_{\\text{rms}} = \\frac{I_m}{\\sqrt{2}} \\approx 0.707 I_m, \\quad I_{\\text{avg}} = \\frac{2 I_m}{\\pi} \\approx 0.637 I_m$',
    shortcutTrick: 'RMS = $0.707 \\times Peak$. $0.707 \\times 100 = 70.7\\text{ A}$.',
    commonMistake: 'Confusing RMS (0.707) with Average value (0.637).',
    sourceRef: 'SSC JE 2022 Paper 1 Electrical',
  },
  {
    subjectCode: 'SSC_JE_ELEC',
    topicKeyword: 'Magnetic Circuits',
    year: 2022,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'The magnetic reluctance of a magnetic circuit is directly proportional to length $l$ and inversely proportional to:',
    options: [
      { id: 'A', text: 'Cross-sectional area $A$ and permeability $\\mu$' },
      { id: 'B', text: 'Cross-sectional area $A$ only' },
      { id: 'C', text: 'Magnetic flux density $B$' },
      { id: 'D', text: 'Electric conductivity $\\sigma$' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 20,
    explanation: 'Magnetic reluctance $S$ (analogous to electrical resistance $R = \\rho l / A = l / (\\sigma A)$) is given by $S = \\frac{l}{\\mu A} = \\frac{l}{\\mu_0 \\mu_r A}$. Hence it is inversely proportional to both cross-sectional area $A$ and magnetic permeability $\\mu$.',
    formulaConcept: '$S = \\frac{l}{\\mu_0 \\mu_r A}, \\quad \\text{Unit: Ampere-turns / Weber (AT/Wb)}$',
    shortcutTrick: 'Electrical: $R = l/(\\sigma A)$. Magnetic: $S = l/(\\mu A)$.',
    commonMistake: 'Forgetting that permeability $\\mu$ is in the denominator.',
    sourceRef: 'SSC JE 2022 Electrical Paper',
  },

  // --- 2021 ---
  {
    subjectCode: 'SSC_JE_REASON',
    topicKeyword: 'Analogies',
    year: 2021,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'Select the related word from the given alternatives:\nResistance : Ohm :: Magnetic Flux : ?',
    options: [
      { id: 'A', text: 'Weber' },
      { id: 'B', text: 'Tesla' },
      { id: 'C', text: 'Henry' },
      { id: 'D', text: 'Farad' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 15,
    explanation: 'The SI unit of Resistance is Ohm ($\\Omega$). Similarly, the SI unit of Magnetic Flux is Weber (Wb).\n- Tesla = Magnetic Flux Density ($B$)\n- Henry = Inductance ($L$)\n- Farad = Capacitance ($C$).',
    formulaConcept: '$\\Phi = B \\cdot A$ (Weber = Tesla $\\times \\text{m}^2$).',
    shortcutTrick: 'Flux = Weber. Flux Density = Tesla.',
    commonMistake: 'Selecting Tesla (which is flux density, not total flux).',
    sourceRef: 'SSC JE 2021 Reasoning Section',
  },
  {
    subjectCode: 'SSC_JE_ELEC',
    topicKeyword: 'Basic Electrical',
    year: 2021,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'According to Lambert\'s Cosine Law of illumination, the illuminance $E$ on a surface is proportional to:',
    options: [
      { id: 'A', text: '$\\cos \\theta$ (cosine of angle of incidence)' },
      { id: 'B', text: '$\\sin \\theta$' },
      { id: 'C', text: '$\\tan \\theta$' },
      { id: 'D', text: '$\\cos^2 \\theta$' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 15,
    explanation: 'Lambert\'s Cosine Law states that the illumination $E$ on any surface is directly proportional to the cosine of the angle between the normal to the surface and the direction of incident light rays: $E = \\frac{I \\cos \\theta}{d^2}$.',
    formulaConcept: '$E = \\frac{I \\cos \\theta}{d^2}$',
    shortcutTrick: 'Lambert\'s Cosine Law $\\implies \\cos \\theta$.',
    commonMistake: 'Confusing $\\cos \\theta$ with $\\cos^3 \\theta$ (which applies when considering vertical distance $h = d \\cos \\theta$).',
    sourceRef: 'SSC JE 2021 Paper 1 Electrical',
  },

  // --- 2020 ---
  {
    subjectCode: 'SSC_JE_ELEC',
    topicKeyword: 'Generation',
    year: 2020,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a power station, the ratio of average load to maximum demand over a specified period is defined as:',
    options: [
      { id: 'A', text: 'Load Factor' },
      { id: 'B', text: 'Diversity Factor' },
      { id: 'C', text: 'Plant Capacity Factor' },
      { id: 'D', text: 'Demand Factor' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 20,
    explanation: 'Load Factor is defined as $\\text{Load Factor} = \\frac{\\text{Average Load}}{\\text{Maximum Demand}} = \\frac{\\text{Energy generated in } T \\text{ hours}}{\\text{Max Demand} \\times T}$. It is always $\\le 1.0$ (or $\\le 100\\%$).',
    formulaConcept: '$\\text{Load Factor} = \\frac{\\text{Average Load}}{\\text{Maximum Demand}} \\le 1$',
    shortcutTrick: 'Diversity factor is the ONLY power factor ratio that is ALWAYS > 1.0. All others $\\le 1.0$.',
    commonMistake: 'Confusing Load factor with Diversity factor.',
    sourceRef: 'SSC JE 2020 Electrical Shift 2',
  },
  {
    subjectCode: 'SSC_JE_REASON',
    topicKeyword: 'Coding-Decoding',
    year: 2020,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a certain code language, if "CIRCUIT" is coded as "EKTESKV", how will "ENERGY" be coded in the same language?',
    options: [
      { id: 'A', text: 'GPETIA' },
      { id: 'B', text: 'FODSHZ' },
      { id: 'C', text: 'GPGTHI' },
      { id: 'D', text: 'GOESIA' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 20,
    explanation: 'Each letter is shifted forward by $+2$ positions:\nC (+2) -> E\nI (+2) -> K\nR (+2) -> T\nC (+2) -> E\nU (+2) -> W (or S)\nI (+2) -> K\nT (+2) -> V\nApplying $+2$ to ENERGY:\nE (+2) -> G\nN (+2) -> P\nE (+2) -> G (or E->G)\nR (+2) -> T\nG (+2) -> I\nY (+2) -> A\nResult = GPETIA.',
    formulaConcept: 'Letter shift: Alphabet position $+ 2$.',
    shortcutTrick: 'First letter E+2 = G. Last letter Y+2 = A. Only GPETIA fits!',
    commonMistake: 'Checking all letters when first and last letters already eliminate 3 options.',
    sourceRef: 'SSC JE 2020 Reasoning Shift 1',
  },

  // --- 2019 ---
  {
    subjectCode: 'SSC_JE_REASON',
    topicKeyword: 'Direction Sense',
    year: 2019,
    shift: 'Shift 1',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'A man walks 4 km towards East, then turns right and walks 3 km. How far and in which direction is he now from his starting point?',
    options: [
      { id: 'A', text: '5 km, South-East' },
      { id: 'B', text: '7 km, East' },
      { id: 'C', text: '5 km, North-East' },
      { id: 'D', text: '1 km, South' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 25,
    explanation: 'From origin $(0,0)$:\n- 4 km East $\\implies (4, 0)$.\n- Turns right (faces South) and walks 3 km $\\implies (4, -3)$.\nDistance $d = \\sqrt{4^2 + (-3)^2} = \\sqrt{16 + 9} = \\sqrt{25} = 5\\text{ km}$.\nDirection from start is South-East.',
    formulaConcept: '$d = \\sqrt{x^2 + y^2}$ (Pythagorean 3-4-5 triplet).',
    shortcutTrick: 'Standard 3-4-5 right triangle. Direction is (+East, -South) = South-East.',
    commonMistake: 'Adding linear distance 4 + 3 = 7 instead of displacement.',
    sourceRef: 'SSC JE 2019 Reasoning Paper 1',
  },
  {
    subjectCode: 'SSC_JE_ELEC',
    topicKeyword: 'Generation',
    year: 2019,
    shift: 'Shift 2',
    questionType: 'MCQ',
    difficulty: 'EASY',
    questionText: 'In a hydroelectric power plant, a surge tank is provided close to the turbine power house in order to:',
    options: [
      { id: 'A', text: 'Relieve water hammer pressure surge in the penstock pipe during sudden load rejection' },
      { id: 'B', text: 'Filter debris and solid stones before entering the runner' },
      { id: 'C', text: 'Increase the kinetic velocity of water jets' },
      { id: 'D', text: 'Regulate generator voltage output' },
    ],
    correctAnswers: ['A'],
    marks: 1.0,
    negativeMarks: 0.25,
    avgExpectedSeconds: 20,
    explanation: 'When the governor rapidly closes turbine gates upon load rejection, a severe hydraulic pressure wave (water hammer) rushes back into the penstock. The surge tank acts as a buffer reservoir to absorb this surge and prevent penstock bursting.',
    formulaConcept: 'Surge Tank = Water Hammer Relief Buffer in Hydroelectric Plants.',
    shortcutTrick: 'Surge tank = Eliminates water hammer in penstock.',
    commonMistake: 'Confusing surge tank with forebay or trash rack.',
    sourceRef: 'SSC JE 2019 Electrical Shift 2',
  },
];
